### ISSUE TITLE
MqttIO CheckpointMark decoding randomly fails

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#18560]
Randomly, the decoding of MQTT CheckpointMark randomly fails:

```

Caused by: org.apache.beam.sdk.coders.CoderException: 95 unexpected extra bytes after decoding org.apache.beam.sdk.io.mqtt.MqttIO$MqttCheckpointMark@14922739
	at
org.apache.beam.sdk.util.CoderUtils.decodeFromByteArray(CoderUtils.java:116)
	at org.apache.beam.sdk.util.CoderUtils.decodeFromByteArray(CoderUtils.java:107)
	at
org.apache.beam.sdk.util.CoderUtils.clone(CoderUtils.java:156)
	at org.apache.beam.runners.direct.UnboundedReadEvaluatorFactory$UnboundedReadEvaluator.getReader(UnboundedReadEvaluatorFactory.java:191)
	at
org.apache.beam.runners.direct.UnboundedReadEvaluatorFactory$UnboundedReadEvaluator.processElement(UnboundedReadEvaluatorFactory.java:127)
	at
org.apache.beam.runners.direct.TransformExecutor.processElements(TransformExecutor.java:146)
	at org.apache.beam.runners.direct.TransformExecutor.run(TransformExecutor.java:110)
	at
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at
java.lang.Thread.run(Thread.java:745)

```

It happens especially when the number of messages to consume from the MQTT topic is high.

Imported from Jira [BEAM-3274](https://issues.apache.org/jira/browse/BEAM-3274). Original Jira may contain additional context.
Reported by: jbonofre.

**Comment by Abacn** [comment]
fixed by #36056
