### ISSUE TITLE
Bumping com.google.cloud.bigdataoss:gcsio and :util to 1.9.2 causes tests to fail

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#19087]
Current version in Beam: 1.4.5

Latest released version: 1.9.2

Test failure:

```

java.lang.NullPointerException at com.google.cloud.hadoop.gcsio.GoogleCloudStorageReadChannel.createRequest(GoogleCloudStorageReadChannel.java:966) at com.google.cloud.hadoop.gcsio.GoogleCloudStorageReadChannel.getMetadata(GoogleCloudStorageReadChannel.java:765) at com.google.cloud.hadoop.gcsio.GoogleCloudStorageReadChannel.initEncodingAndSize(GoogleCloudStorageReadChannel.java:754) at com.google.cloud.hadoop.gcsio.GoogleCloudStorageReadChannel.<init\>(GoogleCloudStorageReadChannel.java:210) at com.google.cloud.hadoop.gcsio.GoogleCloudStorageReadChannel.<init\>(GoogleCloudStorageReadChannel.java:172) at org.apache.beam.sdk.util.GcsUtilTest.testGCSChannelCloseIdempotent(GcsUtilTest.java:774)

```

 

Imported from Jira [BEAM-5034](https://issues.apache.org/jira/browse/BEAM-5034). Original Jira may contain additional context.
Reported by: garrettjonesgoogle.

**Comment by Abacn** [comment]
.close-issue not_planned
