### ISSUE TITLE
testSideInputUnbounded completion and timeout race

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#19336]
https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/1739/testReport/junit/org.apache.beam.sdk.transforms/SplittableDoFnTest/testSideInputUnbounded/
https://pantheon.corp.google.com/dataflow/jobsDetail/locations/us-central1/jobs/2018-12-26_17_37_02-9764896340592912014?project=apache-beam-testing

Job timed out at 600 seconds, had successfully completed and was cleaning up when canceled.

Imported from Jira [BEAM-6323](https://issues.apache.org/jira/browse/BEAM-6323). Original Jira may contain additional context.
Reported by: apilloud.

**Comment by TheNeuralBit** [comment]
There's only one instance of this test failing in Jenkins history and that was a correlated failure with other tests, due to a quota issue: https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/8440/testReport/junit/org.apache.beam.sdk.transforms/SplittableDoFnTest/testSideInputUnbounded/
```
java.lang.RuntimeException: Workflow failed. Causes: The quota check has failed., Requested quota metric In Use Addresses is currently unavailable.
	at org.apache.beam.runners.dataflow.TestDataflowRunner.run(TestDataflowRunner.java:141)
	at org.apache.beam.runners.dataflow.TestDataflowRunner.run(TestDataflowRunner.java:93)
	at org.apache.beam.runners.dataflow.TestDataflowRunner.run(TestDataflowRunner.java:55)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:323)
	at org.apache.beam.sdk.testing.TestPipeline.run(TestPipeline.java:399)
	at org.apache.beam.sdk.testing.TestPipeline.run(TestPipeline.java:335)
	at org.apache.beam.sdk.transforms.SplittableDoFnTest.testSideInput(SplittableDoFnTest.java:451)
	at org.apache.beam.sdk.transforms.SplittableDoFnTest.testSideInputUnbounded(SplittableDoFnTest.java:433)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```
