### ISSUE TITLE
:sdks:python:portableWordCountBatch out of memory in python precommit

### ISSUE THREAD

**Issue by damccorm** [apache/beam#19634]
https://builds.apache.org/job/beam_PreCommit_Portable_Python_Commit/4989/consoleFull

```

11:46:20 OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000735d80000, 716701696, 0)
failed; error='Cannot allocate memory' (errno=12)
11:46:20 #
11:46:20 # There is insufficient memory
for the Java Runtime Environment to continue.
11:46:20 # Native memory allocation (mmap) failed to
map 716701696 bytes for committing reserved memory.
11:46:20 # An error report file with more information
is saved as:
11:46:20 # /opt/apache/beam/hs_err_pid6.log
11:46:20 Traceback (most recent call last):
11:46:20
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
11:46:20     "__main__", fname,
loader, pkg_name)
11:46:20   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
11:46:20  
  exec code in run_globals
11:46:20   File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Portable_Python_Commit/src/sdks/python/apache_beam/examples/wordcount.py",
line 135, in <module>
11:46:20     run()
11:46:20   File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Portable_Python_Commit/src/sdks/python/apache_beam/examples/wordcount.py",
line 115, in run
11:46:20     result.wait_until_finish()
11:46:20   File "apache_beam/runners/portability/portable_runner.py",
line 436, in wait_until_finish
11:46:20     for state_response in self._state_stream:
11:46:20   File
"/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Portable_Python_Commit/src/build/gradleenv/1922375555/local/lib/python2.7/site-packages/grpc/_channel.py",
line 367, in next
11:46:20     return self._next()
11:46:20   File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Portable_Python_Commit/src/build/gradleenv/1922375555/local/lib/python2.7/site-packages/grpc/_channel.py",
line 358, in _next
11:46:20     raise self
11:46:20 grpc._channel._Rendezvous: <_Rendezvous of RPC
that terminated with:
11:46:20 	status = StatusCode.UNAVAILABLE
11:46:20 	details = "Socket closed"
11:46:20
	debug_error_string = "{"created":"@1564166775.203261226","description":"Error received from peer ipv4:127.0.0.1:35209","file":"src/core/lib/surface/call.cc","file_line":1052,"grpc_message":"Socket
closed","grpc_status":14}"
11:46:20 >
11:46:20 Exception in thread wait_until_finish_read:
11:46:20
Traceback (most recent call last):
11:46:20   File "/usr/lib/python2.7/threading.py", line 801, in
__bootstrap_inner
11:46:20     self.run()
11:46:20   File "/usr/lib/python2.7/threading.py", line
754, in run
11:46:20     self.__target(*self.__args, **self.__kwargs)
11:46:20   File "apache_beam/runners/portability/portable_runner.py",
line 418, in read_messages
11:46:20     for message in self._message_stream:
11:46:20   File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Portable_Python_Commit/src/build/gradleenv/1922375555/local/lib/python2.7/site-packages/grpc/_channel.py",
line 367, in next
11:46:20     return self._next()
11:46:20   File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Portable_Python_Commit/src/build/gradleenv/1922375555/local/lib/python2.7/site-packages/grpc/_channel.py",
line 358, in _next
11:46:20     raise self
11:46:20 _Rendezvous: <_Rendezvous of RPC that terminated
with:
11:46:20 	status = StatusCode.UNAVAILABLE
11:46:20 	details = "Socket closed"
11:46:20 	debug_error_string
= "{"created":"@1564166775.203284918","description":"Error received from peer ipv4:127.0.0.1:35209","file":"src/core/lib/surface/call.cc","file_line":1052,"grpc_message":"Socket
closed","grpc_status":14}"
11:46:20 >

```

Imported from Jira [BEAM-7831](https://issues.apache.org/jira/browse/BEAM-7831). Original Jira may contain additional context.
Reported by: udim.

**Comment by damccorm** [comment]
This is currently consistently healthy
