### ISSUE TITLE
portable python precommit error: failure in python setup.py egg_info

### ISSUE THREAD

**Issue by damccorm** [apache/beam#19896]
[~markflyhigh]

```

16:53:13     Traceback (most recent call last):
16:53:13       File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Portable_Python_Commit/src/build/gradleenv/1866363813/bin/futurize",
line 10, in <module>
16:53:13         sys.exit(main())
16:53:13       File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Portable_Python_Commit/src/build/gradleenv/1866363813/local/lib/python2.7/site-packages/libfuturize/main.py",
line 293, in main
16:53:13         options.processes)
16:53:13       File "/usr/lib/python2.7/lib2to3/refactor.py",
line 706, in refactor
16:53:13         items, write, doctests_only)
16:53:13       File "/usr/lib/python2.7/lib2to3/refactor.py",
line 299, in refactor
16:53:13         self.refactor_dir(dir_or_file, write, doctests_only)
16:53:13
      File "/usr/lib/python2.7/lib2to3/refactor.py", line 319, in refactor_dir
16:53:13         self.refactor_file(fullname,
write, doctests_only)
16:53:13       File "/usr/lib/python2.7/lib2to3/refactor.py", line 747, in refactor_file
16:53:13
        *args, **kwargs)
16:53:13       File "/usr/lib/python2.7/lib2to3/refactor.py", line 358, in
refactor_file
16:53:13         write=write, encoding=encoding)
16:53:13       File "/usr/lib/python2.7/lib2to3/refactor.py",
line 514, in processed_file
16:53:13         old_text = self._read_python_source(filename)[0]
16:53:13
      File "/usr/lib/python2.7/lib2to3/refactor.py", line 336, in _read_python_source
16:53:13    
    with _open_with_encoding(filename, "r", encoding=encoding) as f:
16:53:13       File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Portable_Python_Commit/src/build/gradleenv/1866363813/lib/python2.7/codecs.py",
line 896, in open
16:53:13         file = __builtin__.open(filename, mode, buffering)
16:53:13   
 IOError: [Errno 2] No such file or directory: '/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Portable_Python_Commit/src/sdks/python/apache_beam/portability/api/beam_job_api_pb2.py'
16:53:13
    Traceback (most recent call last):
16:53:13       File "<string>", line 1, in <module>
16:53:13
      File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Portable_Python_Commit/src/sdks/python/setup.py",
line 246, in <module>
16:53:13         'test': generate_protos_first(test),
16:53:13       File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Portable_Python_Commit/src/build/gradleenv/1866363813/local/lib/python2.7/site-packages/setuptools/__init__.py",
line 145, in setup
16:53:13         return distutils.core.setup(**attrs)
16:53:13       File "/usr/lib/python2.7/distutils/core.py",
line 151, in setup
16:53:13         dist.run_commands()
16:53:13       File "/usr/lib/python2.7/distutils/dist.py",
line 953, in run_commands
16:53:13         self.run_command(cmd)
16:53:13       File "/usr/lib/python2.7/distutils/dist.py",
line 972, in run_command
16:53:13         cmd_obj.run()
16:53:13       File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Portable_Python_Commit/src/sdks/python/setup.py",
line 173, in run
16:53:13         gen_protos.generate_proto_files()
16:53:13       File "gen_protos.py",
line 135, in generate_proto_files
16:53:13         'Error applying futurize to generated protobuf python
files.')
16:53:13     RuntimeError: Error applying futurize to generated protobuf python files.
16:53:13
    ----------------------------------------
16:53:13 ERROR: Command errored out with exit status 1:
python setup.py egg_info Check the logs for full command output.

```

https://builds.apache.org/job/beam_PreCommit_Portable_Python_Commit/6070/console

Imported from Jira [BEAM-8249](https://issues.apache.org/jira/browse/BEAM-8249). Original Jira may contain additional context.
Reported by: udim.

**Comment by Abacn** [comment]
.close-issue not_planned
