### ISSUE TITLE
Method not found: org.apache.beam.model.job_management.v1.ArtifactStagingService/ReverseArtifactRetrievalService

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20150]
This affects both the Flink and Spark portable runners. It does not appear to cause pipelines to fail.

13:24:17 ERROR:grpc._channel:Exception iterating requests!
13:24:17 Traceback (most recent call last):
13:24:17   File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python2_PVR_Flink_Commit/src/build/gradleenv/1866363813/local/lib/python2.7/site-packages/grpc/_channel.py", line 195, in consume_request_iterator
13:24:17     request = next(request_iterator)
13:24:17   File "apache_beam/runners/portability/artifact_service.py", line 316, in __next__
13:24:17     raise self._queue.get()
13:24:17 _MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
13:24:17 	status = StatusCode.UNIMPLEMENTED
13:24:17 	details = "Method not found: org.apache.beam.model.job_management.v1.ArtifactStagingService/ReverseArtifactRetrievalService"
13:24:17 	debug_error_string = "{"created":"@1588008257.670646906","description":"Error received from peer ipv4:127.0.0.1:37747","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Method not found: org.apache.beam.model.job_management.v1.ArtifactStagingService/ReverseArtifactRetrievalService","grpc_status":12}"
13:24:17 \>

Imported from Jira [BEAM-9793](https://issues.apache.org/jira/browse/BEAM-9793). Original Jira may contain additional context.
Reported by: ibzib.
Subtask of issue #20148

**Comment by Shrhawk** [comment]
@damccorm the job goes into stale state after this error
