### ISSUE TITLE
Flink 1.10 failing [Java 11]

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20294]
Gradle task _*:runners:flink:1.10:generatePipelineOptionsTableJava*_ fails during Java 11 Precommit job 

Example stack trace
```

> Task :runners:flink:1.10:generatePipelineOptionsTableJava FAILED
...
Error: A JNI error has occurred,
please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError:
org/apache/beam/runners/flink/website/PipelineOptionsTableGenerator has been compiled by a more recent
version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes
class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at
java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at
java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at
java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native
Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at
sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at
sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
:runners:flink:1.10:generatePipelineOptionsTableJava
(Thread[Execution worker for ':' Thread 11,5,main]) completed. Took 1.744 secs.

```

Imported from Jira [BEAM-10087](https://issues.apache.org/jira/browse/BEAM-10087). Original Jira may contain additional context.
Reported by: pawel.pasterz.
Subtask of issue #20290

**Comment by Abacn** [comment]
.close-issue not_planned
