### ISSUE TITLE
Flaky test: org.apache.beam.runners.samza.adapter.UnboundedSourceSystemTest.testMultipleAdvanceWatermark

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20376]
Jenkins build log:

 
###  
```

Error Message
java.lang.AssertionError: expected:<[IncomingMessageEnvelope [systemStreamPartition=SystemStreamPartition
[default-system, default-system, 0], offset=rO0ABXNyADhvcmcuYXBhY2hlLmJlYW0ucnVubmVycy5zYW16YS5hZGFwdGVyLlRlc3RDaGVja3BvaW50TWFya08DLHpyVql6AgABSQAKY2hlY2twb2ludHhwAAAAAA==,
key=null, message=OpMessage{type=ELEMENT, element=TimestampedValueInGlobalWindow{value=first, timestamp=2020-07-16T22:19:29.109Z,
pane=PaneInfo.NO_FIRING}, viewId='null', viewElements=null}, eventTime=0, arrivalTime=1594937969136],
IncomingMessageEnvelope [systemStreamPartition=SystemStreamPartition [default-system, default-system,
0], offset=null, key=null, message=org.apache.samza.system.WatermarkMessage@59b60c67, eventTime=0, arrivalTime=1594937969136]]>
but was:<[IncomingMessageEnvelope [systemStreamPartition=SystemStreamPartition [default-system, default-system,
0], offset=rO0ABXNyADhvcmcuYXBhY2hlLmJlYW0ucnVubmVycy5zYW16YS5hZGFwdGVyLlRlc3RDaGVja3BvaW50TWFya08DLHpyVql6AgABSQAKY2hlY2twb2ludHhwAAAAAA==,
key=null, message=OpMessage{type=ELEMENT, element=TimestampedValueInGlobalWindow{value=first, timestamp=2020-07-16T22:19:29.109Z,
pane=PaneInfo.NO_FIRING}, viewId='null', viewElements=null}, eventTime=0, arrivalTime=1594937969144],
IncomingMessageEnvelope [systemStreamPartition=SystemStreamPartition [default-system, default-system,
0], offset=null, key=null, message=org.apache.samza.system.WatermarkMessage@59b60c67, eventTime=0, arrivalTime=1594937969144],
IncomingMessageEnvelope [systemStreamPartition=SystemStreamPartition [default-system, default-system,
0], offset=rO0ABXNyADhvcmcuYXBhY2hlLmJlYW0ucnVubmVycy5zYW16YS5hZGFwdGVyLlRlc3RDaGVja3BvaW50TWFya08DLHpyVql6AgABSQAKY2hlY2twb2ludHhwAAAAAQ==,
key=null, message=OpMessage{type=ELEMENT, element=TimestampedValueInGlobalWindow{value=second, timestamp=2020-07-16T22:19:29.110Z,
pane=PaneInfo.NO_FIRING}, viewId='null', viewElements=null}, eventTime=0, arrivalTime=1594937969223],
IncomingMessageEnvelope [systemStreamPartition=SystemStreamPartition [default-system, default-system,
0], offset=rO0ABXNyADhvcmcuYXBhY2hlLmJlYW0ucnVubmVycy5zYW16YS5hZGFwdGVyLlRlc3RDaGVja3BvaW50TWFya08DLHpyVql6AgABSQAKY2hlY2twb2ludHhwAAAAAg==,
key=null, message=OpMessage{type=ELEMENT, element=TimestampedValueInGlobalWindow{value=third, timestamp=2020-07-16T22:19:29.111Z,
pane=PaneInfo.NO_FIRING}, viewId='null', viewElements=null}, eventTime=0, arrivalTime=1594937969224],
IncomingMessageEnvelope [systemStreamPartition=SystemStreamPartition [default-system, default-system,
0], offset=null, key=null, message=org.apache.samza.system.WatermarkMessage@59b60c66, eventTime=0, arrivalTime=1594937969275]]>

Stacktrace
java.lang.AssertionError:
expected:<[IncomingMessageEnvelope [systemStreamPartition=SystemStreamPartition [default-system, default-system,
0], offset=rO0ABXNyADhvcmcuYXBhY2hlLmJlYW0ucnVubmVycy5zYW16YS5hZGFwdGVyLlRlc3RDaGVja3BvaW50TWFya08DLHpyVql6AgABSQAKY2hlY2twb2ludHhwAAAAAA==,
key=null, message=OpMessage{type=ELEMENT, element=TimestampedValueInGlobalWindow{value=first, timestamp=2020-07-16T22:19:29.109Z,
pane=PaneInfo.NO_FIRING}, viewId='null', viewElements=null}, eventTime=0, arrivalTime=1594937969136],
IncomingMessageEnvelope [systemStreamPartition=SystemStreamPartition [default-system, default-system,
0], offset=null, key=null, message=org.apache.samza.system.WatermarkMessage@59b60c67, eventTime=0, arrivalTime=1594937969136]]>
but was:<[IncomingMessageEnvelope [systemStreamPartition=SystemStreamPartition [default-system, default-system,
0], offset=rO0ABXNyADhvcmcuYXBhY2hlLmJlYW0ucnVubmVycy5zYW16YS5hZGFwdGVyLlRlc3RDaGVja3BvaW50TWFya08DLHpyVql6AgABSQAKY2hlY2twb2ludHhwAAAAAA==,
key=null, message=OpMessage{type=ELEMENT, element=TimestampedValueInGlobalWindow{value=first, timestamp=2020-07-16T22:19:29.109Z,
pane=PaneInfo.NO_FIRING}, viewId='null', viewElements=null}, eventTime=0, arrivalTime=1594937969144],
IncomingMessageEnvelope [systemStreamPartition=SystemStreamPartition [default-system, default-system,
0], offset=null, key=null, message=org.apache.samza.system.WatermarkMessage@59b60c67, eventTime=0, arrivalTime=1594937969144],
IncomingMessageEnvelope [systemStreamPartition=SystemStreamPartition [default-system, default-system,
0], offset=rO0ABXNyADhvcmcuYXBhY2hlLmJlYW0ucnVubmVycy5zYW16YS5hZGFwdGVyLlRlc3RDaGVja3BvaW50TWFya08DLHpyVql6AgABSQAKY2hlY2twb2ludHhwAAAAAQ==,
key=null, message=OpMessage{type=ELEMENT, element=TimestampedValueInGlobalWindow{value=second, timestamp=2020-07-16T22:19:29.110Z,
pane=PaneInfo.NO_FIRING}, viewId='null', viewElements=null}, eventTime=0, arrivalTime=1594937969223],
IncomingMessageEnvelope [systemStreamPartition=SystemStreamPartition [default-system, default-system,
0], offset=rO0ABXNyADhvcmcuYXBhY2hlLmJlYW0ucnVubmVycy5zYW16YS5hZGFwdGVyLlRlc3RDaGVja3BvaW50TWFya08DLHpyVql6AgABSQAKY2hlY2twb2ludHhwAAAAAg==,
key=null, message=OpMessage{type=ELEMENT, element=TimestampedValueInGlobalWindow{value=third, timestamp=2020-07-16T22:19:29.111Z,
pane=PaneInfo.NO_FIRING}, viewId='null', viewElements=null}, eventTime=0, arrivalTime=1594937969224],
IncomingMessageEnvelope [systemStreamPartition=SystemStreamPartition [default-system, default-system,
0], offset=null, key=null, message=org.apache.samza.system.WatermarkMessage@59b60c66, eventTime=0, arrivalTime=1594937969275]]>
at org.junit.Assert.fail(Assert.java:89) at org.junit.Assert.failNotEquals(Assert.java:835) at org.junit.Assert.assertEquals(Assert.java:120)
at org.junit.Assert.assertEquals(Assert.java:146) at org.apache.beam.runners.samza.adapter.UnboundedSourceSystemTest.testMultipleAdvanceWatermark(UnboundedSourceSystemTest.java:200)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:305) at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:365) at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63) at org.junit.runners.ParentRunner$4.run(ParentRunner.java:330)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:78) at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:328)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:65) at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:292)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:305) at org.junit.runners.ParentRunner.run(ParentRunner.java:412)
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498)
at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35) at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
at com.sun.proxy.$Proxy2.processTestClass(Unknown Source) at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498)
at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35) at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404) at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
at java.lang.Thread.run(Thread.java:748)

Standard Error
Jul 16, 2020 10:19:26 PM org.apache.beam.sdk.coders.SerializableCoder
checkEqualsMethodDefined WARNING: Can't verify serialized elements of type TestCheckpointMark have well
defined equals method. This may produce incorrect results on some PipelineRunner

```

 

Imported from Jira [BEAM-10521](https://issues.apache.org/jira/browse/BEAM-10521). Original Jira may contain additional context.
Reported by: tysonjh.

**Comment by damccorm** [comment]
This has been healthy as long as the test history goes back - https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/
