### ISSUE TITLE
Jenkins job stuck on Jacoco

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20725]
The Gradle task for beam_PreCommit_Java_Commit completed successfully, but then the job got stuck on the jacoco plugin step for 5 hours until I terminated the job manually.

https://ci-beam.apache.org/job/beam_PreCommit_Java_Commit/16098/

14:26:03 [JaCoCo plugin] Source Inclusions: null
14:26:03 [JaCoCo plugin] Source Exclusions: nullERROR: Step ‘Record JaCoCo coverage report’ aborted due to exception: 
18:41:11 java.lang.InterruptedException
18:41:11 	at java.lang.Object.wait(Native Method)
18:41:11 	at hudson.remoting.FastPipedInputStream.read(FastPipedInputStream.java:175)
18:41:11 Caused: java.io.IOException
18:41:11 	at hudson.remoting.FastPipedInputStream.read(FastPipedInputStream.java:177)
18:41:11 	at hudson.util.HeadBufferingStream.read(HeadBufferingStream.java:61)
18:41:11 	at com.jcraft.jzlib.InflaterInputStream.fill(InflaterInputStream.java:175)
18:41:11 	at com.jcraft.jzlib.InflaterInputStream.read(InflaterInputStream.java:106)
18:41:11 	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.read(TarArchiveInputStream.java:639)
18:41:11 	at java.io.InputStream.read(InputStream.java:101)
18:41:11 	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2314)
18:41:11 	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2270)
18:41:11 	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2291)
18:41:11 	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2246)
18:41:11 	at hudson.util.IOUtils.copy(IOUtils.java:43)
18:41:11 	at hudson.FilePath.readFromTar(FilePath.java:2602)
18:41:11 Caused: java.io.IOException: Failed to extract /home/jenkins/jenkins-slave/workspace/beam_PreCommit_Java_Commit/src/examples/java/src/main/java/null
18:41:11 	at hudson.FilePath.readFromTar(FilePath.java:2612)
18:41:11 	at hudson.FilePath.copyRecursiveTo(FilePath.java:2390)
18:41:11 	at hudson.FilePath.copyRecursiveTo(FilePath.java:2354)
18:41:11 	at hudson.FilePath.copyRecursiveTo(FilePath.java:2342)
18:41:11 	at hudson.plugins.jacoco.JacocoReportDir.saveSourcesFrom(JacocoReportDir.java:48)
18:41:11 	at hudson.plugins.jacoco.JacocoPublisher.perform(JacocoPublisher.java:653)
18:41:11 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
18:41:11 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
18:41:11 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
18:41:11 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
18:41:11 	at hudson.model.Build$BuildExecution.post2(Build.java:186)
18:41:11 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
18:41:11 	at hudson.model.Run.execute(Run.java:1905)
18:41:11 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
18:41:11 	at hudson.model.ResourceController.execute(ResourceController.java:97)
18:41:11 	at hudson.model.Executor.run(Executor.java:428)

Imported from Jira [BEAM-11840](https://issues.apache.org/jira/browse/BEAM-11840). Original Jira may contain additional context.
Reported by: ibzib.

**Comment by damccorm** [comment]
This isn't happening consistently and will go away when we move to GHA
