### ISSUE TITLE
PubsubTableProviderIT.testSQLSelectsArrayAttributes[0] failing in SQL PostCommit

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20937]
Failing since https://ci-beam.apache.org/job/beam_PostCommit_SQL/6260/

```

java.lang.AssertionError: Did not receive signal on projects/apache-beam-testing/subscriptions/result-subscription--1731534761628855545
in 60s
	at org.apache.beam.sdk.io.gcp.pubsub.TestPubsubSignal.pollForResultForDuration(TestPubsubSignal.java:341)
	at
org.apache.beam.sdk.io.gcp.pubsub.TestPubsubSignal.waitForSuccess(TestPubsubSignal.java:288)
	at org.apache.beam.sdk.extensions.sql.meta.provider.pubsub.PubsubTableProviderIT.testSQLSelectsArrayAttributes(PubsubTableProviderIT.java:256)

```

Imported from Jira [BEAM-12320](https://issues.apache.org/jira/browse/BEAM-12320). Original Jira may contain additional context.
Reported by: bhulette.

**Comment by kennknowles** [comment]
There were fixes in https://github.com/apache/beam/pull/22612 so I will try to reproduce this.
