### ISSUE TITLE
CrossLanguageKafkaIOTest.test_kafkaio flake

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20980]
Saw this here: https://ci-beam.apache.org/job/beam_PostCommit_Python37/3768

```

Pipeline BeamApp-jenkins-0504183620-7feb3116_2ef5c06b-9d2c-4ab6-b040-72f6937fd8b3 failed in state FAILED:
java.lang.RuntimeException: Error received from SDK harness for instruction 16: org.apache.beam.sdk.util.UserCodeException:
java.io.IOException: KafkaWriter : failed to send 1 records (since last report)
	at org.apache.beam.sdk.util.UserCodeException.wrap(UserCodeException.java:39)
	at
org.apache.beam.sdk.io.kafka.KafkaWriter$DoFnInvoker.invokeProcessElement(Unknown Source)
	at org.apache.beam.fn.harness.FnApiDoFnRunner.processElementForParDo(FnApiDoFnRunner.java:750)
	at
org.apache.beam.fn.harness.data.PCollectionConsumerRegistry$MetricTrackingFnDataReceiver.accept(PCollectionConsumerRegistry.java:262)
	at
org.apache.beam.fn.harness.data.PCollectionConsumerRegistry$MetricTrackingFnDataReceiver.accept(PCollectionConsumerRegistry.java:214)
	at
org.apache.beam.fn.harness.FnApiDoFnRunner.outputTo(FnApiDoFnRunner.java:1680)
	at org.apache.beam.fn.harness.FnApiDoFnRunner.access$2500(FnApiDoFnRunner.java:139)
	at
org.apache.beam.fn.harness.FnApiDoFnRunner$NonWindowObservingProcessBundleContext.outputWithTimestamp(FnApiDoFnRunner.java:2194)
	at
org.apache.beam.fn.harness.FnApiDoFnRunner$ProcessBundleContextBase.output(FnApiDoFnRunner.java:2363)
	at
org.apache.beam.sdk.transforms.DoFnOutputReceivers$WindowedContextOutputReceiver.output(DoFnOutputReceivers.java:78)
	at
org.apache.beam.sdk.transforms.MapElements$1.processElement(MapElements.java:142)
	at org.apache.beam.sdk.transforms.MapElements$1$DoFnInvoker.invokeProcessElement(Unknown
Source)
	at org.apache.beam.fn.harness.FnApiDoFnRunner.processElementForParDo(FnApiDoFnRunner.java:750)
	at
org.apache.beam.fn.harness.data.PCollectionConsumerRegistry$MetricTrackingFnDataReceiver.accept(PCollectionConsumerRegistry.java:262)
	at
org.apache.beam.fn.harness.data.PCollectionConsumerRegistry$MetricTrackingFnDataReceiver.accept(PCollectionConsumerRegistry.java:214)
	at
org.apache.beam.fn.harness.BeamFnDataReadRunner.forwardElementToConsumer(BeamFnDataReadRunner.java:220)
	at
org.apache.beam.sdk.fn.data.DecodingFnDataReceiver.accept(DecodingFnDataReceiver.java:43)
	at org.apache.beam.sdk.fn.data.DecodingFnDataReceiver.accept(DecodingFnDataReceiver.java:25)
	at
org.apache.beam.fn.harness.data.QueueingBeamFnDataClient$ConsumerAndData.accept(QueueingBeamFnDataClient.java:315)
	at
org.apache.beam.fn.harness.data.QueueingBeamFnDataClient.drainAndBlock(QueueingBeamFnDataClient.java:218)
	at
org.apache.beam.fn.harness.control.ProcessBundleHandler.processBundle(ProcessBundleHandler.java:326)
	at
org.apache.beam.fn.harness.control.BeamFnControlClient.delegateOnInstructionRequestType(BeamFnControlClient.java:140)
	at
org.apache.beam.fn.harness.control.BeamFnControlClient$InboundObserver.lambda$onNext$0(BeamFnControlClient.java:110)
	at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at
java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: KafkaWriter : failed to send
1 records (since last report)
	at org.apache.beam.sdk.io.kafka.KafkaWriter.checkForFailures(KafkaWriter.java:133)
	at
org.apache.beam.sdk.io.kafka.KafkaWriter.processElement(KafkaWriter.java:58)
Caused by: org.apache.kafka.common.errors.TimeoutException:
Topic xlang_kafkaio_test_0006c41b-f5ae-45cf-a316-a4895dae245f not present in metadata after 60000 ms.

```

Imported from Jira [BEAM-12308](https://issues.apache.org/jira/browse/BEAM-12308). Original Jira may contain additional context.
Reported by: bhulette.

**Comment by damccorm** [comment]
Unable to assign user @johnjcasey. If able, self-assign, otherwise tag @damccorm so that he can assign you. Because of GitHub's spam prevention system, your activity is required to enable assignment in this repo.

**Comment by johnjcasey** [comment]
@damccorm How can I assign myself to this and then close it? I'm logged in, but I'm not seeing those options

**Comment by damccorm** [comment]
One of the unfortunate downsides of moving to issues is that non-committers can't self-assign/triage issues that they didn't create by default. I think that's a workflow we'll need to support going forward though, I'll look into it. For the moment, I'd recommend commenting/declaring intent to work on any issues.

I have access through https://github.com/apache/beam/blob/4dce7b8857f37608321253073745fe7611a48af9/.asf.yaml#L39 which gives triage permissions, unfortunately that's limited to 20 people though

**Comment by johnjcasey** [comment]
Hmm, thats a bit unfortunate. Ty though

**Comment by johnjcasey** [comment]
Next question. How do I close this issue?

**Comment by damccorm** [comment]
Hm, that one is surprising to me. I was under the impression that once assigned you could close.

Once https://github.com/apache/beam/pull/21719 is in, you should be able to do this with chat-op commands

**Comment by johnjcasey** [comment]
.close-issue
