### ISSUE TITLE
WriteToBigQuery in BundleBasedDirectRunner fails when method is FILE_LOADS

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21061]
`WriteToBigQuery` fails when using the `FILE_LOADS` method in the `BundleBasedDirectRunner`.

The issue appears to be in `wait_for_bq_job`, where the function expects `job_reference` to be an actual JobReference instance and not a string. However, the `WaitForBQJobs` DoFn appears to be [passing a string]([https://github.com/apache/beam/blob/5a029fd97d663e19a9bcd6bff61648bccbd7f95b/sdks/python/apache_beam/io/gcp/bigquery_file_loads.py#L730](https://github.com/apache/beam/blob/5a029fd97d663e19a9bcd6bff61648bccbd7f95b/sdks/python/apache_beam/io/gcp/bigquery_file_loads.py#L730)) as the argument. I believe this is during the copy step, and I'm not calling this code directly (so unfortunately I can't just pass a TableReference instance myself).

Here is a traceback:

 
```

request_worker_1      | ERROR:root:Traceback (most recent call last):
request_worker_1      |   File
"/app/main.py", line 209, in process_message
request_worker_1      |     construct_and_run_pipeline(request)
request_worker_1
     |   File "/app/main.py", line 190, in construct_and_run_pipeline
request_worker_1      |     return
result.wait_until_finish()
request_worker_1      |   File "/usr/local/lib/python3.8/site-packages/apache_beam/runners/direct/direct_runner.py",
line 588, in wait_until_finish
request_worker_1      |     self._executor.await_completion()
request_worker_1
     |   File "/usr/local/lib/python3.8/site-packages/apache_beam/runners/direct/executor.py", line
433, in await_completion
request_worker_1      |     self._executor.await_completion()
request_worker_1
     |   File "/usr/local/lib/python3.8/site-packages/apache_beam/runners/direct/executor.py", line
482, in await_completion
request_worker_1      |     raise t(v).with_traceback(tb)
request_worker_1
     |   File "/usr/local/lib/python3.8/site-packages/apache_beam/runners/direct/executor.py", line
371, in call
request_worker_1      |     self.attempt_call(
request_worker_1      |   File "/usr/local/lib/python3.8/site-packages/apache_beam/runners/direct/executor.py",
line 414, in attempt_call
request_worker_1      |     evaluator.process_element(value)
request_worker_1
     |   File "/usr/local/lib/python3.8/site-packages/apache_beam/runners/direct/transform_evaluator.py",
line 880, in process_element
request_worker_1      |     self.runner.process(element)
request_worker_1
     |   File "/usr/local/lib/python3.8/site-packages/apache_beam/runners/common.py", line 1225, in
process
request_worker_1      |     self._reraise_augmented(exn)
request_worker_1      |   File "/usr/local/lib/python3.8/site-packages/apache_beam/runners/common.py",
line 1306, in _reraise_augmented
request_worker_1      |     raise new_exn.with_traceback(tb)
request_worker_1
     |   File "/usr/local/lib/python3.8/site-packages/apache_beam/runners/common.py", line 1223, in
process
request_worker_1      |     return self.do_fn_invoker.invoke_process(windowed_value)
request_worker_1
     |   File "/usr/local/lib/python3.8/site-packages/apache_beam/runners/common.py", line 752, in invoke_process
request_worker_1
     |     self._invoke_process_per_window(
request_worker_1      |   File "/usr/local/lib/python3.8/site-packages/apache_beam/runners/common.py",
line 877, in _invoke_process_per_window
request_worker_1      |     self.process_method(*args_for_process),
request_worker_1
     |   File "/usr/local/lib/python3.8/site-packages/apache_beam/io/gcp/bigquery_file_loads.py", line
730, in process
request_worker_1      |     self.bq_wrapper.wait_for_bq_job(ref, sleep_duration_sec=10,
max_retries=0)
request_worker_1      |   File "/usr/local/lib/python3.8/site-packages/apache_beam/io/gcp/bigquery_tools.py",
line 562, in wait_for_bq_job
request_worker_1      |     job_reference.projectId, job_reference.jobId,
job_reference.location)
request_worker_1      | AttributeError: 'str' object has no attribute 'projectId'
[while running 'write tweets to bigquery/Write/BigQueryBatchFileLoads/WaitForTempTableLoadJobs']

```

 

Here is the `WriteToBigQuery` step that is failing (note that the callable passed for `table` returns a TableReference instance):
```

WriteToBigQuery(
     table=lambda row: bigquery_tools.parse_table_reference(row["table_name"]),

    create_disposition=beam.io.BigQueryDisposition.CREATE_NEVER,
     write_disposition=beam.io.BigQueryDisposition.WRITE_APPEND,

    ignore_insert_ids=True,
     method="FILE_LOADS", # using STREAMING_INSERTS 'fixes' the issue

    batch_size=int(os.getenv("BIGQUERY_BATCH_SIZE", "10")),
     schema=schema,
)

```

 

Note that this issue does not occur when using the standard `DirectRunner`, nor does it occur when using the `STREAMING_INSERTS` method.

Thanks! (And apologies if I left out any important information. This is the first issue I've opened here.)

Imported from Jira [BEAM-12659](https://issues.apache.org/jira/browse/BEAM-12659). Original Jira may contain additional context.
Reported by: milesmcc.

**Comment by blazingbhavneek** [comment]
Hey there! 👋 I'm new to this repository and eager to contribute! 🌟 Could you kindly suggest some entry point or files to look into?

**Comment by damccorm** [comment]
Hey, saw you added this comment several places. I'd recommend focusing on a single issue at first (I answered the underlying question here - https://github.com/apache/beam/issues/20298#issuecomment-1547888993)

**Comment by Wellbek** [comment]
Hey! As my intro to contributing to Apache Beam, I took a look at this older issue to see whether it still relevant.

From the traceback, my understanding is that the failure happened when `WriteToBigQuery` was used with:

* `method="FILE_LOADS"`
* a dynamic `table` callable
* and the `BundleBasedDirectRunner`

which then failed with:

```python
AttributeError: 'str' object has no attribute 'projectId'
```

From the issue description, problem stems from `wait_for_bq_job` expecting a proper `JobReference` object, while a plain string was being passed somewhere in the `WaitForBQJobs` path.

To reproduce this, I first created a small GCP setup:
* created a new GCP project
* created a GCS bucket
* created a BigQuery dataset

I then wrote a minimal reproducer (analogous to your step outlined) using:

* `BundleBasedDirectRunner`
* dynamic destinations
* `method="FILE_LOADS"`

The reproducer writes rows into multiple dynamic BigQuery tables to ensure the copy/load path is triggered.

I tested this in a local setup with `python:3.14.3` using a recent Beam SDK cloned at May 15 2026 (Beam 2.73.0 release). The pipeline completed successfully and the rows were written correctly to BQ. I could not reproduce the original `AttributeError`.

Just to make sure, I tried some more test cases, specifically

* larger numbers of dynamic tables (50)
* more rows
* smaller `batch_size`
* larger payloads (1KB text)
* mixed data types (`None`, floats, booleans, unicode text, long strings)

All of these also completed successfully without any error.

During testing, I also added temporary type checks before calls to `wait_for_bq_job` through the cloned python sdk to verify what was being passed in. In all cases, the value was a proper `JobReference` object and never a plain string.

One thing that also stood out while looking through the code history is that the mentioned `WaitForBQJobs` seems to have been removed in Beam 2.42.0 -> 2.43.0 (see https://github.com/apache/beam/compare/v2.42.0...v2.43.0). 
**I therefore suspect the issue may already have been fixed as part of later refactors.**

At this point I'm unable to reproduce the bug, so I wanted to check whether this issue can likely be closed, or whether there is still a known failing scenario I may have missed.

Since this is also my first time digging into the Beam codebase, I'd really appreciate any guidance on, 1) whether there are more scenarios I should verify against (e.g., using older beam versions), 2) whether there's a more specific reproducer I should try

Happy to run more tests or investigate further if helpful. Cheers

**Comment by vetapalem-pravallika** [comment]
Hi! I'd like to investigate this issue.

I'll try reproducing the behavior on the current Beam version and trace whether the original failure path still exists. If the issue has already been resolved by later refactors, I'll summarize the findings and propose next steps.

.take-issue

**Comment by vetapalem-pravallika** [comment]
I investigated this issue in the current Apache Beam codebase and also attempted to reproduce it using a recent release.

The original failure reports an AttributeError caused by a string being passed instead of a JobReference in the wait_for_bq_job path during FILE_LOADS with BundleBasedDirectRunner.

After analysis, I found that the original implementation (WaitForBQJobs / WaitForTempTableLoadJobs) referenced in the 2022 stack trace has been removed in commit ac37784821eaedd97c2e6e39441c22ebc6d97cd3 as part of PR #23012. The current implementation performs job waiting directly within finish_bundle() in the relevant BigQuery file loads steps.

In the current bigquery_file_loads.py, all calls to wait_for_bq_job() receive job references returned from _insert_load_job() and _insert_copy_job(). I did not find any remaining code path where a string job ID is passed instead of a JobReference object.

Additionally, I attempted to reproduce the issue using Apache Beam 2.73.0 with BundleBasedDirectRunner, FILE_LOADS, and dynamic destinations. The pipeline executed successfully, and no AttributeError or job reference type mismatch was observed.

Based on both code inspection and runtime verification, I could not reproduce the original failure in currently supported Beam versions, and the original root cause appears to have been addressed by subsequent refactoring.

Unless a reproduction is available on a supported release, this issue does not appear to still be present.
