### ISSUE TITLE
Flaky: apache_beam.runners.portability.fn_api_runner.fn_runner_test.FnApiRunnerTestWithGrpcAndMultiWorkers

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21104]
The `apache_beam.runners.portability.fn_api_runner.fn_runner_test.FnApiRunnerTestWithGrpcAndMultiWorkers` tests are flaky and causing precommit failures that seem similar.

`test_pardo_windowed_side_inputs` : [https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/4417/console](https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/4417/console)
```

23:32:35 Exception in thread read_grpc_client_inputs:
23:32:35 Traceback (most recent call last):
23:32:35
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
23:32:35     self.run()
23:32:35
  File "/usr/lib/python3.8/threading.py", line 870, in run
23:32:35     self._target(*self._args, **self._kwargs)
23:32:35
  File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Cron/src/sdks/python/test-suites/tox/py38/build/srcs/sdks/python/apache_beam/runners/worker/data_plane.py",
line 587, in <lambda>
23:32:35     target=lambda: self._read_inputs(elements_iterator),
23:32:35 
 File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Cron/src/sdks/python/test-suites/tox/py38/build/srcs/sdks/python/apache_beam/runners/worker/data_plane.py",
line 570, in _read_inputs
23:32:35     for elements in elements_iterator:
23:32:35   File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Cron/src/sdks/python/test-suites/tox/py38/build/srcs/sdks/python/target/.tox-py38-cython/py38-cython/lib/python3.8/site-packages/grpc/_channel.py",
line 426, in __next__
23:32:35     return self._next()
23:32:35   File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Cron/src/sdks/python/test-suites/tox/py38/build/srcs/sdks/python/target/.tox-py38-cython/py38-cython/lib/python3.8/site-packages/grpc/_channel.py",
line 826, in _next
23:32:35     raise self
23:32:35 grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous
of RPC that terminated with:
23:32:35 	status = StatusCode.UNAVAILABLE
23:32:35 	details = "Broken
pipe"
23:32:35 	debug_error_string = "{"created":"@1626071403.252458842","description":"Error received
from peer ipv4:127.0.0.1:37459","file":"src/core/lib/surface/call.cc","file_line":1066,"grpc_message":"Broken
pipe","grpc_status":14}"
23:32:35 >
23:32:35 Traceback (most recent call last):
23:32:35   File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Cron/src/sdks/python/test-suites/tox/py38/build/srcs/sdks/python/apache_beam/runners/worker/data_plane.py",
line 459, in input_elements
23:32:35     element = received.get(timeout=1)
23:32:35   File "/usr/lib/python3.8/queue.py",
line 178, in get
23:32:35     raise Empty
23:32:35 _queue.Empty

```

 

`test_pack_combiners` :  [https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/4415/consoleFull](https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/4415/consoleFull)
```

11:41:14 Exception ignored in: <object repr() failed>
11:41:14 Traceback (most recent call last):
11:41:14
  File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Cron/src/sdks/python/test-suites/tox/py36/build/srcs/sdks/python/target/.tox-py36-cython/py36-cython/lib/python3.6/site-packages/grpc/_channel.py",
line 444, in __del__
11:41:14     with self._state.condition:
11:41:14 AttributeError: '_MultiThreadedRendezvous'
object has no attribute '_state'
11:41:14 Traceback (most recent call last):
11:41:14   File "apache_beam/runners/common.py",
line 1223, in apache_beam.runners.common.DoFnRunner.process
11:41:14     return self.do_fn_invoker.invoke_process(windowed_value)
11:41:14
  File "apache_beam/runners/common.py", line 752, in apache_beam.runners.common.PerWindowInvoker.invoke_process
11:41:14
    self._invoke_process_per_window(
11:41:14   File "apache_beam/runners/common.py", line 816, in
apache_beam.runners.common.PerWindowInvoker._invoke_process_per_window
11:41:14     [si[global_window]
for si in self.side_inputs]))
11:41:14   File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Cron/src/sdks/python/test-suites/tox/py36/build/srcs/sdks/python/apache_beam/runners/worker/bundle_processor.py",
line 427, in __getitem__
11:41:14     self._cache[target_window] = self._side_input_data.view_fn(raw_view)
11:41:14
  File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Cron/src/sdks/python/test-suites/tox/py36/build/srcs/sdks/python/apache_beam/runners/worker/bundle_processor.py",
line 353, in __iter__
11:41:14     self._state_handler.blocking_get(self._state_key, self._coder_impl))
11:41:14
  File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Cron/src/sdks/python/test-suites/tox/py36/build/srcs/sdks/python/apache_beam/runners/worker/sdk_worker.py",
line 1184, in blocking_get
11:41:14     self._partially_cached_iterable(state_key, coder))
11:41:14
  File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Cron/src/sdks/python/test-suites/tox/py36/build/srcs/sdks/python/apache_beam/runners/worker/sdk_worker.py",
line 1290, in _partially_cached_iterable
11:41:14     data, continuation_token = self._underlying.get_raw(state_key,
None)
11:41:14   File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Cron/src/sdks/python/test-suites/tox/py36/build/srcs/sdks/python/apache_beam/runners/worker/sdk_worker.py",
line 1057, in get_raw
11:41:14     continuation_token=continuation_token)))
11:41:14   File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Cron/src/sdks/python/test-suites/tox/py36/build/srcs/sdks/python/apache_beam/runners/worker/sdk_worker.py",
line 1095, in _blocking_request
11:41:14     raise t(v).with_traceback(tb)
11:41:14 TypeError: __init__()
missing 3 required positional arguments: 'call', 'response_deserializer', and 'deadline'

```

Imported from Jira [BEAM-12603](https://issues.apache.org/jira/browse/BEAM-12603). Original Jira may contain additional context.
Reported by: tysonjh.

**Comment by tvalentyn** [comment]
There have been several fixes (see Jira). last one: https://github.com/apache/beam/pull/17537/files

However this test is still flaky. Seeing a different error this time:

```
Error Message
RuntimeError: Traceback (most recent call last):
  File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Commit/src/sdks/python/test-suites/tox/py38/build/srcs/sdks/python/apache_beam/runners/worker/sdk_worker.py", line 287, in _execute
    response = task()
  File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Commit/src/sdks/python/test-suites/tox/py38/build/srcs/sdks/python/apache_beam/runners/worker/sdk_worker.py", line 360, in <lambda>
    lambda: self.create_worker().do_instruction(request), request)
  File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Commit/src/sdks/python/test-suites/tox/py38/build/srcs/sdks/python/apache_beam/runners/worker/sdk_worker.py", line 596, in do_instruction
    return getattr(self, request_type)(
  File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Commit/src/sdks/python/test-suites/tox/py38/build/srcs/sdks/python/apache_beam/runners/worker/sdk_worker.py", line 634, in process_bundle
    bundle_processor.process_bundle(instruction_id))
  File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Commit/src/sdks/python/test-suites/tox/py38/build/srcs/sdks/python/apache_beam/runners/worker/bundle_processor.py", line 1003, in process_bundle
    input_op_by_transform_id[element.transform_id].process_encoded(
  File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Commit/src/sdks/python/test-suites/tox/py38/build/srcs/sdks/python/apache_beam/runners/worker/bundle_processor.py", line 225, in process_encoded
    decoded_value = self.windowed_coder_impl.decode_from_stream(
  File "apache_beam/coders/coder_impl.py", line 1446, in apache_beam.coders.coder_impl.WindowedValueCoderImpl.decode_from_stream
    def decode_from_stream(self, in_stream, nested):
  File "apache_beam/coders/coder_impl.py", line 1464, in apache_beam.coders.coder_impl.WindowedValueCoderImpl.decode_from_stream
    pane_info = self._pane_info_coder.decode_from_stream(in_stream, True)
  File "apache_beam/coders/coder_impl.py", line 1383, in apache_beam.coders.coder_impl.PaneInfoCoderImpl.decode_from_stream
    raise NotImplementedError('Invalid PaneInfoEncoding: %s' % encoding_type)
NotImplementedError: Invalid PaneInfoEncoding: 6
```

**Comment by pabloem** [comment]
I'm having lots of trouble reproducing this failure...

**Comment by pabloem** [comment]
but I'm trying to : )

**Comment by tvalentyn** [comment]
may be one of those tests that fail on jenkins only (when run together w/ a bunch of tests)... i saw it today in a linked issue

**Comment by pabloem** [comment]
i got it to reproduce a couple of times on my machine in non-cython. I'm adding logging to see what happens

**Comment by tvalentyn** [comment]
nice, did you run a single test?

**Comment by pabloem** [comment]
I got it to repro by runnig the full class of tests (FnApiRunnerTestWithGrpcAndMultiWorkers)

**Comment by pabloem** [comment]
fwiw this is the error stack that I'm able to reproduce:

```
======================================================================
ERROR: test_pardo_large_input (apache_beam.runners.portability.fn_api_runner.fn_runner_test.FnApiRunnerTestWithGrpcAndMultiWorkers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pabloem/codes/pybeam/sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner_test.py", line 379, in test_pardo_large_input
    assert_that(res, equal_to([(i * 2) + 3 for i in range(5000)]))
  File "/home/pabloem/codes/pybeam/sdks/python/apache_beam/pipeline.py", line 597, in __exit__
    self.result = self.run()
  File "/home/pabloem/codes/pybeam/sdks/python/apache_beam/pipeline.py", line 574, in run
    return self.runner.run_pipeline(self, self._options)
  File "/home/pabloem/codes/pybeam/sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 199, in run_pipeline
    self._latest_run_result = self.run_via_runner_api(
  File "/home/pabloem/codes/pybeam/sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 212, in run_via_runner_api
    return self.run_stages(stage_context, stages)
  File "/home/pabloem/codes/pybeam/sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 442, in run_stages
    bundle_results = self._execute_bundle(
  File "/home/pabloem/codes/pybeam/sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 770, in _execute_bundle
    self._run_bundle(
  File "/home/pabloem/codes/pybeam/sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 999, in _run_bundle
    result, splits = bundle_manager.process_bundle(
  File "/home/pabloem/codes/pybeam/sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 1415, in process_bundle
    for result, split_result in executor.map(execute, zip(part_inputs,  # pylint: disable=bad-option-value
  File "/home/pabloem/.pyenv/versions/3.8.9/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/home/pabloem/.pyenv/versions/3.8.9/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/home/pabloem/.pyenv/versions/3.8.9/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/pabloem/codes/pybeam/sdks/python/apache_beam/utils/thread_pool_executor.py", line 37, in run
    self._future.set_result(self._fn(*self._fn_args, **self._fn_kwargs))
  File "/home/pabloem/codes/pybeam/sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 1407, in execute
    return bundle_manager.process_bundle(
  File "/home/pabloem/codes/pybeam/sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 1348, in process_bundle
    raise RuntimeError(result.error)
RuntimeError: Traceback (most recent call last):
  File "/home/pabloem/codes/pybeam/sdks/python/apache_beam/runners/worker/sdk_worker.py", line 287, in _execute
    response = task()
  File "/home/pabloem/codes/pybeam/sdks/python/apache_beam/runners/worker/sdk_worker.py", line 360, in <lambda>
    lambda: self.create_worker().do_instruction(request), request)
  File "/home/pabloem/codes/pybeam/sdks/python/apache_beam/runners/worker/sdk_worker.py", line 596, in do_instruction
    return getattr(self, request_type)(
  File "/home/pabloem/codes/pybeam/sdks/python/apache_beam/runners/worker/sdk_worker.py", line 634, in process_bundle
    bundle_processor.process_bundle(instruction_id))
  File "/home/pabloem/codes/pybeam/sdks/python/apache_beam/runners/worker/bundle_processor.py", line 1003, in process_bundle
    input_op_by_transform_id[element.transform_id].process_encoded(
  File "/home/pabloem/codes/pybeam/sdks/python/apache_beam/runners/worker/bundle_processor.py", line 225, in process_encoded
    decoded_value = self.windowed_coder_impl.decode_from_stream(
  File "/home/pabloem/codes/pybeam/sdks/python/apache_beam/coders/coder_impl.py", line 1465, in decode_from_stream
    value = self._value_coder.decode_from_stream(in_stream, nested)
  File "/home/pabloem/codes/pybeam/sdks/python/apache_beam/coders/coder_impl.py", line 1008, in decode_from_stream
    return self._construct_from_components([
  File "/home/pabloem/codes/pybeam/sdks/python/apache_beam/coders/coder_impl.py", line 1009, in <listcomp>
    c.decode_from_stream(
  File "/home/pabloem/codes/pybeam/sdks/python/apache_beam/coders/coder_impl.py", line 1557, in decode_from_stream
    return self._value_coder.decode(in_stream.read(value_length))
  File "/home/pabloem/codes/pybeam/sdks/python/apache_beam/coders/coder_impl.py", line 240, in decode
    return self.decode_from_stream(create_InputStream(encoded), False)
  File "/home/pabloem/codes/pybeam/sdks/python/apache_beam/coders/coder_impl.py", line 535, in decode_from_stream
    t = stream.read_byte()
  File "/home/pabloem/codes/pybeam/sdks/python/apache_beam/coders/slow_stream.py", line 145, in read_byte
    return self.data[self.pos - 1]
IndexError: index out of range

```

**Comment by pabloem** [comment]
From latest repro:
```
Data position is  620095
Step with error is  NameContext({'step_name': 'assert_that/Group/CoGroupByKeyImpl/Flatten/Read', 'transform_id': 'assert_that/Group/CoGroupByKeyImpl/Flatten/Read'})
```

Doing more research...

**Comment by pabloem** [comment]
Errors I'm seeing:

```
OIOIOI DATA LEN IS  0 POS IS  1
Error in  NameContext({'step_name': 'assert_that/Group/CoGroupByKeyImpl/Flatten/Read', 'transform_id': 'assert_that/Group/CoGroupByKeyImpl/Flatten/Read'})
```

And afterwards

```
OIOIOI DATA LEN IS  682783 POS IS  682784
Error in  NameContext({'step_name': 'assert_that/Group/CoGroupByKeyImpl/Flatten/Read', 'transform_id': 'assert_that/Group/CoGroupByKeyImpl/Flatten/Read'})
```

**Comment by pabloem** [comment]
I've done some more research. Oddly, the encoding size for the first set of elements that we output varies even on instances of successful tests.

I wondered if this could be because we encode every element with the current timestamp, which varies depending on test execution time - so I hardcoded a specific timestamp for all instances of the test. Encoding size still varied:

```
INFO:root:pabloem Adding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464646 - inst: bundle_1
INFO:root:pabloem Yielding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464646 - inst bundle_1
INFO:root:pabloem Adding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464675 - inst: bundle_4
INFO:root:pabloem Yielding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464675 - inst bundle_4
INFO:root:pabloem Adding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464679 - inst: bundle_1
INFO:root:pabloem Yielding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464679 - inst bundle_1
INFO:root:pabloem Adding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464693 - inst: bundle_4
INFO:root:pabloem Yielding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464693 - inst bundle_4
INFO:root:pabloem Adding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464658 - inst: bundle_3
INFO:root:pabloem Yielding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464658 - inst bundle_3
INFO:root:pabloem Adding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464725 - inst: bundle_4
INFO:root:pabloem Yielding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464725 - inst bundle_4
INFO:root:pabloem Adding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464684 - inst: bundle_1
INFO:root:pabloem Yielding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464684 - inst bundle_1
INFO:root:pabloem Adding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464685 - inst: bundle_3
INFO:root:pabloem Yielding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464685 - inst bundle_3
INFO:root:pabloem Adding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464719 - inst: bundle_3
INFO:root:pabloem Yielding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464719 - inst bundle_3
INFO:root:pabloem Adding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464702 - inst: bundle_1
INFO:root:pabloem Yielding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464702 - inst bundle_1
INFO:root:pabloem Adding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464694 - inst: bundle_1
INFO:root:pabloem Yielding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464694 - inst bundle_1
INFO:root:pabloem Adding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464702 - inst: bundle_4
INFO:root:pabloem Yielding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464702 - inst bundle_4
INFO:root:pabloem Adding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464673 - inst: bundle_1
INFO:root:pabloem Yielding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464673 - inst bundle_1
INFO:root:pabloem Adding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464716 - inst: bundle_1
INFO:root:pabloem Yielding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464716 - inst bundle_1
INFO:root:pabloem Adding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464684 - inst: bundle_4
INFO:root:pabloem Yielding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464684 - inst bundle_4
INFO:root:pabloem Adding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464682 - inst: bundle_1
INFO:root:pabloem Yielding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464682 - inst bundle_1
INFO:root:pabloem Adding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464702 - inst: bundle_1
INFO:root:pabloem Yielding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464702 - inst bundle_1
INFO:root:pabloem Adding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464665 - inst: bundle_3
INFO:root:pabloem Yielding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464665 - inst bundle_3
INFO:root:pabloem Adding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464703 - inst: bundle_1
INFO:root:pabloem Yielding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464703 - inst bundle_1
INFO:root:pabloem Adding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464720 - inst: bundle_3
INFO:root:pabloem Yielding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464720 - inst bundle_3
INFO:root:pabloem Adding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464669 - inst: bundle_4
INFO:root:pabloem Yielding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464669 - inst bundle_4
INFO:root:pabloem Adding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464675 - inst: bundle_1
INFO:root:pabloem Yielding Create/MaybeReshuffle/Reshuffle/ReshufflePerKey/GroupByKey/Write element. Len: 1464675 - inst bundle_1
```

**Comment by kennknowles** [comment]
@pabloem are you still actively working on this?

**Comment by pabloem** [comment]
Thanks Kenn. I am not working actively on this now.
If I find some time I'll get back to it - but for now anyone else should
feel free to pick it up.

**Comment by kennknowles** [comment]
I'll unassign you then
