### ISSUE TITLE
apache_beam.runners.portability.fn_api_runner.translations_test.TranslationsTest.test_run_packable_combine_globally 'apache_beam.coders.coder_impl._AbstractIterable' object is not reversible

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21265]
Suspected cause: https://github.com/apache/beam/pull/15662

Example failure:
https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/8524/testReport/junit/apache_beam.runners.portability.fn_api_runner.translations_test/TranslationsTest/test_run_packable_combine_globally/

```

E         apache_beam.runners.dataflow.dataflow_runner.DataflowRuntimeException: Dataflow pipeline
failed. State: FAILED, Error:
E         Traceback (most recent call last):
E           File "apache_beam/runners/common.py",
line 1198, in apache_beam.runners.common.DoFnRunner.process
E           File "apache_beam/runners/common.py",
line 536, in apache_beam.runners.common.SimpleInvoker.invoke_process
E           File "apache_beam/runners/common.py",
line 1334, in apache_beam.runners.common._OutputProcessor.process_outputs
E           File "/usr/local/lib/python3.6/site-packages/apache_beam/transforms/combiners.py",
line 383, in process
E             for element in reversed(bundle):
E         TypeError: 'apache_beam.coders.coder_impl._AbstractIterable'
object is not reversible
E         
E         During handling of the above exception, another exception
occurred:
E         
E         Traceback (most recent call last):
E           File "/usr/local/lib/python3.6/site-packages/dataflow_worker/batchworker.py",
line 651, in do_work
E             work_executor.execute()
E           File "/usr/local/lib/python3.6/site-packages/dataflow_worker/executor.py",
line 213, in execute
E             op.start()
E           File "dataflow_worker/shuffle_operations.py",
line 63, in dataflow_worker.shuffle_operations.GroupedShuffleReadOperation.start
E           File "dataflow_worker/shuffle_operations.py",
line 64, in dataflow_worker.shuffle_operations.GroupedShuffleReadOperation.start
E           File "dataflow_worker/shuffle_operations.py",
line 79, in dataflow_worker.shuffle_operations.GroupedShuffleReadOperation.start
E           File "dataflow_worker/shuffle_operations.py",
line 80, in dataflow_worker.shuffle_operations.GroupedShuffleReadOperation.start
E           File "dataflow_worker/shuffle_operations.py",
line 84, in dataflow_worker.shuffle_operations.GroupedShuffleReadOperation.start
E           File "apache_beam/runners/worker/operations.py",
line 349, in apache_beam.runners.worker.operations.Operation.output
E           File "apache_beam/runners/worker/operations.py",
line 216, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
E           File "dataflow_worker/shuffle_operations.py",
line 261, in dataflow_worker.shuffle_operations.BatchGroupAlsoByWindowsOperation.process
E        
  File "dataflow_worker/shuffle_operations.py", line 268, in dataflow_worker.shuffle_operations.BatchGroupAlsoByWindowsOperation.process
E
          File "apache_beam/runners/worker/operations.py", line 349, in apache_beam.runners.worker.operations.Operation.output
E
          File "apache_beam/runners/worker/operations.py", line 216, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
E
          File "apache_beam/runners/worker/operations.py", line 708, in apache_beam.runners.worker.operations.DoOperation.process
E
          File "apache_beam/runners/worker/operations.py", line 709, in apache_beam.runners.worker.operations.DoOperation.process
E
          File "apache_beam/runners/common.py", line 1200, in apache_beam.runners.common.DoFnRunner.process
E
          File "apache_beam/runners/common.py", line 1281, in apache_beam.runners.common.DoFnRunner._reraise_augmented
E
          File "apache_beam/runners/common.py", line 1198, in apache_beam.runners.common.DoFnRunner.process
E
          File "apache_beam/runners/common.py", line 536, in apache_beam.runners.common.SimpleInvoker.invoke_process
E
          File "apache_beam/runners/common.py", line 1334, in apache_beam.runners.common._OutputProcessor.process_outputs
E
          File "/usr/local/lib/python3.6/site-packages/apache_beam/transforms/combiners.py", line 383,
in process
E             for element in reversed(bundle):
E         TypeError: 'apache_beam.coders.coder_impl._AbstractIterable'
object is not reversible [while running 'multiple-combines/largest-globally/Top(2)/ParDo(_MergeTopPerBundle)']

apache_beam/runners/dataflow/dataflow_runner.py:1643:
DataflowRuntimeException

```

Imported from Jira [BEAM-13087](https://issues.apache.org/jira/browse/BEAM-13087). Original Jira may contain additional context.
Reported by: lcwik.

**Comment by kennknowles** [comment]
Addressed by #15757 before the Jira to GitHub Issues migration.
