### ISSUE TITLE
org.apache.beam.sdk.transforms.ParDoLifecycleTest.testTeardownCalledAfterExceptionInProcessElementStateful is flaky in Java ValidatesRunner Flink suite.

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21266]
Sample run: https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/9666/testReport/junit/org.apache.beam.sdk.transforms/ParDoLifecycleTest/testTeardownCalledAfterExceptionInProcessElementStateful/

Saw at least 2 other instances this week.
  
```

Error Message
java.lang.AssertionError: Expected to have a processing method throw an exception
Stacktrace
java.lang.AssertionError:
Expected to have a processing method throw an exception
	at org.junit.Assert.fail(Assert.java:89)
	at
org.apache.beam.sdk.transforms.ParDoLifecycleTest$ExceptionThrowingFn.after(ParDoLifecycleTest.java:439)
Standard
Error
Nov 23, 2021 12:07:43 PM org.apache.beam.runners.flink.FlinkRunner run
INFO: Executing pipeline
using FlinkRunner.
Nov 23, 2021 12:07:43 PM org.apache.beam.runners.flink.FlinkRunner run
WARNING:
For maximum performance you should set the 'fasterCopy' option. See more at https://issues.apache.org/jira/browse/BEAM-11146
Nov
23, 2021 12:07:43 PM org.apache.beam.runners.flink.FlinkRunner run
INFO: Translating pipeline to Flink
program.
Nov 23, 2021 12:07:43 PM org.apache.beam.runners.flink.FlinkExec
...[truncated 869358 chars]...
ction.open(WrappingFunction.java:46)
	at
org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:34)
	at org.apache.flink.runtime.operators.BatchTask.run(BatchTask.java:508)
	...
4 more
Caused by: java.lang.Exception: Hasn't yet thrown
	at org.apache.beam.sdk.transforms.ParDoLifecycleTest$ExceptionThrowingFn.throwIfNecessary(ParDoLifecycleTest.java:432)
	at
org.apache.beam.sdk.transforms.ParDoLifecycleTest$ExceptionThrowingFn.before(ParDoLifecycleTest.java:395)

```

Imported from Jira [BEAM-13311](https://issues.apache.org/jira/browse/BEAM-13311). Original Jira may contain additional context.
Reported by: tvalentyn.

**Comment by kennknowles** [comment]
This is the same as #19814
