### ISSUE TITLE
Flake in org.apache.beam.sdk.io.mqtt.MqttIOTest.testReadObject: Address already in use

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21462]
```

org.apache.beam.sdk.io.mqtt.MqttIOTest.testReadObject

Failing for the past 1 build (Since #4376
)
Took 8 sec.
Error Message
java.io.IOException: Failed to bind to server socket: mqtt://localhost:38845
due to: java.net.BindException: Address already in use (Bind failed)
Stacktrace
java.io.IOException:
Failed to bind to server socket: mqtt://localhost:38845 due to: java.net.BindException: Address already
in use (Bind failed)
	at org.apache.activemq.util.IOExceptionSupport.create(IOExceptionSupport.java:34)
	at
org.apache.activemq.transport.tcp.TcpTransportServer.bind(TcpTransportServer.java:143)
	at org.apache.activemq.transport.tcp.TcpTransportFactory.doBind(TcpTransportFactory.java:62)
	at
org.apache.activemq.transport.TransportFactorySupport.bind(TransportFactorySupport.java:40)
	at org.apache.activemq.broker.BrokerService.createTransportConnector(BrokerService.java:2478)
	at
org.apache.activemq.broker.BrokerService.addConnector(BrokerService.java:338)
	at org.apache.activemq.broker.BrokerService.addConnector(BrokerService.java:328)
	at
org.apache.beam.sdk.io.mqtt.MqttIOTest.startBroker(MqttIOTest.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native
Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at
java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at
org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at
org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at
org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.apache.beam.sdk.testing.TestPipeline$1.evaluate(TestPipeline.java:323)
	at
org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at
org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at
org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at
org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at
org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at
org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at
org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at
org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at
org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at
org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at
org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at
org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at
org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at
org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at
com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
	at
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at
org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at
org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at
org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at
org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at
org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at
java.lang.Thread.run(Thread.java:748)
Caused by: java.net.BindException: Address already in use (Bind
failed)
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
	at
java.net.ServerSocket.bind(ServerSocket.java:390)
	at java.net.ServerSocket.<init>(ServerSocket.java:252)
	at
javax.net.DefaultServerSocketFactory.createServerSocket(ServerSocketFactory.java:231)
	at org.apache.activemq.transport.tcp.TcpTransportServer.bind(TcpTransportServer.java:140)
	...
59 more
Standard Error
Dec 13, 2021 10:17:02 PM org.apache.beam.sdk.io.mqtt.MqttIOTest startBroker
INFO:
Starting ActiveMQ brokerService on 38845
Dec 13, 2021 10:17:02 PM org.apache.activemq.broker.BrokerService
stop
INFO: Apache ActiveMQ 5.14.5 (localhost, null) is shutting down
Dec 13, 2021 10:17:02 PM org.apache.activemq.broker.BrokerService
stop
INFO: Apache ActiveMQ 5.14.5 (localhost, null) is shutdown
Dec 13, 2021 10:17:02 PM org.apache.beam.sdk.io.mqtt.MqttIOTest
startBroker
INFO: Starting ActiveMQ brokerService on 36981
Dec 13, 2021 10:17:03 PM org.apache.activemq.broker.BrokerService
doStartPersistenceAdapter
INFO: Using Persistence Adapter: MemoryPersistenceAdapter
Dec 13, 2021 10:17:03
PM org.apache.activemq.broker.jmx.ManagementContext$1 run
INFO: JMX consoles can connect to service:jmx:rmi:///jndi/rmi://localhost:1099/jmxrmi
Dec
13, 2021 10:17:04 PM org.apache.activemq.broker.BrokerService doStartBroker
INFO: Apache ActiveMQ 5.14.5
(localhost, ID:apache-ci-beam-jenkins-3-34821-1639433823589-0:1) is starting
Dec 13, 2021 10:17:04
PM org.apache.activemq.transport.TransportServerThreadSupport doStart
INFO: Listening for connections
at: mqtt://localhost:36981
Dec 13, 2021 10:17:04 PM org.apache.activemq.broker.TransportConnector start
INFO:
Connector mqtt://localhost:36981 started
Dec 13, 2021 10:17:04 PM org.apache.activemq.broker.BrokerService
doStartBroker
INFO: Apache ActiveMQ 5.14.5 (localhost, ID:apache-ci-beam-jenkins-3-34821-1639433823589-0:1)
started
Dec 13, 2021 10:17:04 PM org.apache.activemq.broker.BrokerService doStartBroker
INFO: For
help or more information please see: http://activemq.apache.org
Dec 13, 2021 10:17:18 PM org.apache.activemq.broker.BrokerService
stop
INFO: Apache ActiveMQ 5.14.5 (localhost, ID:apache-ci-beam-jenkins-3-34821-1639433823589-0:1)
is shutting down
Dec 13, 2021 10:17:18 PM org.apache.activemq.broker.TransportConnector stop
INFO:
Connector mqtt://localhost:36981 stopped
Dec 13, 2021 10:17:18 PM org.apache.activemq.broker.BrokerService
stop
INFO: Apache ActiveMQ 5.14.5 (localhost, ID:apache-ci-beam-jenkins-3-34821-1639433823589-0:1)
uptime 15.281 seconds
Dec 13, 2021 10:17:18 PM org.apache.activemq.broker.BrokerService stop
INFO:
Apache ActiveMQ 5.14.5 (localhost, ID:apache-ci-beam-jenkins-3-34821-1639433823589-0:1) is shutdown
Dec
13, 2021 10:17:18 PM org.apache.beam.sdk.io.mqtt.MqttIOTest startBroker
INFO: Starting ActiveMQ brokerService
on 45689
Dec 13, 2021 10:17:18 PM org.apache.activemq.broker.BrokerService doStartPersistenceAdapter
INFO:
Using Persistence Adapter: MemoryPersistenceAdapter
Dec 13, 2021 10:17:18 PM org.apache.activemq.broker.BrokerService
doStartBroker
INFO: Apache ActiveMQ 5.14.5 (localhost, ID:apache-ci-beam-jenkins-3-34821-1639433823589-0:2)
is starting
Dec 13, 2021 10:17:18 PM org.apache.activemq.broker.jmx.ManagementContext$1 run
INFO:
JMX consoles can connect to service:jmx:rmi:///jndi/rmi://localhost:1099/jmxrmi
Dec 13, 2021 10:17:18
PM org.apache.activemq.transport.TransportServerThreadSupport doStart
INFO: Listening for connections
at: mqtt://localhost:45689
Dec 13, 2021 10:17:18 PM org.apache.activemq.broker.TransportConnector start
INFO:
Connector mqtt://localhost:45689 started
Dec 13, 2021 10:17:18 PM org.apache.activemq.broker.BrokerService
doStartBroker
INFO: Apache ActiveMQ 5.14.5 (localhost, ID:apache-ci-beam-jenkins-3-34821-1639433823589-0:2)
started
Dec 13, 2021 10:17:18 PM org.apache.activemq.broker.BrokerService doStartBroker
INFO: For
help or more information please see: http://activemq.apache.org
Dec 13, 2021 10:17:18 PM org.apache.beam.sdk.coders.SerializableCoder
checkEqualsMethodDefined
WARNING: Can't verify serialized elements of type Shard have well defined
equals method. This may produce incorrect results on some PipelineRunner
Dec 13, 2021 10:17:19 PM org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector
verifyUnmodifiedThrowingCheckedExceptions
WARNING: Coder of type class org.apache.beam.sdk.coders.SerializableCoder
has a #structuralValue method which does not return true when the encoding of the elements is equal.
Element Shard{source=org.apache.beam.sdk.io.mqtt.MqttIO$UnboundedMqttSource@2c541ea7, maxNumRecords=9223372036854775807,
maxReadTime=PT2S}
Dec 13, 2021 10:17:19 PM org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector
verifyUnmodifiedThrowingCheckedExceptions
WARNING: Coder of type class org.apache.beam.sdk.coders.SerializableCoder
has a #structuralValue method which does not return true when the encoding of the elements is equal.
Element Shard{source=org.apache.beam.sdk.io.mqtt.MqttIO$UnboundedMqttSource@52c00c96, maxNumRecords=9223372036854775807,
maxReadTime=PT2S}
Dec 13, 2021 10:17:19 PM org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector
verifyUnmodifiedThrowingCheckedExceptions
WARNING: Coder of type class org.apache.beam.sdk.coders.SerializableCoder
has a #structuralValue method which does not return true when the encoding of the elements is equal.
Element Shard{source=org.apache.beam.sdk.io.mqtt.MqttIO$UnboundedMqttSource@2730c42b, maxNumRecords=9223372036854775807,
maxReadTime=PT2S}
Dec 13, 2021 10:17:19 PM org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector
verifyUnmodifiedThrowingCheckedExceptions
WARNING: Coder of type class org.apache.beam.sdk.coders.SerializableCoder
has a #structuralValue method which does not return true when the encoding of the elements is equal.
Element Shard{source=org.apache.beam.sdk.io.mqtt.MqttIO$UnboundedMqttSource@52c00c96, maxNumRecords=9223372036854775807,
maxReadTime=PT2S}
Dec 13, 2021 10:17:20 PM org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector
verifyUnmodifiedThrowingCheckedExceptions
WARNING: Coder of type class org.apache.beam.sdk.coders.SerializableCoder
has a #structuralValue method which does not return true when the encoding of the elements is equal.
Element Shard{source=org.apache.beam.sdk.io.mqtt.MqttIO$UnboundedMqttSource@7a8ba45e, maxNumRecords=9223372036854775807,
maxReadTime=PT2S}
Dec 13, 2021 10:17:20 PM org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector
verifyUnmodifiedThrowingCheckedExceptions
WARNING: Coder of type class org.apache.beam.sdk.coders.KvCoder
has a #structuralValue method which does not return true when the encoding of the elements is equal.
Element KV{171548182, Shard{source=org.apache.beam.sdk.io.mqtt.MqttIO$UnboundedMqttSource@7a8ba45e,
maxNumRecords=9223372036854775807, maxReadTime=PT2S}}
Dec 13, 2021 10:17:20 PM org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector
verifyUnmodifiedThrowingCheckedExceptions
WARNING: Coder of type class org.apache.beam.sdk.coders.SerializableCoder
has a #structuralValue method which does not return true when the encoding of the elements is equal.
Element Shard{source=org.apache.beam.sdk.io.mqtt.MqttIO$UnboundedMqttSource@7a8ba45e, maxNumRecords=9223372036854775807,
maxReadTime=PT2S}
Dec 13, 2021 10:17:20 PM org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector
verifyUnmodifiedThrowingCheckedExceptions
WARNING: Coder of type class org.apache.beam.sdk.coders.KvCoder
has a #structuralValue method which does not return true when the encoding of the elements is equal.
Element KV{171548182, Shard{source=org.apache.beam.sdk.io.mqtt.MqttIO$UnboundedMqttSource@7c7843b3,
maxNumRecords=9223372036854775807, maxReadTime=PT2S}}
Dec 13, 2021 10:17:20 PM org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector
verifyUnmodifiedThrowingCheckedExceptions
WARNING: Coder of type class org.apache.beam.sdk.coders.KvCoder
has a #structuralValue method which does not return true when the encoding of the elements is equal.
Element KV{171548182, TimestampedValue(Shard{source=org.apache.beam.sdk.io.mqtt.MqttIO$UnboundedMqttSource@7c7843b3,
maxNumRecords=9223372036854775807, maxReadTime=PT2S}, -290308-12-21T19:59:05.225Z)}
Dec 13, 2021 10:17:20
PM org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector verifyUnmodifiedThrowingCheckedExceptions
WARNING:
Coder of type class org.apache.beam.sdk.coders.KvCoder has a #structuralValue method which does not
return true when the encoding of the elements is equal. Element KV{171548182, Shard{source=org.apache.beam.sdk.io.mqtt.MqttIO$UnboundedMqttSource@7c7843b3,
maxNumRecords=9223372036854775807, maxReadTime=PT2S}}
Dec 13, 2021 10:17:21 PM org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector
verifyUnmodifiedThrowingCheckedExceptions
WARNING: Coder of type class org.apache.beam.sdk.coders.KvCoder
has a #structuralValue method which does not return true when the encoding of the elements is equal.
Element KV{171548182, [TimestampedValue(Shard{source=org.apache.beam.sdk.io.mqtt.MqttIO$UnboundedMqttSource@4f0ed6fe,
maxNumRecords=9223372036854775807, maxReadTime=PT2S}, -290308-12-21T19:59:05.225Z)]}
Dec 13, 2021 10:17:21
PM org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector verifyUnmodifiedThrowingCheckedExceptions
WARNING:
Coder of type class org.apache.beam.sdk.coders.KvCoder has a #structuralValue method which does not
return true when the encoding of the elements is equal. Element KV{171548182, TimestampedValue(Shard{source=org.apache.beam.sdk.io.mqtt.MqttIO$UnboundedMqttSource@4f0ed6fe,
maxNumRecords=9223372036854775807, maxReadTime=PT2S}, -290308-12-21T19:59:05.225Z)}
Dec 13, 2021 10:17:21
PM org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector verifyUnmodifiedThrowingCheckedExceptions
WARNING:
Coder of type class org.apache.beam.sdk.coders.KvCoder has a #structuralValue method which does not
return true when the encoding of the elements is equal. Element KV{171548182, [TimestampedValue(Shard{source=org.apache.beam.sdk.io.mqtt.MqttIO$UnboundedMqttSource@4f0ed6fe,
maxNumRecords=9223372036854775807, maxReadTime=PT2S}, -290308-12-21T19:59:05.225Z)]}
Dec 13, 2021 10:17:21
PM org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector verifyUnmodifiedThrowingCheckedExceptions
WARNING:
Coder of type class org.apache.beam.sdk.coders.KvCoder has a #structuralValue method which does not
return true when the encoding of the elements is equal. Element KV{171548182, TimestampedValue(Shard{source=org.apache.beam.sdk.io.mqtt.MqttIO$UnboundedMqttSource@1d6ae5ef,
maxNumRecords=9223372036854775807, maxReadTime=PT2S}, -290308-12-21T19:59:05.225Z)}
Dec 13, 2021 10:17:21
PM org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector verifyUnmodifiedThrowingCheckedExceptions
WARNING:
Coder of type class org.apache.beam.sdk.coders.KvCoder has a #structuralValue method which does not
return true when the encoding of the elements is equal. Element KV{171548182, TimestampedValue(Shard{source=org.apache.beam.sdk.io.mqtt.MqttIO$UnboundedMqttSource@1d6ae5ef,
maxNumRecords=9223372036854775807, maxReadTime=PT2S}, -290308-12-21T19:59:05.225Z)}
Dec 13, 2021 10:17:21
PM org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector verifyUnmodifiedThrowingCheckedExceptions
WARNING:
Coder of type class org.apache.beam.sdk.coders.KvCoder has a #structuralValue method which does not
return true when the encoding of the elements is equal. Element KV{171548182, TimestampedValue(Shard{source=org.apache.beam.sdk.io.mqtt.MqttIO$UnboundedMqttSource@1d6ae5ef,
maxNumRecords=9223372036854775807, maxReadTime=PT2S}, -290308-12-21T19:59:05.225Z)}
Dec 13, 2021 10:17:22
PM org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector verifyUnmodifiedThrowingCheckedExceptions
WARNING:
Coder of type class org.apache.beam.sdk.coders.KvCoder has a #structuralValue method which does not
return true when the encoding of the elements is equal. Element KV{171548182, TimestampedValue(Shard{source=org.apache.beam.sdk.io.mqtt.MqttIO$UnboundedMqttSource@2cfdbf6a,
maxNumRecords=9223372036854775807, maxReadTime=PT2S}, -290308-12-21T19:59:05.225Z)}
Dec 13, 2021 10:17:22
PM org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector verifyUnmodifiedThrowingCheckedExceptions
WARNING:
Coder of type class org.apache.beam.sdk.coders.KvCoder has a #structuralValue method which does not
return true when the encoding of the elements is equal. Element KV{171548182, Shard{source=org.apache.beam.sdk.io.mqtt.MqttIO$UnboundedMqttSource@2cfdbf6a,
maxNumRecords=9223372036854775807, maxReadTime=PT2S}}
Dec 13, 2021 10:17:22 PM org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector
verifyUnmodifiedThrowingCheckedExceptions
WARNING: Coder of type class org.apache.beam.sdk.coders.KvCoder
has a #structuralValue method which does not return true when the encoding of the elements is equal.
Element KV{171548182, TimestampedValue(Shard{source=org.apache.beam.sdk.io.mqtt.MqttIO$UnboundedMqttSource@2cfdbf6a,
maxNumRecords=9223372036854775807, maxReadTime=PT2S}, -290308-12-21T19:59:05.225Z)}
Dec 13, 2021 10:17:22
PM org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector verifyUnmodifiedThrowingCheckedExceptions
WARNING:
Coder of type class org.apache.beam.sdk.coders.KvCoder has a #structuralValue method which does not
return true when the encoding of the elements is equal. Element KV{171548182, Shard{source=org.apache.beam.sdk.io.mqtt.MqttIO$UnboundedMqttSource@4776c1e9,
maxNumRecords=9223372036854775807, maxReadTime=PT2S}}
Dec 13, 2021 10:17:22 PM org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector
verifyUnmodifiedThrowingCheckedExceptions
WARNING: Coder of type class org.apache.beam.sdk.coders.SerializableCoder
has a #structuralValue method which does not return true when the encoding of the elements is equal.
Element Shard{source=org.apache.beam.sdk.io.mqtt.MqttIO$UnboundedMqttSource@4776c1e9, maxNumRecords=9223372036854775807,
maxReadTime=PT2S}
Dec 13, 2021 10:17:22 PM org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector
verifyUnmodifiedThrowingCheckedExceptions
WARNING: Coder of type class org.apache.beam.sdk.coders.KvCoder
has a #structuralValue method which does not return true when the encoding of the elements is equal.
Element KV{171548182, Shard{source=org.apache.beam.sdk.io.mqtt.MqttIO$UnboundedMqttSource@4776c1e9,
maxNumRecords=9223372036854775807, maxReadTime=PT2S}}
Dec 13, 2021 10:17:24 PM org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector
verifyUnmodifiedThrowingCheckedExceptions
WARNING: Coder of type class org.apache.beam.sdk.coders.SerializableCoder
has a #structuralValue method which does not return true when the encoding of the elements is equal.
Element Shard{source=org.apache.beam.sdk.io.mqtt.MqttIO$UnboundedMqttSource@3be221aa, maxNumRecords=9223372036854775807,
maxReadTime=PT2S}
Dec 13, 2021 10:17:24 PM org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector
verifyUnmodifiedThrowingCheckedExceptions
WARNING: Coder of type class org.apache.beam.sdk.coders.SerializableCoder
has a #structuralValue method which does not return true when the encoding of the elements is equal.
Element Shard{source=org.apache.beam.sdk.io.mqtt.MqttIO$UnboundedMqttSource@3be221aa, maxNumRecords=9223372036854775807,
maxReadTime=PT2S}
Dec 13, 2021 10:17:24 PM org.apache.activemq.broker.BrokerService stop
INFO: Apache
ActiveMQ 5.14.5 (localhost, ID:apache-ci-beam-jenkins-3-34821-1639433823589-0:2) is shutting down
Dec
13, 2021 10:17:24 PM org.apache.activemq.broker.TransportConnector stop
INFO: Connector mqtt://localhost:45689
stopped
Dec 13, 2021 10:17:24 PM org.apache.activemq.broker.BrokerService stop
INFO: Apache ActiveMQ
5.14.5 (localhost, ID:apache-ci-beam-jenkins-3-34821-1639433823589-0:2) uptime 6.314 seconds
Dec 13,
2021 10:17:24 PM org.apache.activemq.broker.BrokerService stop
INFO: Apache ActiveMQ 5.14.5 (localhost,
ID:apache-ci-beam-jenkins-3-34821-1639433823589-0:2) is shutdown

```

Imported from Jira [BEAM-13453](https://issues.apache.org/jira/browse/BEAM-13453). Original Jira may contain additional context.
Reported by: tvalentyn.

**Comment by johnjcasey** [comment]
@tvalentyn has this reoccurred?

**Comment by tvalentyn** [comment]
I don't know. I haven't recently worked on a Java PR, but there may be a way to query history.

**Comment by kennknowles** [comment]
https://ci-beam.apache.org/job/beam_PreCommit_Java_Mqtt_IO_Direct_Cron/ is not flaky
