### ISSUE TITLE
beam_PostCommit_XVR_Flink flaky: Connection refused

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21469]
https://ci-beam.apache.org/job/beam_PostCommit_XVR_Flink/4980/

The following tests failed:

org.apache.beam.runners.core.construction.ValidateRunnerXlangTest$CoGroupByKeyTest.test
org.apache.beam.runners.core.construction.ValidateRunnerXlangTest$CoGroupByKeyTest.test
org.apache.beam.runners.core.construction.ValidateRunnerXlangTest$CombineGloballyTest.test
org.apache.beam.runners.core.construction.ValidateRunnerXlangTest$CombineGloballyTest.test
org.apache.beam.runners.core.construction.ValidateRunnerXlangTest$CombinePerKeyTest.test
org.apache.beam.runners.core.construction.ValidateRunnerXlangTest$CombinePerKeyTest.test
org.apache.beam.runners.core.construction.ValidateRunnerXlangTest$FlattenTest.test
org.apache.beam.runners.core.construction.ValidateRunnerXlangTest$FlattenTest.test
org.apache.beam.runners.core.construction.ValidateRunnerXlangTest$GroupByKeyTest.test
org.apache.beam.runners.core.construction.ValidateRunnerXlangTest$GroupByKeyTest.test
org.apache.beam.runners.core.construction.ValidateRunnerXlangTest$MultiInputOutputWithSideInputTest.test
org.apache.beam.runners.core.construction.ValidateRunnerXlangTest$MultiInputOutputWithSideInputTest.test
org.apache.beam.runners.core.construction.ValidateRunnerXlangTest$PartitionTest.test
org.apache.beam.runners.core.construction.ValidateRunnerXlangTest$PartitionTest.test
org.apache.beam.runners.core.construction.ValidateRunnerXlangTest$SingleInputOutputTest.test
org.apache.beam.runners.core.construction.ValidateRunnerXlangTest$SingleInputOutputTest.test
org.apache.beam.runners.core.construction.ValidateRunnerXlangTest$PythonDependenciesTest.test

error/stack trace: 
org.apache.beam.vendor.grpc.v1p43p2.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at org.apache.beam.vendor.grpc.v1p43p2.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at org.apache.beam.vendor.grpc.v1p43p2.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at org.apache.beam.vendor.grpc.v1p43p2.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at org.apache.beam.model.expansion.v1.ExpansionServiceGrpc$ExpansionServiceBlockingStub.expand(ExpansionServiceGrpc.java:169)
	at org.apache.beam.runners.core.construction.DefaultExpansionServiceClientFactory$1.expand(DefaultExpansionServiceClientFactory.java:63)
	at org.apache.beam.runners.core.construction.External$ExpandableTransform.expand(External.java:218)
	at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:548)
	at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:482)
	at org.apache.beam.sdk.transforms.join.KeyedPCollectionTuple.apply(KeyedPCollectionTuple.java:108)
	at org.apache.beam.runners.core.construction.ValidateRunnerXlangTest$ValidateRunnerXlangTestBase.coGroupByKeyTest(ValidateRunnerXlangTest.java:210)
	at org.apache.beam.runners.core.construction.ValidateRunnerXlangTest$CoGroupByKeyTest.test(ValidateRunnerXlangTest.java:345)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.apache.beam.sdk.testing.TestPipeline$1.evaluate(TestPipeline.java:323)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: org.apache.beam.vendor.grpc.v1p43p2.io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: localhost/127.0.0.1:45899
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
	at org.apache.beam.vendor.grpc.v1p43p2.io.netty.channel.unix.Errors.newConnectException0(Errors.java:155)
	at org.apache.beam.vendor.grpc.v1p43p2.io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128)
	at org.apache.beam.vendor.grpc.v1p43p2.io.netty.channel.unix.Socket.finishConnect(Socket.java:278)
	at org.apache.beam.vendor.grpc.v1p43p2.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:710)
	at org.apache.beam.vendor.grpc.v1p43p2.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:687)
	at org.apache.beam.vendor.grpc.v1p43p2.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567)
	at org.apache.beam.vendor.grpc.v1p43p2.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:470)
	at org.apache.beam.vendor.grpc.v1p43p2.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at org.apache.beam.vendor.grpc.v1p43p2.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at org.apache.beam.vendor.grpc.v1p43p2.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at org.apache.beam.vendor.grpc.v1p43p2.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Imported from Jira [BEAM-13809](https://issues.apache.org/jira/browse/BEAM-13809). Original Jira may contain additional context.
Reported by: ibzib.

**Comment by damccorm** [comment]
Closing since this is for a decommissioned Jenkins job
