### ISSUE TITLE
Test flake: test_split_half_sdf

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21470]
\>       raise RuntimeError(result.error)
E       RuntimeError: Traceback (most recent call last):
E         File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Commit/src/sdks/python/test-suites/tox/py37/build/srcs/sdks/python/apache_beam/runners/worker/data_plane.py", line 487, in input_elements
E           element = received.get(timeout=1)
E         File "/usr/lib/python3.7/queue.py", line 178, in get
E           raise Empty
E       _queue.Empty
E       
E       During handling of the above exception, another exception occurred:
E       
E       Traceback (most recent call last):
E         File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Commit/src/sdks/python/test-suites/tox/py37/build/srcs/sdks/python/apache_beam/runners/worker/sdk_worker.py", line 267, in _execute
E           response = task()
E         File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Commit/src/sdks/python/test-suites/tox/py37/build/srcs/sdks/python/apache_beam/runners/worker/sdk_worker.py", line 340, in <lambda\>
E           lambda: self.create_worker().do_instruction(request), request)
E         File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Commit/src/sdks/python/test-suites/tox/py37/build/srcs/sdks/python/apache_beam/runners/worker/sdk_worker.py", line 581, in do_instruction
E           getattr(request, request_type), request.instruction_id)
E         File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Commit/src/sdks/python/test-suites/tox/py37/build/srcs/sdks/python/apache_beam/runners/worker/sdk_worker.py", line 618, in process_bundle
E           bundle_processor.process_bundle(instruction_id))
E         File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Commit/src/sdks/python/test-suites/tox/py37/build/srcs/sdks/python/apache_beam/runners/worker/bundle_processor.py", line 985, in process_bundle
E           expected_inputs):
E         File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Commit/src/sdks/python/test-suites/tox/py37/build/srcs/sdks/python/apache_beam/runners/worker/data_plane.py", line 490, in input_elements
E           raise RuntimeError('Channel closed prematurely.')
E       RuntimeError: Channel closed prematurely.

Imported from Jira [BEAM-13859](https://issues.apache.org/jira/browse/BEAM-13859). Original Jira may contain additional context.
Reported by: ibzib.

**Comment by damccorm** [comment]
This hasn't caused CI to fail in current history of the cron job. I also tried running it 100 times locally and it didn't flake (`for i in {1..100} ; do (pytest -v apache_beam/runners/portability/fn_api_runner/fn_runner_test.py::FnApiRunnerSplitTest::test_split_half_sdf) ; done`)
