### ISSUE TITLE
SpannerChangeStreamErrorTest.testUnavailableExceptionRetries hard failure (disabled)

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21533]
Example failures: 
* https://ci-beam.apache.org/job/beam_PreCommit_Java_Commit/21726/testReport/junit/org.apache.beam.sdk.io.gcp.spanner.changestreams/SpannerChangeStreamErrorTest/testUnavailableExceptionRetries/
* https://ci-beam.apache.org/job/beam_PreCommit_Java_Commit/21723/testReport/junit/org.apache.beam.sdk.io.gcp.spanner.changestreams/SpannerChangeStreamErrorTest/testUnavailableExceptionRetries/

```

java.lang.AssertionError: 
Expected: a value greater than <1>
     but: <0> was less than <1>
	at
org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at
org.apache.beam.sdk.io.gcp.spanner.changestreams.SpannerChangeStreamErrorTest.testUnavailableExceptionRetries(SpannerChangeStreamErrorTest.java:166)
	at
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at
org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at
org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at
org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at
org.apache.beam.sdk.testing.TestPipeline$1.evaluate(TestPipeline.java:323)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:258)
	at
org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)

```

Imported from Jira [BEAM-14152](https://issues.apache.org/jira/browse/BEAM-14152). Original Jira may contain additional context.
Reported by: lcwik.

**Comment by kennknowles** [comment]
Confirmed this on my first try: https://scans.gradle.com/s/s3rz2sggpks4m/tests/:sdks:java:io:google-cloud-platform:test/org.apache.beam.sdk.io.gcp.spanner.changestreams.SpannerChangeStreamErrorTest/testUnavailableExceptionRetries?top-execution=1

**Comment by kennknowles** [comment]
So far 100% failure rate, not flaking.

**Comment by kennknowles** [comment]
Seems the test is expecting a particular proto class in a mock, so it isn't lining up with expected results

**Comment by kennknowles** [comment]
@zoercai @thiagotnunes this test is now a hard failure. It looks like it is caused by the way it uses mocking, even though the results of a retry may be fine.

**Comment by thiagotnunes** [comment]
@nancyxu123

**Comment by Abacn** [comment]
Looks like the mockSpannerService in SpannerChangeStreamErrorTest actually does not taking effect. It also affects current test suite beam_PreCommit_Java_GCP_IO_Direct where `org.apache.beam.sdk.io.gcp.spanner.changestreams.SpannerChangeStreamErrorTest.testAbortedExceptionNotRetriedithDefaultsForStreamSqlRetrySettings` costs 5 minutes exactly on success run. The test being success due to real grpc DEADLINE_EXCEEDED.

Reopen the issue for now for mockSpannerService not working properly
