### ISSUE TITLE
BigQueryIO: NullPointerException in BigQueryServicesImpl

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21535]
Encountered several times on Beam 2.37.0 using BigQuery Streaming Inserts:
```

java.lang.RuntimeException: java.lang.NullPointerException
	at org.apache.beam.sdk.io.gcp.bigquery.BigQueryServicesImpl$DatasetServiceImpl.insertAll(BigQueryServicesImpl.java:1101)
	at
org.apache.beam.sdk.io.gcp.bigquery.BigQueryServicesImpl$DatasetServiceImpl.insertAll(BigQueryServicesImpl.java:1154)
	at
org.apache.beam.sdk.io.gcp.bigquery.BatchedStreamingWrite.flushRows(BatchedStreamingWrite.java:374)
	at
org.apache.beam.sdk.io.gcp.bigquery.BatchedStreamingWrite.access$900(BatchedStreamingWrite.java:69)
	at
org.apache.beam.sdk.io.gcp.bigquery.BatchedStreamingWrite$BatchAndInsertElements.finishBundle(BatchedStreamingWrite.java:263)
Caused
by: java.lang.NullPointerException
	at org.apache.beam.sdk.io.gcp.bigquery.BigQueryServicesImpl$DatasetServiceImpl.getErrorInfo(BigQueryServicesImpl.java:1175)
	at
org.apache.beam.sdk.io.gcp.bigquery.BigQueryServicesImpl$DatasetServiceImpl$InsertBatchofRowsCallable.call(BigQueryServicesImpl.java:879)
	at
org.apache.beam.sdk.io.gcp.bigquery.BigQueryServicesImpl$DatasetServiceImpl$InsertBatchofRowsCallable.call(BigQueryServicesImpl.java:818)
	at
org.apache.beam.sdk.io.gcp.bigquery.BigQueryServicesImpl$BoundedExecutorService$SemaphoreCallable.call(BigQueryServicesImpl.java:1697)
	at
java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

Imported from Jira [BEAM-14074](https://issues.apache.org/jira/browse/BEAM-14074). Original Jira may contain additional context.
Reported by: dennis.waldron.

**Comment by dennisatspaceape** [comment]
This can be closed. See conversation history at https://issues.apache.org/jira/browse/BEAM-14074
A batch was submitted via another issue https://issues.apache.org/jira/browse/BEAM-14133
