### ISSUE TITLE
beam_PreCommit_PythonDocs failing (jinja2)

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21587]
I'm guessing a new jinja2 release broke us (https://pypi.org/project/Jinja2/#history)

12:16:08 Traceback (most recent call last):
12:16:08   File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_PythonDocs_Commit/src/sdks/python/test-suites/tox/pycommon/build/srcs/sdks/python/target/.tox-py38-docs/py38-docs/bin/sphinx-apidoc", line 7, in <module\>
12:16:08     from sphinx.ext.apidoc import main
12:16:08   File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_PythonDocs_Commit/src/sdks/python/test-suites/tox/pycommon/build/srcs/sdks/python/target/.tox-py38-docs/py38-docs/lib/python3.8/site-packages/sphinx/ext/apidoc.py", line 32, in <module\>
12:16:08     from sphinx.cmd.quickstart import EXTENSIONS
12:16:08   File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_PythonDocs_Commit/src/sdks/python/test-suites/tox/pycommon/build/srcs/sdks/python/target/.tox-py38-docs/py38-docs/lib/python3.8/site-packages/sphinx/cmd/quickstart.py", line 49, in <module\>
12:16:08     from sphinx.util.template import SphinxRenderer
12:16:08   File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_PythonDocs_Commit/src/sdks/python/test-suites/tox/pycommon/build/srcs/sdks/python/target/.tox-py38-docs/py38-docs/lib/python3.8/site-packages/sphinx/util/template.py", line 17, in <module\>
12:16:08     from sphinx.jinja2glue import SphinxFileSystemLoader
12:16:08   File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_PythonDocs_Commit/src/sdks/python/test-suites/tox/pycommon/build/srcs/sdks/python/target/.tox-py38-docs/py38-docs/lib/python3.8/site-packages/sphinx/jinja2glue.py", line 16, in <module\>
12:16:08     from jinja2 import FileSystemLoader, BaseLoader, TemplateNotFound, \
12:16:08 ImportError: cannot import name 'contextfunction' from 'jinja2' (/home/jenkins/jenkins-slave/workspace/beam_PreCommit_PythonDocs_Commit/src/sdks/python/test-suites/tox/pycommon/build/srcs/sdks/python/target/.tox-py38-docs/py38-docs/lib/python3.8/site-packages/jinja2/__init__.py)

Imported from Jira [BEAM-14172](https://issues.apache.org/jira/browse/BEAM-14172). Original Jira may contain additional context.
Reported by: ibzib.

**Comment by damccorm** [comment]
This is now healthy - https://ci-beam.apache.org/job/beam_PreCommit_PythonDocs_Cron/
