### ISSUE TITLE
google_cloud_bigtable_client_core is deprecated/maintenance mode  

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21592]
google_cloud_bigtable_client_core is incompatible with gax included in gcp bom 24.2.0****, and is meant to be deprecated

 

Currently this is used for [https://github.com/googleapis/java-bigtable-hbase/tree/main/bigtable-dataflow-parent/bigtable-hbase-beam](https://github.com/googleapis/java-bigtable-hbase/tree/main/bigtable-dataflow-parent/bigtable-hbase-beam)

Ideally we move away from using this library in general. 

Imported from Jira [BEAM-14309](https://issues.apache.org/jira/browse/BEAM-14309). Original Jira may contain additional context.
Reported by: emilymye.

**Comment by janhicken** [comment]
As of Apache Beam 2.42.0, we cannot create instances of `BigtableDataClient` any more, because a `NoSuchMethodError` is thrown. It seems to be related to this dependency issue.

Stack trace:
```
org.apache.beam.vendor.guava.v26_0_jre.com.google.common.util.concurrent.UncheckedExecutionException: org.apache.beam.sdk.util.UserCodeException: java.lang.NoSuchMethodError: 'io.grpc.MethodDescriptor com.google.bigtable.v2.BigtableGrpc.getPingAndWarmMethod()'
	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2050)
	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.cache.LocalCache.get(LocalCache.java:3952)
	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at org.apache.beam.runners.direct.DoFnLifecycleManager.get(DoFnLifecycleManager.java:62)
	at org.apache.beam.runners.direct.ParDoEvaluatorFactory.createEvaluator(ParDoEvaluatorFactory.java:131)
	at org.apache.beam.runners.direct.ParDoEvaluatorFactory.forApplication(ParDoEvaluatorFactory.java:81)
	at org.apache.beam.runners.direct.TransformEvaluatorRegistry.forApplication(TransformEvaluatorRegistry.java:162)
	at org.apache.beam.runners.direct.DirectTransformExecutor.run(DirectTransformExecutor.java:122)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.beam.sdk.util.UserCodeException: java.lang.NoSuchMethodError: 'io.grpc.MethodDescriptor com.google.bigtable.v2.BigtableGrpc.getPingAndWarmMethod()'
	at org.apache.beam.sdk.util.UserCodeException.wrap(UserCodeException.java:39)
	at io.github.example.MyDoFn$DoFnInvoker.invokeSetup(Unknown Source)
	at org.apache.beam.sdk.transforms.reflect.DoFnInvokers.tryInvokeSetupFor(DoFnInvokers.java:53)
	at org.apache.beam.runners.direct.DoFnLifecycleManager$DeserializingCacheLoader.load(DoFnLifecycleManager.java:107)
	at org.apache.beam.runners.direct.DoFnLifecycleManager$DeserializingCacheLoader.load(DoFnLifecycleManager.java:92)
	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
	... 13 more
Caused by: java.lang.NoSuchMethodError: 'io.grpc.MethodDescriptor com.google.bigtable.v2.BigtableGrpc.getPingAndWarmMethod()'
	at com.google.cloud.bigtable.data.v2.stub.EnhancedBigtableStub.createPingAndWarmCallable(EnhancedBigtableStub.java:835)
	at com.google.cloud.bigtable.data.v2.stub.EnhancedBigtableStub.<init>(EnhancedBigtableStub.java:290)
	at com.google.cloud.bigtable.data.v2.stub.EnhancedBigtableStub.create(EnhancedBigtableStub.java:153)
	at com.google.cloud.bigtable.data.v2.BigtableDataClient.create(BigtableDataClient.java:162)
```
