### ISSUE TITLE
[Bug]: RedisIO#readKeyPatterns failing with OutOfMemory on version 2.39.0

### ISSUE THREAD

**Issue by djaneluz** [apache/beam#21825]
### What happened?

I'm using **RedisIO** to read/write values on cache and it was working fine with version _2.38.0._ 

When I moved to version _2.39.0_ I started getting errors like: 

`Execution of work for computation 'P13' for key '<�֤#�͵.;]�NDC���^m��=�w<@癢P�u:k<��ުm�7����6�';��z	�<	z0��>2QN����9EX�-����k\����eL�	�( ���a����;��φ' failed with out-of-memory. Work will not be retried locally. Heap dump not written.`

With stacktrace:

`java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
	at java.base/java.lang.Thread.start0(Native Method)
	at java.base/java.lang.Thread.start(Thread.java:803)
	at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:937)
	at java.base/java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1583)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:346)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
	at java.base/java.util.concurrent.Executors$DelegatedScheduledExecutorService.schedule(Executors.java:779)
	at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.OutputAndTimeBoundedSplittableProcessElementInvoker$ProcessContext.onClaimed(OutputAndTimeBoundedSplittableProcessElementInvoker.java:312)
	at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.sdk.fn.splittabledofn.RestrictionTrackers$RestrictionTrackerObserver.tryClaim(RestrictionTrackers.java:60)
	at org.apache.beam.sdk.io.redis.RedisIO$ReadFn.processElement(RedisIO.java:399)`

The error happens when calling `RedisIO.readKeyPatterns()`

The pipeline get stuck in the Step: `.../ReadRedis/ParDo(Read)/ParMultiDo(Read)/ProcessKeyedElements.out0`

### Issue Priority

Priority: 0

### Issue Component

Component: io-java-redis

**Comment by aromanenko-dev** [comment]
It can be related to this change #15549 as the latest big change in `RedisIO`.

@MiguelAnzoWizeline @benWize Could you take a look, please?

**Comment by benWize** [comment]
Hi @aromanenko-dev!
Miguel who made the larger changes in `RedisIO` is no longer working on this project, but I will sync with him and provide a response in a couple of days.

**Comment by aromanenko-dev** [comment]
@benWize Many thanks!

**Comment by aromanenko-dev** [comment]
@benWize Kind ping on this. Do you have any news by chance?

**Comment by roger-mike** [comment]
Hi, could you give more details about how to reproduce this error?

**Comment by aromanenko-dev** [comment]
Ping @djaneluz

**Comment by djaneluz** [comment]
Hello!

I have a streaming pipeline that consumes Pub/Sub messages, extracts keys, group them by window (FixedWindow of 5 min) and call Redis to get the values, that are used as side input to another step.

Something like:

        final PCollection<KV<String, Iterable<MyMessage>>> myMessageKV = pipeline
            .apply("ReadPubSubMessages", PubsubIO.readMessages().fromSubscription(options.getSubscription()))
            .apply("ExtractAndParse", ParDo.of(new ExtractAndParse()))
            .apply("MapMessageWithKey", MapElements.into(TypeDescriptors.kvs(TypeDescriptors.strings(), 
        TypeDescriptor.of(MyMessage.class)))
                .via(m-> KV.of(m.getMyKey(), m)))
            .apply("5MinFixedWindow", Window.into(FixedWindows.of(Duration.standardMinutes(5))))
            .apply("GroupByKey", GroupByKey.create());

        final PCollectionView<Map<String, Iterable<String>>> myCache = myMessageKV 
                .apply("ExtractKeys", Keys.create())
                .apply("ReadRedis", RedisIO.readKeyPatterns()
                        .withEndpoint(redisHost, REDIS_PORT)
                        .withOutputParallelization(false))
                .apply("ViewAsMultiMapFromCache", View.asMultimap());

        final PCollectionTuple outputs = myMessageKV 
                .apply("EnrichMessage", ParDo.of(new EnrichMessages())
                         .withSideInput(REF_CODE_CACHE_TAG_ID, refCodeCache));

        ...

I just ran the pipeline again with BEAM version _2.41.0_ and got the error. With version _2.38.0_ it works just fine.

Let me know what more do you need.

Thanks

**Comment by djaneluz** [comment]
Hello, is there any update on this? Thanks

**Comment by djaneluz** [comment]
I tested the pipeline with Apache Beam version 2.56.0 and the problem still happens

**Comment by djaneluz** [comment]
ping @roger-mike
