### ISSUE TITLE
[Bug]: Running Java pipeline with JDBCIO when using a window causes a ClassCastException

### ISSUE THREAD

**Issue by sshahar1** [apache/beam#21882]
### What happened?

I have a pipeline that reads data, windows it, groups, aggregates and write to a relational DB
Code below in Kotlin
```
pipeline
    .apply(
        "WaitForNewFiles",
        FileIO.match()
            .filepattern(inputPath)
            .continuously(
                // Check for new files every 2 minute
                Duration.standardMinutes(2),
                // Never stop checking for new files
                Watch.Growth.never()
            )
    )
    .apply("GetFiles", FileIO.readMatches())
    .apply(TextIO.readFiles())
    .apply("ToTuple", ParDo.of(toTuple))
    .apply(
        "WaitForLines",
        Window.into<T>(FixedWindows.of(Duration.standardMinutes(1)))
            .triggering(AfterWatermark.pastEndOfWindow())
            .discardingFiredPanes()
            .withAllowedLateness(Duration.ZERO)
    ).apply("Filter", Filter.by(Matcher()))
        .apply("Flatten", ParDo.of(FlattenRecords()))
        .setCoder(AvroCoder.of(MyRecord::class.java))
        .apply("Insert to database",
            JdbcIO.write<MyRecord>()
                .withDataSourceProviderFn(dsProvider)
                .withStatement(cloud_sql_rome_records_insert)
                .withPreparedStatementSetter(preparedSetter()))
```

Up until upgrading to Apache Beam 2.37 it worked, but after an upgrade we started getting the following Exceptions (and alot of them):
```
java.lang.ClassCastException: class org.apache.beam.sdk.transforms.windowing.GlobalWindow cannot be cast to class org.apache.beam.sdk.transforms.windowing.IntervalWindow (org.apache.beam.sdk.transforms.windowing.GlobalWindow and org.apache.beam.sdk.transforms.windowing.IntervalWindow are in unnamed module of loader 'app')
at org.apache.beam.sdk.transforms.windowing.IntervalWindow$IntervalWindowCoder.registerByteSizeObserver(IntervalWindow.java:142)
at org.apache.beam.sdk.coders.IterableLikeCoder.registerByteSizeObserver(IterableLikeCoder.java:211)
at org.apache.beam.sdk.coders.IterableLikeCoder.registerByteSizeObserver(IterableLikeCoder.java:60)
at org.apache.beam.sdk.util.WindowedValue$FullWindowedValueCoder.registerByteSizeObserver(WindowedValue.java:640)
at org.apache.beam.sdk.util.WindowedValue$FullWindowedValueCoder.registerByteSizeObserver(WindowedValue.java:558)
at org.apache.beam.runners.dataflow.worker.IntrinsicMapTaskExecutorFactory$ElementByteSizeObservableCoder.registerByteSizeObserver(IntrinsicMapTaskExecutorFactory.java:403)
at org.apache.beam.runners.dataflow.worker.util.common.worker.OutputObjectAndByteCounter.update(OutputObjectAndByteCounter.java:128)
at org.apache.beam.runners.dataflow.worker.DataflowOutputCounter.update(DataflowOutputCounter.java:67)
at org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:43)
at org.apache.beam.runners.dataflow.worker.SimpleParDoFn$1.output(SimpleParDoFn.java:285)
at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.outputWindowedValue(SimpleDoFnRunner.java:268)
at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.access$900(SimpleDoFnRunner.java:84)
at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner$DoFnFinishBundleArgumentProvider$Context.output(SimpleDoFnRunner.java:326)
at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner$DoFnFinishBundleArgumentProvider$Context.output(SimpleDoFnRunner.java:321)
at org.apache.beam.sdk.io.jdbc.JdbcIO$1.finish(JdbcIO.java:1613)
```

The new code introduced in 2.37 in JDBCIO includes:
```
@FinishBundle
                    public void finish(FinishBundleContext c) {
                      if (outputList != null && outputList.size() > 0) {
                        c.output(outputList, Instant.now(), GlobalWindow.INSTANCE);
                      }
                      outputList = null;
                    }
```
https://github.com/apache/beam/blob/d97c52117b7bc5dc844da73d368afb16d0a18abb/sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcIO.java#L1610

So, from what I understand the time interval and global interval conflict.

This is a very vague exception obviously and should be addressed in documentation.

Thanks in advance

### Issue Priority

Priority: 2

### Issue Component

Component: io-java-jdbc

**Comment by sshahar1** [comment]
I would highly appreciate to hear recommendations or opinions on this issue

**Comment by Abacn** [comment]
Not familiar with kotlin, but cannot reproduce this with Java code snippet, using either release-2.39.0 or master. Setting a log in the referred method, confirmed that the method was evaluated.

```java

@Test
  public void TestWriteUsingWindow() throws Exception {
    String tableName = DatabaseTestHelper.getTestTableName("UT_WRITE");
    DatabaseTestHelper.createTable(DATA_SOURCE, tableName);

    pipeline.apply("Generate Periodic Impulse",
            PeriodicImpulse.create().startAt(Instant.now()).stopAt(Instant.now().plus(Duration.standardSeconds(14))).withInterval(Duration.standardSeconds(5)))
        .apply("Generate Records", ParDo.of(
            new DoFn<Instant, KV<Integer, String>>() {
              @ProcessElement
              public void processElement(ProcessContext context) {
                ArrayList<KV<Integer, String>> data = getDataToWrite(10);
                for(KV<Integer, String> datum: data) {
                  context.output(datum);
                }
              }
            }))
        .apply(
            "WaitForLines",
            Window.<KV<Integer, String>>into(FixedWindows.of(Duration.standardSeconds(5)))
                .triggering(AfterWatermark.pastEndOfWindow())
                .discardingFiredPanes()
                .withAllowedLateness(Duration.ZERO))
        .apply(getJdbcWrite(tableName));

    pipeline.run();

    assertRowCount(DATA_SOURCE, tableName, 3*10);
    DatabaseTestHelper.deleteTable(DATA_SOURCE, tableName);
  }
```

Likely due to compiler not correctly infer the signature of `FinishBundleContext.output` here? In DoFn class it has a type of BoundedWindow. Both GlobalWindow and IntervalWindow can be cast to BoundedWindow.

**Comment by scott-strong** [comment]
Hi @sshahar1 @Abacn,

I ran into the same issue in my java pipeline. We upgraded to Apache Beam 2.39 and started getting the exact error message from above. I can't post the exact pipeline, but we're streaming Pub/Sub events, transforming and windowing, then writing them to MySQL. Below is the windowing function:
```
Window.<SimplifiedEvent>into(FixedWindows.of(Duration.standardMinutes(options.getWindowDurationMinutes())))
    .discardingFiredPanes()
```

I'm curious if Sigal has resolved this since this post, or if there have been any other reports of this error message occurring. I know there was a test case where this is passing, but following the stacktrace I don't see how the `GlobalWindow` would work when passed to the `IntervalWindowCoder`. Any info is appreciated. Thanks.

**Comment by Abacn** [comment]
Hi @pabloem do you have an idea of the fix? Seems like here the third parameter is not compatible in the case of fixed window

https://github.com/apache/beam/blob/76761db371c8e33136706872f83d89ea600022db/sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcIO.java#L1642

**Comment by sshahar1** [comment]
> Hi @sshahar1 @Abacn,
> 
> I ran into the same issue in my java pipeline. We upgraded to Apache Beam 2.39 and started getting the exact error message from above. I can't post the exact pipeline, but we're streaming Pub/Sub events, transforming and windowing, then writing them to MySQL. Below is the windowing function:
> 
> ```
> Window.<SimplifiedEvent>into(FixedWindows.of(Duration.standardMinutes(options.getWindowDurationMinutes())))
>     .discardingFiredPanes()
> ```
> 
> I'm curious if Sigal has resolved this since this post, or if there have been any other reports of this error message occurring. I know there was a test case where this is passing, but following the stacktrace I don't see how the `GlobalWindow` would work when passed to the `IntervalWindowCoder`. Any info is appreciated. Thanks.

Nothing further we could do, unfortunatey

**Comment by sshahar1** [comment]
> Not familiar with kotlin, but cannot reproduce this with Java code snippet, using either release-2.39.0 or master. Setting a log in the referred method, confirmed that the method was evaluated.
> 
> ```java
> @Test
>   public void TestWriteUsingWindow() throws Exception {
>     String tableName = DatabaseTestHelper.getTestTableName("UT_WRITE");
>     DatabaseTestHelper.createTable(DATA_SOURCE, tableName);
> 
>     pipeline.apply("Generate Periodic Impulse",
>             PeriodicImpulse.create().startAt(Instant.now()).stopAt(Instant.now().plus(Duration.standardSeconds(14))).withInterval(Duration.standardSeconds(5)))
>         .apply("Generate Records", ParDo.of(
>             new DoFn<Instant, KV<Integer, String>>() {
>               @ProcessElement
>               public void processElement(ProcessContext context) {
>                 ArrayList<KV<Integer, String>> data = getDataToWrite(10);
>                 for(KV<Integer, String> datum: data) {
>                   context.output(datum);
>                 }
>               }
>             }))
>         .apply(
>             "WaitForLines",
>             Window.<KV<Integer, String>>into(FixedWindows.of(Duration.standardSeconds(5)))
>                 .triggering(AfterWatermark.pastEndOfWindow())
>                 .discardingFiredPanes()
>                 .withAllowedLateness(Duration.ZERO))
>         .apply(getJdbcWrite(tableName));
> 
>     pipeline.run();
> 
>     assertRowCount(DATA_SOURCE, tableName, 3*10);
>     DatabaseTestHelper.deleteTable(DATA_SOURCE, tableName);
>   }
> ```
> 
> The test passed. For Kotlin then likely due to compiler not correctly infer the signature of `FinishBundleContext.output` here? In DoFn class it has a type of BoundedWindow. Both GlobalWindow and IntervalWindow can be cast to BoundedWindow.

I checked the decompiled code, I don't see anything that can cause this

**Comment by scott-strong** [comment]
@pabloem do you have any suggestions on how we can fix this? It's currently blocking us from upgrading our pipelines that use fixed windows. I was thinking maybe we need to handle the work being done in `finish` using a timer and setting an expiry. It seems like we're basically just buffering and flushing, but need to make sure the buffer get left with elements.

I was also wondering if we should be using dedicated state mechanisms to handle this. It seems like we should be adding these elements to a `BagState` instead of a local variable. I started working on it but wanted to get your opinion since you originally wrote this feature.

**Comment by sriram23kmm** [comment]
Is there any update on this issue

**Comment by Abacn** [comment]
Apparently this does not show up in direct runner because it does not do the windowing coding thing. It is broken in Dataflow runner indeed. Looking into it.

**Comment by Abacn** [comment]
As a workaround, could you please try add `.withAutoSharding()` into JdbcIO.write ? (ref https://beam.apache.org/releases/javadoc/current/org/apache/beam/sdk/io/jdbc/JdbcIO.Write.html#withAutoSharding--) this avoided the problematic line in the issue description.

**Comment by sshahar1** [comment]
I no longer have access to this code and project

**Comment by sriram23kmm** [comment]
This is only working when the streaming engine is enabled in dataflow can you suggest any other alternatives

**Comment by yelianevich** [comment]
I get the same issue when running on Apache Flink 1.16.3 with Apache Beam 2.57.0 using bounded data source and IntervalWindow.
```
Caused by: org.apache.beam.sdk.util.UserCodeException: java.lang.ClassCastException: class org.apache.beam.sdk.transforms.windowing.GlobalWindow cannot be cast to class org.apache.beam.sdk.transforms.windowing.IntervalWindow (org.apache.beam.sdk.transforms.windowing.GlobalWindow and org.apache.beam.sdk.transforms.windowing.IntervalWindow are in unnamed module of loader 'app')
	at org.apache.beam.sdk.util.UserCodeException.wrap(UserCodeException.java:39) ~[beam-runners-direct-java-2.57.0.jar:?]
	at org.apache.beam.sdk.transforms.MapElements$MapWithFailures$2$DoFnInvoker.invokeProcessElement(Unknown Source) ~[?:?]
	at org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:212) ~[beam-runners-core-java-2.57.0.jar:?]
	at org.apache.beam.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:189) ~[beam-runners-core-java-2.57.0.jar:?]
	at org.apache.beam.runners.flink.metrics.DoFnRunnerWithMetricsUpdate.processElement(DoFnRunnerWithMetricsUpdate.java:62) ~[beam-runners-flink-1.16-2.57.0.jar:?]
	at org.apache.beam.runners.flink.translation.functions.FlinkDoFnFunction.flatMap(FlinkDoFnFunction.java:122) ~[beam-runners-flink-1.16-2.57.0.jar:?]
	at org.apache.beam.runners.flink.translation.functions.FlinkDoFnFunction.flatMap(FlinkDoFnFunction.java:59) ~[beam-runners-flink-1.16-2.57.0.jar:?]
	at org.apache.flink.runtime.operators.chaining.ChainedFlatMapDriver.collect(ChainedFlatMapDriver.java:79) ~[flink-dist-1.16.3.jar:1.16.3]
	at org.apache.flink.runtime.operators.util.metrics.CountingCollector.collect(CountingCollector.java:35) ~[flink-dist-1.16.3.jar:1.16.3]
	at org.apache.beam.runners.flink.translation.functions.FlinkMultiOutputPruningFunction.flatMap(FlinkMultiOutputPruningFunction.java:60) ~[beam-runners-flink-1.16-2.57.0.jar:?]
	at org.apache.beam.runners.flink.translation.functions.FlinkMultiOutputPruningFunction.flatMap(FlinkMultiOutputPruningFunction.java:35) ~[beam-runners-flink-1.16-2.57.0.jar:?]
	at org.apache.flink.runtime.operators.chaining.ChainedFlatMapDriver.collect(ChainedFlatMapDriver.java:79) ~[flink-dist-1.16.3.jar:1.16.3]
	at org.apache.flink.runtime.operators.util.metrics.CountingCollector.collect(CountingCollector.java:35) ~[flink-dist-1.16.3.jar:1.16.3]
	at org.apache.beam.runners.flink.translation.functions.FlinkDoFnFunction$DoFnOutputManager.output(FlinkDoFnFunction.java:221) ~[beam-runners-flink-1.16-2.57.0.jar:?]
	at org.apache.beam.runners.core.SimpleDoFnRunner.outputWindowedValue(SimpleDoFnRunner.java:276) ~[beam-runners-core-java-2.57.0.jar:?]
	at org.apache.beam.runners.core.SimpleDoFnRunner.access$900(SimpleDoFnRunner.java:86) ~[beam-runners-core-java-2.57.0.jar:?]
	at org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:432) ~[beam-runners-core-java-2.57.0.jar:?]
	at org.apache.beam.sdk.transforms.DoFnOutputReceivers$WindowedContextOutputReceiver.output(DoFnOutputReceivers.java:89) ~[beam-runners-direct-java-2.57.0.jar:?]
```
