### ISSUE TITLE
[Bug]: More NPEs in IsmReaderImpl (BEAM-14187)

### ISSUE THREAD

**Issue by steveniemitz** [apache/beam#22080]
### What happened?

https://issues.apache.org/jira/browse/BEAM-14187 attempted to fix an NPE in IsmReaderImpl, however it doesn't seem like this is completely fixed.

We're seeing errors like:
```
Caused by: java.lang.NullPointerException
	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:877)
	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.base.Optional.of(Optional.java:103)
	at org.apache.beam.runners.dataflow.worker.IsmReaderImpl.initializeForKeyedRead(IsmReaderImpl.java:566)
	at org.apache.beam.runners.dataflow.worker.IsmReaderImpl.overKeyComponents(IsmReaderImpl.java:200)
	at org.apache.beam.runners.dataflow.worker.SideInputTrackingIsmReader.overKeyComponents(SideInputTrackingIsmReader.java:104)
	at org.apache.beam.runners.dataflow.worker.IsmSideInputReader.findAndStartReaders(IsmSideInputReader.java:707)
	at org.apache.beam.runners.dataflow.worker.IsmSideInputReader.access$500(IsmSideInputReader.java:107)
...
```

https://github.com/apache/beam/blob/a3b3182e38fe6b2152f371d4232ddc5d22feed71/runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/IsmReaderImpl.java#L566

I can't completely follow the logic going on in `initializeForKeyedRead`, but it seems like if multiple threads race on computeIfAbsent, the losers will all throw an NPE?

### Issue Priority

Priority: 1

### Issue Component

Component: runner-dataflow

**Comment by lukecwik** [comment]
Fixed by https://github.com/apache/beam/pull/22111
