### ISSUE TITLE
Problem with manual compiled beam python package

### ISSUE THREAD

**Issue by wilsonwang371** [apache/beam#22149]
Hi,

I compiled apache beam package and installed it in my own environment.

However, when i tried to load apache_beam using
```python
import apache_beam
```

I saw the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/apache_beam/__init__.py", line 92, in <module>
    from apache_beam import coders
  File "/usr/local/lib/python3.9/site-packages/apache_beam/coders/__init__.py", line 17, in <module>
    from apache_beam.coders.coders import *
  File "/usr/local/lib/python3.9/site-packages/apache_beam/coders/coders.py", line 58, in <module>
    from apache_beam.coders import coder_impl
  File "/usr/local/lib/python3.9/site-packages/apache_beam/coders/coder_impl.py", line 62, in <module>
    from apache_beam.typehints.schemas import named_tuple_from_schema
  File "/usr/local/lib/python3.9/site-packages/apache_beam/typehints/schemas.py", line 72, in <module>
    from apache_beam.portability import common_urns
  File "/usr/local/lib/python3.9/site-packages/apache_beam/portability/common_urns.py", line 22, in <module>
    from .api import beam_runner_api_pb2_urns
ImportError: cannot import name 'beam_runner_api_pb2_urns' from 'apache_beam.portability.api' (unknown location)
```

Can someone help me out on this?

Thanks

**Comment by Abacn** [comment]
Sounds like protos are not generated. It should be executed automatically as part of the install: https://github.com/apache/beam/blob/b53b16f1fb41913b0e8bbe9d64d71b8e3ebfbbf6/sdks/python/setup.py#L164
If not could manually run `python gen_protos.py` at sdks/python folder before install.

**Comment by wilsonwang371** [comment]
I think I found the root cause. My python was 3.5 and it has problem compiling beam with this python version.
