### ISSUE TITLE
[Bug]: PR 17365 breaks BQ loads in some cases

### ISSUE THREAD

**Issue by steveniemitz** [apache/beam#22372]
### What happened?

In beam 2.39, this used to work:
```
BigQueryIO
   .write()
   .optimizedWrites()
   .to(OutputTable)
   .withAvroFormatFunction(abc)
   .withAvroSchemaFactory(xyz)
   .withCreateDisposition(CreateDisposition.CREATE_NEVER)
   .withWriteDisposition(WriteDisposition.WRITE_TRUNCATE))
```

but now throws an exception if you end up in MultiPartitionsWriteTables:

```
Caused by: java.lang.IllegalArgumentException: Unless create disposition is CREATE_NEVER, a schema must be specified, i.e. DynamicDestinations.getSchema() may not return null. However, create disposition is CREATE_IF_NEEDED, and org.apache.beam.sdk.io.gcp.bigquery.DynamicDestinationsHelpers$ConstantTableDestinations@52e95e1 returned null for destination tableSpec: <table>
	at org.apache.beam.sdk.util.Preconditions.checkArgumentNotNull(Preconditions.java:436)
	at org.apache.beam.sdk.io.gcp.bigquery.WriteTables$WriteTablesDoFn.processElement(WriteTables.java:207)
```

The reason seems like now, the create disposition is set to `CreateDisposition.CREATE_IF_NEEDED` in WriteTables no matter what the user sets it to.

cc @pabloem @MarcoRob 

### Issue Priority

Priority: 2

### Issue Component

Component: io-java-gcp

**Comment by steveniemitz** [comment]
Additionally, the new `UpdateSchemaDestination` breaks if the source format is set to avro due to it trying to load an empty file (a 0 length file is not a valid avro file).

**Comment by pabloem** [comment]
@johnjcasey @chamikaramj could you help look into this? I will be on vacation for a couple weeks from today.

**Comment by johnjcasey** [comment]
ack

**Comment by johnjcasey** [comment]
Agreed, this looks like that original PR changed how we load dynamic destinations for MultiPartitionsWrite tables. @MarcoRob can you take a look at this?

**Comment by MarcoRob** [comment]
> Agreed, this looks like that original PR changed how we load dynamic destinations for MultiPartitionsWrite tables. @MarcoRob can you take a look at this?

Sure, let me check, tks

**Comment by Abacn** [comment]
Hi, just curious about what is the current status of this bug? Is the working example fixed by #22390 ? @steveniemitz @MarcoRob

**Comment by ahmedabu98** [comment]
Looks like #22390 fixed the Avro source problem referred to in the second comment.

**Comment by ahmedabu98** [comment]
Looks like the problem is in this [deleted code block](https://github.com/apache/beam/pull/17365/files#diff-3edb3abd8909e7075e679e8b93420d4119858d6a9418b6ec10a204a592f062abL682-L692). The create disposition in WriteTables has always been `CreateDisposition.CREATE_IF_NEEDED`, because that's necessary when creating temp tables. However, in the case the schema isn't provided, this would cause the problem we're seeing here.

That code block used to handle this case by fetching the schema of the final destination table and using it as the schema for the temp tables. I think bringing that code back would solve this issue, unless there's a particular reason it was deleted @MarcoRob?

**Comment by MarcoRob** [comment]
> Looks like the problem is in this [deleted code block](https://github.com/apache/beam/pull/17365/files#diff-3edb3abd8909e7075e679e8b93420d4119858d6a9418b6ec10a204a592f062abL682-L692). The create disposition in WriteTables has always been `CreateDisposition.CREATE_IF_NEEDED`, because that's necessary when creating temp tables. However, in the case the schema isn't provided, this would cause the problem we're seeing here.
> 
> That code block used to handle this case by fetching the schema of the final destination table and using it as the schema for the temp tables. I think bringing that code back would solve this issue, unless there's a particular reason it was deleted @MarcoRob?

The change was part of a fix made due the following [ticket](https://issues.apache.org/jira/browse/BEAM-12482).
I am taking a look at this now to validate the issue and fix the bug. I will be updating the bug with more info.

**Comment by Abacn** [comment]
Hi @MarcoRob, what is the status of this issue? Is it safe to restore the deleted block?
