### ISSUE TITLE
[Bug]: Seed job failing to access LDAP

### ISSUE THREAD

**Issue by TheNeuralBit** [apache/beam#22676]
### What happened?

```
ERROR:root:Couldn't generate the list of committers
Traceback (most recent call last):
  File "main.py", line 70, in get_committers_github_usernames
    people = connection.search_s(
  File "/home/jenkins/jenkins-slave/workspace/beam_SeedJob/.test-infra/jenkins/committers_list_generator/ve3/lib/python3.8/site-packages/ldap/ldapobject.py", line 631, in search_s
    return self.search_ext_s(base,scope,filterstr,attrlist,attrsonly,None,None,timeout=self.timeout)
  File "/home/jenkins/jenkins-slave/workspace/beam_SeedJob/.test-infra/jenkins/committers_list_generator/ve3/lib/python3.8/site-packages/ldap/ldapobject.py", line 624, in search_ext_s
    msgid = self.search_ext(base,scope,filterstr,attrlist,attrsonly,serverctrls,clientctrls,timeout,sizelimit)
  File "/home/jenkins/jenkins-slave/workspace/beam_SeedJob/.test-infra/jenkins/committers_list_generator/ve3/lib/python3.8/site-packages/ldap/ldapobject.py", line 614, in search_ext
    return self._ldap_call(
  File "/home/jenkins/jenkins-slave/workspace/beam_SeedJob/.test-infra/jenkins/committers_list_generator/ve3/lib/python3.8/site-packages/ldap/ldapobject.py", line 128, in _ldap_call
    result = func(*args,**kwargs)
ldap.SERVER_DOWN: {'result': -1, 'desc': "Can't contact LDAP server", 'errno': 107, 'ctrls': [], 'info': 'Transport endpoint is not connected'}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 142, in <module>
    generate_groovy(args.output_dir, args.ldap_uris, args.cert_path)
  File "main.py", line 53, in generate_groovy
    github_usernames=get_committers_github_usernames(
  File "main.py", line 104, in get_committers_github_usernames
    raise CommittersGeneratorException("Could not fetch LDAP data") from e
CommittersGeneratorException: Could not fetch LDAP data
```

https://ci-beam.apache.org/job/beam_SeedJob/10122/

### Issue Priority

Priority: 1

### Issue Component

Component: infrastructure

**Comment by TheNeuralBit** [comment]
Attempted to address this in https://github.com/apache/beam/pull/22673 per advice from INFRA that the URIs had changed, but it had no effect.
