### ISSUE TITLE
[Bug]: Example sql_taxi.py not working with DirectRunner

### ISSUE THREAD

**Issue by Ture2019** [apache/beam#22709]
### What happened?

I am trying to run the example [https://github.com/apache/beam/blob/master/sdks/python/apache_beam/examples/sql_taxi.py](sdks/python/apache_beam/examples/sql_taxi.py) on my local machine. After some minor adaptations (I created a subscription to the "taxirides-realtime" topic and reference that instead of the topic itself), I expected it to work. But I get a NotImplementedError that indicates that SqlTransform is not implemented in DirectRunner.

The stacktrace I get:
```python
ERROR:apache_beam.runners.direct.executor:Exception at bundle <apache_beam.runners.direct.bundle_factory._Bundle object at 0x7f8809a860e0>, due to an exception.
 Traceback (most recent call last):
  File "/Users/ture.friese/miniconda3/envs/atldfs/lib/python3.10/site-packages/apache_beam/runners/direct/executor.py", line 370, in call
    self.attempt_call(
  File "/Users/ture.friese/miniconda3/envs/atldfs/lib/python3.10/site-packages/apache_beam/runners/direct/executor.py", line 400, in attempt_call
    evaluator = self._transform_evaluator_registry.get_evaluator(
  File "/Users/ture.friese/miniconda3/envs/atldfs/lib/python3.10/site-packages/apache_beam/runners/direct/transform_evaluator.py", line 135, in get_evaluator
    raise NotImplementedError(
NotImplementedError: Execution of [<class 'apache_beam.transforms.sql.SqlTransform'>] not implemented in runner <apache_beam.runners.direct.transform_evaluator.TransformEvaluatorRegistry object at 0x7f8809a092d0>.

ERROR:apache_beam.runners.direct.executor:Exception at bundle <apache_beam.runners.direct.bundle_factory._Bundle object at 0x7f8809a860e0>, due to an exception.
 Traceback (most recent call last):
  File "/Users/ture.friese/miniconda3/envs/atldfs/lib/python3.10/site-packages/apache_beam/runners/direct/executor.py", line 370, in call
    self.attempt_call(
  File "/Users/ture.friese/miniconda3/envs/atldfs/lib/python3.10/site-packages/apache_beam/runners/direct/executor.py", line 400, in attempt_call
    evaluator = self._transform_evaluator_registry.get_evaluator(
  File "/Users/ture.friese/miniconda3/envs/atldfs/lib/python3.10/site-packages/apache_beam/runners/direct/transform_evaluator.py", line 135, in get_evaluator
    raise NotImplementedError(
NotImplementedError: Execution of [<class 'apache_beam.transforms.sql.SqlTransform'>] not implemented in runner <apache_beam.runners.direct.transform_evaluator.TransformEvaluatorRegistry object at 0x7f8809a092d0>.

ERROR:apache_beam.runners.direct.executor:Exception at bundle <apache_beam.runners.direct.bundle_factory._Bundle object at 0x7f8809a860e0>, due to an exception.
 Traceback (most recent call last):
  File "/Users/ture.friese/miniconda3/envs/atldfs/lib/python3.10/site-packages/apache_beam/runners/direct/executor.py", line 370, in call
    self.attempt_call(
  File "/Users/ture.friese/miniconda3/envs/atldfs/lib/python3.10/site-packages/apache_beam/runners/direct/executor.py", line 400, in attempt_call
    evaluator = self._transform_evaluator_registry.get_evaluator(
  File "/Users/ture.friese/miniconda3/envs/atldfs/lib/python3.10/site-packages/apache_beam/runners/direct/transform_evaluator.py", line 135, in get_evaluator
    raise NotImplementedError(
NotImplementedError: Execution of [<class 'apache_beam.transforms.sql.SqlTransform'>] not implemented in runner <apache_beam.runners.direct.transform_evaluator.TransformEvaluatorRegistry object at 0x7f8809a092d0>.

ERROR:apache_beam.runners.direct.executor:Exception at bundle <apache_beam.runners.direct.bundle_factory._Bundle object at 0x7f8809a860e0>, due to an exception.
 Traceback (most recent call last):
  File "/Users/ture.friese/miniconda3/envs/atldfs/lib/python3.10/site-packages/apache_beam/runners/direct/executor.py", line 370, in call
    self.attempt_call(
  File "/Users/ture.friese/miniconda3/envs/atldfs/lib/python3.10/site-packages/apache_beam/runners/direct/executor.py", line 400, in attempt_call
    evaluator = self._transform_evaluator_registry.get_evaluator(
  File "/Users/ture.friese/miniconda3/envs/atldfs/lib/python3.10/site-packages/apache_beam/runners/direct/transform_evaluator.py", line 135, in get_evaluator
    raise NotImplementedError(
NotImplementedError: Execution of [<class 'apache_beam.transforms.sql.SqlTransform'>] not implemented in runner <apache_beam.runners.direct.transform_evaluator.TransformEvaluatorRegistry object at 0x7f8809a092d0>.

ERROR:apache_beam.runners.direct.executor:Giving up after 4 attempts.
WARNING:apache_beam.runners.direct.executor:A task failed with exception: Execution of [<class 'apache_beam.transforms.sql.SqlTransform'>] not implemented in runner <apache_beam.runners.direct.transform_evaluator.TransformEvaluatorRegistry object at 0x7f8809a092d0>.
Traceback (most recent call last):
  File "/Users/ture.friese/atl-dataflow-sql/sql_taxi.py", line 97, in <module>
    run(known_args.output_topic, pipeline_args)
  File "/Users/ture.friese/atl-dataflow-sql/sql_taxi.py", line 46, in run
    with beam.Pipeline(options=pipeline_options) as pipeline:
  File "/Users/ture.friese/miniconda3/envs/atldfs/lib/python3.10/site-packages/apache_beam/pipeline.py", line 598, in __exit__
    self.result.wait_until_finish()
  File "/Users/ture.friese/miniconda3/envs/atldfs/lib/python3.10/site-packages/apache_beam/runners/direct/direct_runner.py", line 588, in wait_until_finish
    self._executor.await_completion()
  File "/Users/ture.friese/miniconda3/envs/atldfs/lib/python3.10/site-packages/apache_beam/runners/direct/executor.py", line 432, in await_completion
    self._executor.await_completion()
  File "/Users/ture.friese/miniconda3/envs/atldfs/lib/python3.10/site-packages/apache_beam/runners/direct/executor.py", line 480, in await_completion
    raise update.exception
  File "/Users/ture.friese/miniconda3/envs/atldfs/lib/python3.10/site-packages/apache_beam/runners/direct/executor.py", line 370, in call
    self.attempt_call(
  File "/Users/ture.friese/miniconda3/envs/atldfs/lib/python3.10/site-packages/apache_beam/runners/direct/executor.py", line 400, in attempt_call
    evaluator = self._transform_evaluator_registry.get_evaluator(
  File "/Users/ture.friese/miniconda3/envs/atldfs/lib/python3.10/site-packages/apache_beam/runners/direct/transform_evaluator.py", line 135, in get_evaluator
    raise NotImplementedError(
NotImplementedError: Execution of [<class 'apache_beam.transforms.sql.SqlTransform'>] not implemented in runner <apache_beam.runners.direct.transform_evaluator.TransformEvaluatorRegistry object at 0x7f8809a092d0>.
```

### Issue Priority

Priority: 2

### Issue Component

Component: examples-python

**Comment by TheNeuralBit** [comment]
No this example was never tested with DirectRunner. I suspect the issue here is that the streaming direct runner is not portable, meaning it doesn't support cross-language transforms like SqlTransform.

**Comment by TheNeuralBit** [comment]
I tried running sql_taxi on FlinkRunner (`python -m apache_beam.examples.sql_taxi --output 'projects/foo/topics/bar' --runner FlinkRunner`) but got the following error:
```
INFO:apache_beam.utils.subprocess_server:java.lang.IllegalArgumentException: PCollectionNodes [PCollectionNode{id=ref_PCollection_PCollection_2, PCollection=unique_name: "19ReadFromPubSub/Read.None"                                  
INFO:apache_beam.utils.subprocess_server:coder_id: "ref_Coder_BytesCoder_3"                                                                                                                                                             
INFO:apache_beam.utils.subprocess_server:is_bounded: UNBOUNDED                                                                                                                                                                          
INFO:apache_beam.utils.subprocess_server:windowing_strategy_id: "ref_Windowing_Windowing_2"                                                                                                                                             
INFO:apache_beam.utils.subprocess_server:}] were consumed but never produced                                                                                                                                                            
INFO:apache_beam.utils.subprocess_server:       at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.base.Preconditions.checkArgument(Preconditions.java:440)                                                                    
INFO:apache_beam.utils.subprocess_server:       at org.apache.beam.runners.core.construction.graph.QueryablePipeline.buildNetwork(QueryablePipeline.java:234)                                                                           
INFO:apache_beam.utils.subprocess_server:       at org.apache.beam.runners.core.construction.graph.QueryablePipeline.<init>(QueryablePipeline.java:127)                                                                                 
INFO:apache_beam.utils.subprocess_server:       at org.apache.beam.runners.core.construction.graph.QueryablePipeline.forPrimitivesIn(QueryablePipeline.java:90)                                                                         
INFO:apache_beam.utils.subprocess_server:       at org.apache.beam.runners.core.construction.graph.GreedyPipelineFuser.<init>(GreedyPipelineFuser.java:70)                                                                              
INFO:apache_beam.utils.subprocess_server:       at org.apache.beam.runners.core.construction.graph.GreedyPipelineFuser.fuse(GreedyPipelineFuser.java:93)                                                                                
INFO:apache_beam.utils.subprocess_server:       at org.apache.beam.runners.flink.FlinkPipelineRunner.runPipelineWithTranslator(FlinkPipelineRunner.java:112)                                                                            
INFO:apache_beam.utils.subprocess_server:       at org.apache.beam.runners.flink.FlinkPipelineRunner.run(FlinkPipelineRunner.java:85)                                                                                                   INFO:apache_beam.utils.subprocess_server:       at org.apache.beam.runners.jobsubmission.JobInvocation.runPipeline(JobInvocation.java:86)                                                                                               
INFO:apache_beam.utils.subprocess_server:       at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java
:125)                                                                                                                                                                                                                                   
INFO:apache_beam.utils.subprocess_server:       at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)                                                            
INFO:apache_beam.utils.subprocess_server:       at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)                                        
INFO:apache_beam.utils.subprocess_server:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)                                                                                            
INFO:apache_beam.utils.subprocess_server:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)                                                                                            
INFO:apache_beam.utils.subprocess_server:       at java.base/java.lang.Thread.run(Thread.java:830)   
```

Maybe this has to do with using Dataflow built-in pubsub source? I'm pretty sure I've run this successfully on Flink before though. Any idea what's happening here @chamikaramj?

**Comment by TheNeuralBit** [comment]
Note I filed #22829 after looking into this. We should be testing this pipeline continuously.

**Comment by TheNeuralBit** [comment]
I tried sql_taxi on FlinkRunner on various released SDKs, it's failing even on 2.24.0, when it was first introduced. So I guess I was imagining running it with Flink. Note the error is different in 2.24.0 though:

```
INFO:apache_beam.utils.subprocess_server:b'[flink-runner-job-invoker] INFO org.apache.beam.runners.flink.FlinkPipelineRunner - Translating pipeline to Flink program.'                                                                  
INFO:apache_beam.runners.portability.portable_runner:Job state changed to STOPPED                                                                                                                                                       
INFO:apache_beam.runners.portability.portable_runner:Job state changed to STARTING                                                                                                                                                      
INFO:apache_beam.runners.portability.portable_runner:Job state changed to RUNNING                                                                                                                                                       
INFO:apache_beam.utils.subprocess_server:b'[flink-runner-job-invoker] ERROR org.apache.beam.runners.jobsubmission.JobInvocation - Error during job invocation BeamApp-bhulette-0823215552-533f1c9e_b699066c-ad87-4224-8dd4-f2a7da741b13.
'                                                                                                                                                                                                                                       
INFO:apache_beam.utils.subprocess_server:b'java.lang.IllegalArgumentException: GreedyPipelineFuser requires all root nodes to be runner-implemented beam:transform:impulse:v1 or beam:transform:read:v1 primitives, but transform ref_Ap
pliedPTransform_ReadFromPubSub/Read_3 executes in environment Optional[urn: "beam:env:external:v1"'                                                                                                                                     
INFO:apache_beam.utils.subprocess_server:b'payload: "\\n\\021\\n\\017localhost:46343"'                                                                                                                                                  
INFO:apache_beam.utils.subprocess_server:b'capabilities: "beam:coder:bytes:v1"'                                                                                                                                                         
INFO:apache_beam.utils.subprocess_server:b'capabilities: "beam:coder:string_utf8:v1"'                                                                                                                                                   
INFO:apache_beam.utils.subprocess_server:b'capabilities: "beam:coder:kv:v1"'                                                                                                                                                            
INFO:apache_beam.utils.subprocess_server:b'capabilities: "beam:coder:bool:v1"'                                                                                                                                                          
INFO:apache_beam.utils.subprocess_server:b'capabilities: "beam:coder:varint:v1"'
...
```

**Comment by chamikaramj** [comment]
Yeah, portable DirectRunner (Python) does not support streaming. So please try with Dataflow, Flink or Spark.

**Comment by TheNeuralBit** [comment]
> Yeah, portable DirectRunner (Python) does not support streaming. So please try with Dataflow, Flink or Spark.

Right, but I tried Flink and ran into the PubSubRead error(s) copied above.

**Comment by tvalentyn** [comment]
I think we might not have a working PubSub source w/ Flink..
