### ISSUE TITLE
[Task]: Add support for google-api-client:2.0.0+ to beam-runners-google-cloud-dataflow-java

### ISSUE THREAD

**Issue by jnsimon** [apache/beam#22843]
### What needs to happen?

Google libraries have started a switch to v2 of their API client library. When using org.apache.beam:beam-runners-google-cloud-dataflow-java with Google Cloud Storage ([com.google.cloud:google-cloud-storage:2.11.0+](https://search.maven.org/artifact/com.google.cloud/google-cloud-storage)) for example, it creates a dependency conflict. This will prevent updating Google Cloud libraries in a beam/dataflow project until beam-runners-google-cloud-dataflow-java works with the later google-api-client.

### Current google-api-client dependencies:

[org.apache.beam:beam-runners-google-cloud-dataflow-java:2.41.0](https://search.maven.org/artifact/org.apache.beam/beam-runners-google-cloud-dataflow-java/2.41.0/jar)
```
<groupId>com.google.api-client</groupId>
<artifactId>google-api-client</artifactId>
<version>1.32.1</version>
```

[com.google.cloud:google-cloud-storage:2.11.3](https://search.maven.org/artifact/com.google.cloud/google-cloud-storage/2.11.3/jar)
```
<groupId>com.google.api-client</groupId>
<artifactId>google-api-client</artifactId>
<version>2.0.0</version>
```

### Issue Priority

Priority: 2

### Issue Component

Component: runner-dataflow

**Comment by mkuthan** [comment]
You can't use any dependency with  google-api-client 2.x for direct runner as well, for example if you want to use PubsubIO you will get an error:

```
Caused by: java.lang.IllegalStateException: You are currently running with version 2.0.0 of google-api-client. You need at least version 1.31.1 of google-api-client to run version 1.32.1 of the Cloud Pub/Sub API library.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:534)
	at com.google.api.client.util.Preconditions.checkState(Preconditions.java:113)
	at com.google.api.services.pubsub.Pubsub.<clinit>(Pubsub.java:44)
	at com.google.api.services.pubsub.Pubsub$Builder.build(Pubsub.java:6940)
	at org.apache.beam.sdk.io.gcp.pubsub.PubsubJsonClient$PubsubJsonClientFactory.newClient(PubsubJsonClient.java:88)
	at org.apache.beam.sdk.io.gcp.pubsub.PubsubIO$Write$PubsubBoundedWriter.startBundle(PubsubIO.java:1285)
	at org.apache.beam.sdk.io.gcp.pubsub.PubsubIO$Write$PubsubBoundedWriter$DoFnInvoker.invokeStartBundle(Unknown Source)
	at org.apache.beam.repackaged.direct_java.runners.core.SimpleDoFnRunner.startBundle(SimpleDoFnRunner.java:174)
	at org.apache.beam.repackaged.direct_java.runners.core.SimplePushbackSideInputDoFnRunner.startBundle(SimplePushbackSideInputDoFnRunner.java:72)
	at org.apache.beam.runners.direct.ParDoEvaluator.<init>(ParDoEvaluator.java:223)
	at org.apache.beam.runners.direct.ParDoEvaluator.create(ParDoEvaluator.java:179)
	at org.apache.beam.runners.direct.ParDoEvaluator.create(ParDoEvaluator.java:171)
	at org.apache.beam.runners.direct.ParDoEvaluatorFactory.createParDoEvaluator(ParDoEvaluatorFactory.java:152)
	at org.apache.beam.runners.direct.ParDoEvaluatorFactory.createEvaluator(ParDoEvaluatorFactory.java:123)
	at org.apache.beam.runners.direct.ParDoEvaluatorFactory.forApplication(ParDoEvaluatorFactory.java:81)
	at org.apache.beam.runners.direct.TransformEvaluatorRegistry.forApplication(TransformEvaluatorRegistry.java:162)
	at org.apache.beam.runners.direct.DirectTransformExecutor.run(DirectTransformExecutor.java:122)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by kennknowles** [comment]
@kileys @apilloud this is at the intersection of java and dataflow runner; can you sort out an action plan? you might consult @suztomo

**Comment by suztomo** [comment]
I thought it's been fixed. Let me know if it's still the problem. Dependency tree will clarify what libraries still have old suffix such as "20220403-**1.32.1**".

**Comment by kennknowles** [comment]
Yes, to be clear I am just commenting and pinging people as I triage. I have not investigated. That would be great if this can be closed.
