### ISSUE TITLE
[Bug]: Python SDK installation cannot generate proto with protobuf 3.20.2

### ISSUE THREAD

**Issue by Abacn** [apache/beam#23227]
### What happened?

All  python suites (actions / Jenkins) fail with:

```
15:41:07 Processing ./target/.tox-py38-docs/.tmp/package/1/apache-beam-2.43.0.dev0.zip
15:41:07   Preparing metadata (setup.py): started
15:41:07   Preparing metadata (setup.py): finished with status 'error'
15:41:07   error: subprocess-exited-with-error
15:41:07   
15:41:07   × python setup.py egg_info did not run successfully.
15:41:07   │ exit code: 1
15:41:07   ╰─> [10 lines of output]
15:41:07       Traceback (most recent call last):
15:41:07         File "<string>", line 2, in <module>
15:41:07         File "<pip-setuptools-caller>", line 34, in <module>
15:41:07         File "/tmp/pip-req-build-rgi4y61h/setup.py", line 169, in <module>
15:41:07           generate_protos_first()
15:41:07         File "/tmp/pip-req-build-rgi4y61h/setup.py", line 139, in generate_protos_first
15:41:07           gen_protos.generate_proto_files()
15:41:07         File "/tmp/pip-req-build-rgi4y61h/gen_protos.py", line 476, in generate_proto_files
15:41:07           raise RuntimeError(error_msg)
15:41:07       RuntimeError: Not in apache git tree, unable to find proto definitions.
15:41:07       [end of output]
15:41:07   
15:41:07   note: This error originates from a subprocess, and is likely not a problem with pip.
15:41:07 error: metadata-generation-failed
15:41:07 
15:41:07 × Encountered error while generating package metadata.
15:41:07 ╰─> See above for output.

### Issue Priority

Priority: 1

### Issue Component

Component: test-failures

**Comment by tvalentyn** [comment]
Thanks, do we have a bug on protobuf side?

**Comment by Abacn** [comment]
> Thanks, do we have a bug on protobuf side?

Raised https://github.com/protocolbuffers/protobuf/issues/10564

**Comment by Abacn** [comment]
From protobuf 3.20.1 to 3.20.2 do not find something strange: https://github.com/protocolbuffers/protobuf/compare/v3.20.1...v3.20.2 the change is really minor, mostly fixing macos build.

From Beam side, looks like the build "python/build/apache-beam.tar.gz" sent to tox does not contain generated code anymore, which triggers this error.

**Comment by Abacn** [comment]
.take-issue

**Comment by Abacn** [comment]
.close-issue
