### ISSUE TITLE
[Bug]: beam_PerformanceTests_InfluxDbIO_IT Flaky > 50 % Fail 

### ISSUE THREAD

**Issue by Abacn** [apache/beam#23286]
### What happened?

This performance test has always been markedly flaky with timeout error:

```
21:17:33 org.apache.beam.sdk.io.influxdb.InfluxDbIOIT > testWriteAndReadWithMultipleMetric FAILED
21:17:33     org.influxdb.InfluxDBIOException: java.net.SocketTimeoutException: connect timed out
21:17:33         at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:836)
21:17:33         at org.influxdb.impl.InfluxDBImpl.executeQuery(InfluxDBImpl.java:819)
21:17:33         at org.influxdb.impl.InfluxDBImpl.query(InfluxDBImpl.java:554)
21:17:33         at org.apache.beam.sdk.io.influxdb.InfluxDbIOIT.initTest(InfluxDbIOIT.java:99)
21:17:33 
21:17:33         Caused by:
21:17:33         java.net.SocketTimeoutException: connect timed out
21:17:33             at java.net.PlainSocketImpl.socketConnect(Native Method)
21:17:33             at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
21:17:33             at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
21:17:33             at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
21:17:33             at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
21:17:33             at java.net.Socket.connect(Socket.java:607)
21:17:33             at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:119)
21:17:33             at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:283)
21:17:33             at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:195)
21:17:33             at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:249)
21:17:33             at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:108)
21:17:33             at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:76)
21:17:33             at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:245)
21:17:33             at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
21:17:33             at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
21:17:33             at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
21:17:33             at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
21:17:33             at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
21:17:33             at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
21:17:33             at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
21:17:33             at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
21:17:33             at org.influxdb.impl.BasicAuthInterceptor.intercept(BasicAuthInterceptor.java:22)
21:17:33             at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
21:17:33             at org.influxdb.impl.GzipRequestInterceptor.intercept(GzipRequestInterceptor.java:42)
21:17:33             at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
21:17:33             at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:152)
21:17:33             at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
21:17:33             at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
21:17:33             at okhttp3.internal.connection.RealCall.execute(RealCall.kt:148)
21:17:33             at retrofit2.OkHttpCall.execute(OkHttpCall.java:190)
21:17:33             at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:824)
21:17:33             ... 3 more
```
See https://ci-beam.apache.org/view/PerformanceTests/job/beam_PerformanceTests_InfluxDbIO_IT/

### Issue Priority

Priority: 2

### Issue Component

Component: test-failures

**Comment by Abacn** [comment]
Fix by #23286

**Comment by kileys** [comment]
Keeping it open for a bit longer to see if it keeps passing

**Comment by kileys** [comment]
Didn't get to it. I'll unassign myself

**Comment by kileys** [comment]
There's also a flaky test

```
org.apache.beam.sdk.io.influxdb.InfluxDbIOIT > testWriteAndReadWithSingleMetric FAILED
11:54:58     java.lang.AssertionError: Count All/Flatten.PCollections.out: 
11:54:58     Expected: <2000L>
11:54:58          but: was <1999L>

**Comment by Abacn** [comment]
last 5 jons all succeeded
