### ISSUE TITLE
[Bug] Runtime Error: invalid memory address or nil pointer dereference for newJarGetter() 

### ISSUE THREAD

**Issue by euannliu** [apache/beam#23647]
I'm getting an error initializing Apache Beam for my Go service deployed to kubernetes. The error in question is:
```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xb94949]

goroutine 1 [running]:
github.com/apache/beam/sdks/v2/go/pkg/beam/core/runtime/xlangx/expansionx.newJarGetter()
	/go/src/groups/vendor/github.com/apache/beam/sdks/v2/go/pkg/beam/core/runtime/xlangx/expansionx/download.go:50 +0x29
github.com/apache/beam/sdks/v2/go/pkg/beam/core/runtime/xlangx/expansionx.init()
	/go/src/groups/vendor/github.com/apache/beam/sdks/v2/go/pkg/beam/core/runtime/xlangx/expansionx/download.go:40 +0x17
```
	
Looking at the code, it seems like the culprit is `usr` in
 ```
	cacheDir := filepath.Join(usr.HomeDir, jarCache[2:])
```
I am wondering if there is a potential bug or problem with `usr, _ := user.Current()` in the line before.

**Comment by bnewcomer** [comment]
I just hit this issue trying to run a pipeline in Dataflow and trying to run locally with the PortableRunner using a custom docker image. I resolved it by ensuring there was a user set before launching beam in the Dockerfile. I'm guessing that call to `usr.HomeDir` is the source of the error if there is no user owning the process that launches beam (or if the user has no home directory)
```
RUN useradd -u 1000 -d <some-path-to-a-home-dir> <user-name>
USER 1000
ENTRYPOINT ["/opt/apache/beam/boot"]
```

I still think there should be some error handling, this doesn't seem like it should be a fatal error.
