### ISSUE TITLE
beam_PostCommit_Py_ValCont failing

### ISSUE THREAD

**Issue by ryanthompson591** [apache/beam#23940]
https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/

An initial look makes it seem like this might be flaky, but very flaky with many failures in a row.

[Run 9889](https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/9889/) has 6 failing tests.
[Run 9887](https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/9887/) Has only one failing test.
[Run 9885] (https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/9885/) Has a different failing test.

**Comment by ryanthompson591** [comment]
.add_label P1
.add_label bug
.add_label build

**Comment by ryanthompson591** [comment]
.add-labels P1,bug,build

**Comment by ryanthompson591** [comment]
.take-issue

**Comment by ryanthompson591** [comment]
These tests are failing with a stack trace in the java dataflow worker.

This went green in[9918](https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/9918/)

The only change that might have fixed this is a [dataflow config change](https://github.com/apache/beam/commit/95c121b2549d3f8fda7668e3759b8991b55d9865)

Example output:
```
12:34:09 FAILED apache_beam/runners/dataflow/dataflow_exercise_metrics_pipeline_test.py::ExerciseMetricsPipelineTest::test_metrics_fnapi_it - apache_beam.runners.dataflow.dataflow_runner.DataflowRuntimeException: Dataflow pipeline failed. State: FAILED, Error:
12:34:09 java.lang.RuntimeException: java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
12:34:09 	at org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowsParDoFn$1.output(GroupAlsoByWindowsParDoFn.java:187)
12:34:09 	at org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowFnRunner$1.outputWindowedValue(GroupAlsoByWindowFnRunner.java:108)
12:34:09 	at org.apache.beam.runners.dataflow.worker.util.BatchGroupAlsoByWindowViaIteratorsFn.processElement(BatchGroupAlsoByWindowViaIteratorsFn.java:128)
12:34:09 	at org.apache.beam.runners.dataflow.worker.util.BatchGroupAlsoByWindowViaIteratorsFn.processElement(BatchGroupAlsoByWindowViaIteratorsFn.java:56)
12:34:09 	at org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowFnRunner.invokeProcessElement(GroupAlsoByWindowFnRunner.java:121)
12:34:09 	at org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowFnRunner.processElement(GroupAlsoByWindowFnRunner.java:73)
12:34:09 	at org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowsParDoFn.processElement(GroupAlsoByWindowsParDoFn.java:117)
12:34:09 	at org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:44)
12:34:09 	at org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:49)
12:34:09 	at org.apache.beam.runners.dataflow.worker.util.common.worker.ReadOperation.runReadLoop(ReadOperation.java:218)
12:34:09 	at org.apache.beam.runners.dataflow.worker.util.common.worker.ReadOperation.start(ReadOperation.java:169)
12:34:09 	at org.apache.beam.runners.dataflow.worker.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:83)
12:34:09 	at org.apache.beam.runners.dataflow.worker.fn.control.BeamFnMapTaskExecutor.execute(BeamFnMapTaskExecutor.java:127)
12:34:09 	at org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.executeWork(BatchDataflowWorker.java:420)
12:34:09 	at org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.doWork(BatchDataflowWorker.java:389)
12:34:09 	at org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.getAndPerformWork(BatchDataflowWorker.java:314)
12:34:09 	at org.apache.beam.runners.dataflow.worker.DataflowRunnerHarness.start(DataflowRunnerHarness.java:239)
12:34:09 	at org.apache.beam.runners.dataflow.worker.DataflowRunnerHarness.main(DataflowRunnerHarness.java:142)
```

**Comment by ryanthompson591** [comment]
This is fixed, this is not the dataflow config change (since that only effected the vendored version of grpc). It is also not due to changes in the java runner (in fact the java runner should not have been called since that is runner_v1 and we should use runner_v2 by default).

This fixed due to a recent fixes in jenkins servers.

**Comment by ryanthompson591** [comment]
Just a followup task to this issue 
https://github.com/apache/beam/issues/24107
