### ISSUE TITLE
[Bug]: WriteToParquet to Azure Blob Storage not working in Spark

### ISSUE THREAD

**Issue by cozos** [apache/beam#24303]
### What happened?

I am running Apache Beam on Spark. My code:
```py
from apache_beam import Create, Map, Pipeline
from apache_beam.io.parquetio import  WriteToParquet
from apache_beam.options.pipeline_options import PipelineOptions

options = PipelineOptions(
    [
        "--runner",  "SparkRunner",
        "--spark_version", "3",
    ]
)

with Pipeline(options=options) as pipeline:
    (
        pipeline
        | Create(list(range(1000)))
        | Map(lambda x: {"name": str(x), "age": x})
        | WriteToParquet(
            "azfs://mystorageaccount/mycontainer/mypath/",
            pyarrow.schema([("name", pyarrow.binary()), ("age", pyarrow.int64())]),
            file_name_suffix=".parquet",
        )
    )
```

The error:
```
Traceback (most recent call last):
  File "apache_beam/runners/common.py", line 1198, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 718, in apache_beam.runners.common.PerWindowInvoker.invoke_process
  File "apache_beam/runners/common.py", line 841, in apache_beam.runners.common.PerWindowInvoker._invoke_process_per_window
  File "apache_beam/runners/common.py", line 1334, in apache_beam.runners.common._OutputProcessor.process_outputs
  File "/databricks/python3/lib/python3.7/site-packages/apache_beam/io/iobase.py", line 1229, in <genexpr>
    window.TimestampedValue(v, timestamp.MAX_TIMESTAMP) for v in outputs)
  File "/databricks/python3/lib/python3.7/site-packages/apache_beam/io/filebasedsink.py", line 279, in finalize_write
    self._check_state_for_finalize_write(writer_results, num_shards))
  File "/databricks/python3/lib/python3.7/site-packages/apache_beam/io/filebasedsink.py", line 263, in _check_state_for_finalize_write
    FileSystems.checksum(src) == FileSystems.checksum(dst)):
  File "/databricks/python3/lib/python3.7/site-packages/apache_beam/io/filesystems.py", line 324, in checksum
    return filesystem.checksum(path)
  File "/databricks/python3/lib/python3.7/site-packages/apache_beam/io/azure/blobstoragefilesystem.py", line 277, in checksum
    raise BeamIOError("Checksum operation failed", {path, e})
apache_beam.io.filesystem.BeamIOError: Checksum operation failed with exceptions {'azfs://mystorageaccount/mycontainer/mypath/beam-temp--9a346cf260e611ed84fc00163eafa21b/59821b95-11a8-43fd-9117-f9b8466f46fd..parquet', BlobStorageError('The specified blob does not exist.', 404)}
```

This error is only happening when I have speculative execution enabled. When I disable speculative execution, the problem doesn't happen. It seems to me like `finalize_write` is not idempotent here, and is deleting my temp files.

### Issue Priority

Priority: 2

### Issue Component

Component: io-py-parquet

**Comment by kennknowles** [comment]
@chamikaramj is this the known issue we have seen? It was in Java though, and this is Python?

**Comment by chamikaramj** [comment]
Seems like "speculative execution" means backup workers ? It's very possible that we have not tested this connector for such workloads. So potentially there's a race condition here when the same task is run twice.

**Comment by chamikaramj** [comment]
And looking at the failure, it doesn't seem to be specific to Parquet so probably affect other file-based I/O as well.

cc: @johnjcasey

**Comment by cozos** [comment]
Speculative execution means:

> Apache Spark has the 'speculative execution' feature to handle the slow tasks in a stage due to environment issues like slow network, disk etc. If one task is running slowly in a stage, Spark driver can launch a speculation task for it on a different host

In Beam terms, I think this means that there are two SDK Harnesses writing the same bundle to the same file.

> And looking at the failure, it doesn't seem to be specific to Parquet so probably affect other file-based I/O as well.

Yes this doesn't seem Parquet specific so could affect other file formats.

**Comment by cozos** [comment]
Something that caught my attention for this is the `blobstorageio.py` implementation of `checksum`, which uses the `etag` of the file: https://github.com/apache/beam/blob/d15913b289158bea685197db7752409886217441/sdks/python/apache_beam/io/azure/blobstorageio.py#L379

The purpose of the `checksum` method as I understand it is: "when committing a file from the temporary path to the final path, check if a file already exists in the final path. If it already exists, compare the checksum of the temporary file to the existing file in the final path, and if they are the same then another worker has already written that data and we are good to go. If they are different then something has gone wrong (implies possible dataloss) so we should abort". 

However, the `etag` says nothing about the contents of the file - from https://learn.microsoft.com/en-us/rest/api/storageservices/get-blob-properties#response-headers:

```
The ETag contains a value that you can use to perform operations conditionally.
```

(i.e. for optimistic concurrency)


It seems to me like the `Content-MD5` header is what we actually want for the `checksum()` implementation, as [it is](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.blobproperties.contentmd5?view=azure-dotnet):

```
A string containing the blob's content-MD5 hash.
```

It is unclear if the ETag is actually a digest of the blob data.

**Comment by chamikaramj** [comment]
Yes, seems like we use Content MD5 Header instead of ETag. Can you send a PR (sounds like a quick fix) ?

**Comment by cozos** [comment]
I can, but I don't have the bandwidth to do any more in-depth validation. Would the CI tests be sufficient here?
