### ISSUE TITLE
[Bug] "Bad type on operand stack" when using the Apache Beam Maven WordCount archetype on a Kubernetes cluster with the Spark operator

### ISSUE THREAD

**Issue by shroffru** [apache/beam#25165]
Attempting to run the Apache Beam Maven WordCount archetype on a Kubernetes cluster with the Spark operator. I have not changed the pom of the project, but I keep on running into the exception when I use the `SparkRunner`

Spark version: 3.1.1
Apache Beam version:  2.44.0

```
Exception in thread "main" java.lang.RuntimeException: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/google/api/ClientProto.registerAllExtensions(Lcom/google/protobuf/ExtensionRegistryLite;)V @4: invokevirtual
  Reason:
    Type 'com/google/protobuf/GeneratedMessage$GeneratedExtension' (current frame, stack[1]) is not assignable to 'com/google/protobuf/ExtensionLite'
  Current Frame:
    bci: @4
    flags: { }
    locals: { 'com/google/protobuf/ExtensionRegistryLite' }
    stack: { 'com/google/protobuf/ExtensionRegistryLite', 'com/google/protobuf/GeneratedMessage$GeneratedExtension' }
  Bytecode:
    0000000: 2ab2 0002 b600 032a b200 04b6 0003 2ab2
    0000010: 0005 b600 03b1                         

	at org.apache.beam.runners.spark.SparkPipelineResult.runtimeExceptionFrom(SparkPipelineResult.java:60)
	at org.apache.beam.runners.spark.SparkPipelineResult.beamExceptionFrom(SparkPipelineResult.java:77)
	at org.apache.beam.runners.spark.SparkPipelineResult.waitUntilFinish(SparkPipelineResult.java:104)
	at org.apache.beam.runners.spark.SparkPipelineResult.waitUntilFinish(SparkPipelineResult.java:92)
```

This is what my deployment yaml looks like

```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-beam
  namespace: spark-k8s
spec:
    type: Java
    mode: cluster
    image: "gcr.io/spark-operator/spark:v3.1.1"
    imagePullPolicy: Always
    
    mainClass: com.example.WordCount
    mainApplicationFile: "local:///home/artifacts/wordcount-bundled-0.1.jar"
    arguments: ["--runner=SparkRunner", "--output=gs://spark-beam/output/"]
    
    sparkVersion: "3.1.1"
    restartPolicy:
      type: Never

    volumes: ...
```

This is what my pom looks like - https://github.com/apache/beam/blob/master/sdks/java/maven-archetypes/examples/src/main/resources/archetype-resources/pom.xml

So it seems that the beam pipeline is using an incorrect version of protobuf-java.

**Comment by shroffru** [comment]
I just noticed the pom.xml link does not have version numbers on it, let me push it to a repo and share that here.

**Comment by shroffru** [comment]
https://github.com/shroffrushabh/WordCount/blob/main/pom.xml 

That's what the proto looks like
