### ISSUE TITLE
[Bug]: AttributeError: 'HttpError' object has no attribute 'message' GcsIO

### ISSUE THREAD

**Issue by janowskijak** [apache/beam#25911]
### What happened?

Beam version: 2.45.0

While performing write operations using the DoFn below,  the GcsIO connector returns the following traceback:

```
Error message from worker: generic::unknown: Traceback (most recent call last):
  File "apache_beam/runners/common.py", line 1417, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 624, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "/project/pipelines/nesg_backup_splitter/utilities/writers.py", line 68, in process
    with self.gcs.open(f"{split_file_name}", "wb") as f:
  File "/usr/local/lib/python3.10/site-packages/apache_beam/io/filesystemio.py", line 215, in close
    self._uploader.finish()
  File "/usr/local/lib/python3.10/site-packages/apache_beam/io/gcp/gcsio.py", line 829, in finish
    self._upload_thread.last_error.message)  # pylint: disable=raising-bad-type
AttributeError: 'HttpError' object has no attribute 'message'
```

The problem appears to be transient and stopped when HttpErrors stopped occurring.  

```
class WriteFilesToGCS(DoFn):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def start_bundle(self):
        self.gcs = gcsio.GcsIO()

    def finish_bundle(self):
        del self.gcs

    def process(self, element: Tuple[str, str], *args, **kwargs):
        file_name, file_content

        # Write the file to GCS
        with self.gcs.open(file_name, "wb") as f:
            with GzipFile(fileobj=f, mode="wb") as gz:
                gz.write(file_content.encode("utf-8"))
```

### Issue Priority

Priority: 3 (minor)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [X] Component: Google Cloud Dataflow Runner

**Comment by rizenfrmtheashes** [comment]
As a note, This bug pops up in WriteToBigQuery with method FILE_LOADS

```
Error message from worker: generic::unknown: Traceback (most recent call last):
  File "apache_beam/runners/common.py", line 1459, in apache_beam.runners.common.DoFnRunner._invoke_bundle_method
  File "apache_beam/runners/common.py", line 562, in apache_beam.runners.common.DoFnInvoker.invoke_finish_bundle
  File "apache_beam/runners/common.py", line 567, in apache_beam.runners.common.DoFnInvoker.invoke_finish_bundle
  File "apache_beam/runners/common.py", line 1731, in apache_beam.runners.common._OutputHandler.finish_bundle_outputs
  File "/opt/apache/beam-venv/beam-venv-worker-sdk-0-1/lib/python3.11/site-packages/apache_beam/io/gcp/bigquery_file_loads.py", line 276, in finish_bundle
    writer.close()
  File "/opt/apache/beam-venv/beam-venv-worker-sdk-0-1/lib/python3.11/site-packages/apache_beam/io/gcp/bigquery_tools.py", line 1400, in close
    self._file_handle.close()
  File "/opt/apache/beam-venv/beam-venv-worker-sdk-0-1/lib/python3.11/site-packages/apache_beam/io/filesystemio.py", line 215, in close
    self._uploader.finish()
  File "/opt/apache/beam-venv/beam-venv-worker-sdk-0-1/lib/python3.11/site-packages/apache_beam/io/gcp/gcsio.py", line 829, in finish
    self._upload_thread.last_error.message)  # pylint: disable=raising-bad-type
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'HttpError' object has no attribute 'message'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/apache/beam-venv/beam-venv-worker-sdk-0-1/lib/python3.11/site-packages/apache_beam/runners/worker/sdk_worker.py", line 295, in _execute
    response = task()
               ^^^^^^
  File "/opt/apache/beam-venv/beam-venv-worker-sdk-0-1/lib/python3.11/site-packages/apache_beam/runners/worker/sdk_worker.py", line 370, in <lambda>
    lambda: self.create_worker().do_instruction(request), request)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/apache/beam-venv/beam-venv-worker-sdk-0-1/lib/python3.11/site-packages/apache_beam/runners/worker/sdk_worker.py", line 629, in do_instruction
    return getattr(self, request_type)(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/apache/beam-venv/beam-venv-worker-sdk-0-1/lib/python3.11/site-packages/apache_beam/runners/worker/sdk_worker.py", line 667, in process_bundle
    bundle_processor.process_bundle(instruction_id))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/apache/beam-venv/beam-venv-worker-sdk-0-1/lib/python3.11/site-packages/apache_beam/runners/worker/bundle_processor.py", line 1067, in process_bundle
    op.finish()
  File "apache_beam/runners/worker/operations.py", line 939, in apache_beam.runners.worker.operations.DoOperation.finish
  File "apache_beam/runners/worker/operations.py", line 942, in apache_beam.runners.worker.operations.DoOperation.finish
  File "apache_beam/runners/worker/operations.py", line 943, in apache_beam.runners.worker.operations.DoOperation.finish
  File "apache_beam/runners/common.py", line 1480, in apache_beam.runners.common.DoFnRunner.finish
  File "apache_beam/runners/common.py", line 1461, in apache_beam.runners.common.DoFnRunner._invoke_bundle_method
  File "apache_beam/runners/common.py", line 1508, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 1459, in apache_beam.runners.common.DoFnRunner._invoke_bundle_method
  File "apache_beam/runners/common.py", line 562, in apache_beam.runners.common.DoFnInvoker.invoke_finish_bundle
  File "apache_beam/runners/common.py", line 567, in apache_beam.runners.common.DoFnInvoker.invoke_finish_bundle
  File "apache_beam/runners/common.py", line 1731, in apache_beam.runners.common._OutputHandler.finish_bundle_outputs
  File "/opt/apache/beam-venv/beam-venv-worker-sdk-0-1/lib/python3.11/site-packages/apache_beam/io/gcp/bigquery_file_loads.py", line 276, in finish_bundle
    writer.close()
  File "/opt/apache/beam-venv/beam-venv-worker-sdk-0-1/lib/python3.11/site-packages/apache_beam/io/gcp/bigquery_tools.py", line 1400, in close
    self._file_handle.close()
  File "/opt/apache/beam-venv/beam-venv-worker-sdk-0-1/lib/python3.11/site-packages/apache_beam/io/filesystemio.py", line 215, in close
    self._uploader.finish()
  File "/opt/apache/beam-venv/beam-venv-worker-sdk-0-1/lib/python3.11/site-packages/apache_beam/io/gcp/gcsio.py", line 829, in finish
    self._upload_thread.last_error.message)  # pylint: disable=raising-bad-type
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'HttpError' object has no attribute 'message' [while running 'Write BQ Sessioned Events to BigQuery/BigQueryBatchFileLoads/ParDo(WriteRecordsToFile)/ParDo(WriteRecordsToFile)-ptransform-105']
```

**Comment by CharlesHolbrow** [comment]
I've been getting these too. It appears to be a bug, and the cause looks pretty simple. However, it's inconvenient, because when an HttpError arises while uploading to GCS, the bug makes it impossible to see the underlying HttpError message. 

Here's where beam expects a `.message` property, but looking at the `apitools` `HttpError` class shows that the class does not have a `.message` property. Instead, its `__str__` property is intended to be used to make a human readable error. 

https://github.com/apache/beam/blob/7ce2d00464f90723c25531fcb08643559a7b3257/sdks/python/apache_beam/io/gcp/gcsio.py#L830

Looks like this is resolved in 62a8087b98d9a885c9c11b30e8767a9e2b293459
