### ISSUE TITLE
[Failing Test]: beam_PreCommit_Java_PVR_Flink_Batch stuck

### ISSUE THREAD

**Issue by Abacn** [apache/beam#26301]
### What happened?

There is possibility that this precommit stuck and timing out after 4 hour. It is not obvious which test is timing out. Having downloaded the raw log in the jenkins node, it is found that the stucking test is `CombineTest.basicTests#testCombinePerKeyLambda` at least for https://ci-beam.apache.org/job/beam_PreCommit_Java_PVR_Flink_Batch_Cron/9111/

### Issue Failure

Failure: Test is flaky

### Issue Priority

Priority: 2 (backlog / disabled test but we think the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [X] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
The sampler continuously emitting warnings indicating job stuck:
```
[pool-258-thread-2] WARN org.apache.beam.fn.harness.control.ExecutionStateSampler - Operation ongoing in bundle 12 for at least 01h00m51s without outputting or completing:
at sun.misc.Unsafe.park(Native Method)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
at org.apache.beam.sdk.fn.CancellableQueue.take(CancellableQueue.java:94)
at org.apache.beam.sdk.fn.data.BeamFnDataInboundObserver.awaitCompletion(BeamFnDataInboundObserver.java:122)
at org.apache.beam.fn.harness.control.ProcessBundleHandler.processBundle(ProcessBundleHandler.java:550)
at org.apache.beam.fn.harness.FnHarness$$Lambda$1264/2051412990.apply(Unknown Source)
at org.apache.beam.fn.harness.control.BeamFnControlClient.delegateOnInstructionRequestType(BeamFnControlClient.java:151)
at org.apache.beam.fn.harness.control.BeamFnControlClient$InboundObserver.lambda$onNext$0(BeamFnControlClient.java:116)
at org.apache.beam.fn.harness.control.BeamFnControlClient$InboundObserver$$Lambda$1391/138607428.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at org.apache.beam.sdk.util.UnboundedScheduledExecutorService$ScheduledFutureTask.run(UnboundedScheduledExecutorService.java:163)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)
```
However this code path is generic and not help much for root cause
