### ISSUE TITLE
[Bug]: beam_PostCommit_Java permared DLPTextOperationsIT.inspectsText failing

### ISSUE THREAD

**Issue by Abacn** [apache/beam#26585]
### What happened?

Error message:

```
Stacktrace
java.lang.AssertionError: DLPInspectText/DLPInspect/ParMultiDo(InspectData).output: null
	at org.apache.beam.sdk.testing.PAssert$PAssertionSite.capture(PAssert.java:175)
	at org.apache.beam.sdk.testing.PAssert.that(PAssert.java:460)
	at org.apache.beam.sdk.testing.PAssert.that(PAssert.java:452)
	at org.apache.beam.sdk.extensions.ml.DLPTextOperationsIT.inspectsText(DLPTextOperationsIT.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        ...
Caused by: java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.apache.beam.sdk.extensions.ml.DLPTextOperationsIT$VerifyInspectionResult.apply(DLPTextOperationsIT.java:121)
	at org.apache.beam.sdk.extensions.ml.DLPTextOperationsIT$VerifyInspectionResult.apply(DLPTextOperationsIT.java:109)
        ....
org.apache.beam.repackaged.direct_java.runners.core.SimplePushbackSideInputDoFnRunner.processElementInReadyWindows(SimplePushbackSideInputDoFnRunner.java:79)
	at org.apache.beam.runners.direct.ParDoEvaluator.processElement(ParDoEvaluator.java:244)
	at org.apache.beam.runners.direct.DoFnLifecycleManagerRemovingTransformEvaluator.processElement(DoFnLifecycleManagerRemovingTransformEvaluator.java:54)
	at org.apache.beam.runners.direct.DirectTransformExecutor.processElements(DirectTransformExecutor.java:165)
	at org.apache.beam.runners.direct.DirectTransformExecutor.run(DirectTransformExecutor.java:129)
```

It start failing on May 4, 5 PM GMT, but then at May 5, 5 PM GMT there is a successful run, then permared since then. No obvious code change at that time. Is it some breaking change at gcp side?

<img width="346" alt="image" src="https://user-images.githubusercontent.com/8010435/236847651-1ead4732-a3bd-489a-ab8b-d03ddf405284.png">

### Issue Priority

Priority: 1 (data loss / total loss of function)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
Checked that also failing on release-2.47.0 branch for the same exception. So that this is indeed due to gcp service change

**Comment by Abacn** [comment]
It turns out that the response now contains additional information:

```
name: "EMAIL_ADDRESS"
3: {
  1: 20
}

while the expected value is 
```
name: "EMAIL_ADDRESS"
```
