### ISSUE TITLE
[Failing Test]: Java ValidateRunner test ViewTest.testTriggeredLatestSingleton flaky/permared on multiple runners

### ISSUE THREAD

**Issue by Abacn** [apache/beam#26706]
### What happened?

Newly added test `org.apache.beam.sdk.transforms.ViewTest.testTriggeredLatestSingleton` in #25940 is failing on several validate runner postcommits:

https://ci-beam.apache.org/view/PostCommit/job/beam_PostCommit_Java_VR_Dataflow_V2_Streaming/3502/testReport/

https://ci-beam.apache.org/view/PostCommit/job/beam_PostCommit_Java_PVR_Flink_Streaming/

https://ci-beam.apache.org/view/PostCommit/job/beam_PostCommit_Java_ValidatesRunner_Flink/

highly flaky (~80%)

https://ci-beam.apache.org/view/PostCommit/job/beam_PostCommit_Java_PVR_Samza/ permared:

```
java.lang.RuntimeException: The Runner experienced the following error during execution:
java.lang.UnsupportedOperationException: class org.apache.beam.runners.samza.SamzaRunner currently only supports event time or processing time but get SYNCHRONIZED_PROCESSING_TIME
	at org.apache.beam.runners.portability.JobServicePipelineResult.propagateErrors(JobServicePipelineResult.java:176)
	at org.apache.beam.runners.portability.JobServicePipelineResult.waitUntilFinish(JobServicePipelineResult.java:117)
	at org.apache.beam.runners.portability.testing.TestPortableRunner.run(TestPortableRunner.java:81)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:321)
```

https://ci-beam.apache.org/view/PostCommit/job/beam_PostCommit_Java_ValidatesRunner_ULR/ permared:

```
java.lang.RuntimeException: The Runner experienced the following error during execution:
Traceback (most recent call last):
  File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Java_ValidatesRunner_ULR/src/sdks/python/apache_beam/runners/portability/local_job_service.py", line 296, in _run_job
    self.result = self._invoke_runner()
  File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Java_ValidatesRunner_ULR/src/sdks/python/apache_beam/runners/portability/local_job_service.py", line 318, in _invoke_runner
    return fn_runner.FnApiRunner(
  File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Java_ValidatesRunner_ULR/src/sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 224, in run_via_runner_api
    return self.run_stages(stage_context, stages)
  File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Java_ValidatesRunner_ULR/src/sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 455, in run_stages
    bundle_results = self._execute_bundle(
  File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Java_ValidatesRunner_ULR/src/sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 783, in _execute_bundle
    self._run_bundle(
  File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Java_ValidatesRunner_ULR/src/sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 1012, in _run_bundle
    result, splits = bundle_manager.process_bundle(
  File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Java_ValidatesRunner_ULR/src/sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 1380, in process_bundle
    self.bundle_context_manager.get_buffer(
  File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Java_ValidatesRunner_ULR/src/sdks/python/apache_beam/runners/portability/fn_api_runner/execution.py", line 1172, in get_buffer
    self.execution_context.pipeline_context.windowing_strategies[
  File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Java_ValidatesRunner_ULR/src/sdks/python/apache_beam/runners/pipeline_context.py", line 163, in __getitem__
    return self.get_by_id(id)
  File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Java_ValidatesRunner_ULR/src/sdks/python/apache_beam/runners/pipeline_context.py", line 114, in get_by_id
    self._id_to_obj[id] = self._obj_type.from_runner_api(
  File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Java_ValidatesRunner_ULR/src/sdks/python/apache_beam/transforms/core.py", line 3403, in from_runner_api
    triggerfn=TriggerFn.from_runner_api(proto.trigger, context),
  File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Java_ValidatesRunner_ULR/src/sdks/python/apache_beam/transforms/trigger.py", line 304, in from_runner_api
    return {
  File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Java_ValidatesRunner_ULR/src/sdks/python/apache_beam/transforms/trigger.py", line 737, in from_runner_api
    TriggerFn.from_runner_api(proto.repeat.subtrigger, context))
  File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Java_ValidatesRunner_ULR/src/sdks/python/apache_beam/transforms/trigger.py", line 304, in from_runner_api
    return {
  File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Java_ValidatesRunner_ULR/src/sdks/python/apache_beam/transforms/trigger.py", line 413, in from_runner_api
    proto.after_processing_time.timestamp_transforms[0].delay.
IndexError: list index out of range
```

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [X] Component: Flink Runner
- [X] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [X] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
Fixed by #26707
