### ISSUE TITLE
[Bug] Module `sdf_direct_runner` calls `DoFnInvoker.create_invoker` with wrong parameter

### ISSUE THREAD

**Issue by hoangvu-ct** [apache/beam#26836]
### What happened?

The module [sdf_direct_runner](https://github.com/apache/beam/blob/c31243ece6a78e46ea2a25147643143d0ab20d93/sdks/python/apache_beam/runners/direct/sdf_direct_runner.py) calls `DoFnInvoker.create_invoker` with `output_processor` param:
https://github.com/apache/beam/blob/c31243ece6a78e46ea2a25147643143d0ab20d93/sdks/python/apache_beam/runners/direct/sdf_direct_runner.py#L121-L125
... but the actual function signature takes `output_handler` instead:
https://github.com/apache/beam/blob/c31243ece6a78e46ea2a25147643143d0ab20d93/sdks/python/apache_beam/runners/common.py#L444-L453

This makes the pipeline cannot be build when using `beam.GroupIntoBatches`.

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by tvalentyn** [comment]
Thanks for reporting. Would you be open to contributing a PR (and ideally a test that exercises it) ?

**Comment by hoangvu-ct** [comment]
> Thanks for reporting. Would you be open to contributing a PR (and ideally a test that exercises it) ?

@tvalentyn I'm afraid not. I've tried to correct the param names in `sdf_direct_runner.py`, but it led to other errors that I have no clues. I have just started to use Apache Beam and have not familiar with it, so I think it'll take too long to fix this on my own.

**Comment by liferoad** [comment]
.take-issue

**Comment by liferoad** [comment]
@hoangvu-ct, can you share one test case?

I do not have the problem to use `beam.GroupIntoBatches`:
```
import apache_beam as beam
from apache_beam.runners.interactive.interactive_runner import InteractiveRunner

with beam.Pipeline(InteractiveRunner()) as pipeline:
    batches_with_keys = (
        pipeline
        | "Create produce"
        >> beam.Create(
            [
                ("spring", "🍓"),
                ("spring", "🥕"),
                ("spring", "🍆"),
                ("spring", "🍅"),
                ("summer", "🥕"),
                ("summer", "🍅"),
                ("summer", "🌽"),
                ("summer", "🌽"),
                ("fall", "🥕"),
                ("fall", "🍅"),
                ("winter", "🍆"),
            ]
        )
        | "Group into batches" >> beam.GroupIntoBatches(2)
        | beam.Values()
        | beam.Map(print)
    )
```

**Comment by hoangvu-ct** [comment]
@liferoad It seems like `beam.Create` does not reproduce the issue. `beam.ReadFromTextFile` does:

```python
import apache_beam as beam

with beam.Pipeline() as pipeline:
    batches_with_keys = (
        pipeline
        | "Create produce" >> beam.io.ReadFromText(file_pattern='test.jsonl')
        | "Key by season" >> beam.Map(lambda e: (e["key"], e))
        | "Group key" >> beam.GroupIntoBatches(2, 1)
        | beam.Map(print)
    )
```

The `test.jsonl` file:
```jsonl
{"key": "spring", "value": "🍓"}
{"key": "spring", "value": "🥕"}
{"key": "spring", "value": "🍆"}
{"key": "summer", "value": "🥕"}
{"key": "summer", "value": "🍅"}
{"key": "spring", "value": "🍅"}
{"key": "summer", "value": "🌽"}
{"key": "summer", "value": "🌽"}
{"key": "fall", "value": "🥕"}
{"key": "fall", "value": "🍅"}
{"key": "winter", "value": "🍆"}
```

**Comment by liferoad** [comment]
Got it. Thanks. I can reproduce it now.

**Comment by Abacn** [comment]
Create does not reproduce it because Create create elements at pipeline construction time, while ReadFromText is a SDF source. A simpler way to reproduce is to use a synthetic_source (which is also a SDF source)

```
with beam.Pipeline() as pipeline:
    batches_with_keys = (
        pipeline
        | beam.io.Read(SyntheticSource({'numRecords': 10, 'keySizeBytes': 1, 'valueSizeBytes': 1}))
        | "Group key" >> beam.GroupIntoBatches(2, 1)
        | beam.Map(print)
    )
```

Error message (master):

```
ERROR:apache_beam.runners.direct.executor:Giving up after 4 attempts.
WARNING:apache_beam.runners.direct.executor:A task failed with exception: create_invoker() takes at least 2 positional arguments (1 given) [while running 'Read/SDFBoundedSourceReader/ParDo(SDFBoundedSourceDoFn)/pair']
Traceback (most recent call last):
  File "apache_beam\runners\common.py", line 1459, in apache_beam.runners.common.DoFnRunner._invoke_bundle_method
  File "apache_beam\runners\common.py", line 554, in apache_beam.runners.common.DoFnInvoker.invoke_start_bundle
  File "apache_beam\runners\common.py", line 560, in apache_beam.runners.common.DoFnInvoker.invoke_start_bundle
  File "F:\Py\beampy38\lib\site-packages\apache_beam\runners\direct\sdf_direct_runner.py", line 122, in start_bundle
    self._invoker = DoFnInvoker.create_invoker(
  File "apache_beam\runners\common.py", line 444, in apache_beam.runners.common.DoFnInvoker.create_invoker
TypeError: create_invoker() takes at least 2 positional arguments (1 given)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\groupintobatchtest.py", line 9, in <module>
    batches_with_keys = (
  File "F:\Py\beampy38\lib\site-packages\apache_beam\pipeline.py", line 601, in __exit__
    self.result.wait_until_finish()
  File "F:\Py\beampy38\lib\site-packages\apache_beam\runners\direct\direct_runner.py", line 588, in wait_until_finish
    self._executor.await_completion()
  File "F:\Py\beampy38\lib\site-packages\apache_beam\runners\direct\executor.py", line 432, in await_completion
    self._executor.await_completion()
  File "F:\Py\beampy38\lib\site-packages\apache_beam\runners\direct\executor.py", line 480, in await_completion
    raise update.exception
  File "F:\Py\beampy38\lib\site-packages\apache_beam\runners\direct\executor.py", line 370, in call
    self.attempt_call(
  File "F:\Py\beampy38\lib\site-packages\apache_beam\runners\direct\executor.py", line 404, in attempt_call
    evaluator.start_bundle()
  File "F:\Py\beampy38\lib\site-packages\apache_beam\runners\direct\transform_evaluator.py", line 870, in start_bundle
    self.runner.start()
  File "apache_beam\runners\common.py", line 1476, in apache_beam.runners.common.DoFnRunner.start
  File "apache_beam\runners\common.py", line 1461, in apache_beam.runners.common.DoFnRunner._invoke_bundle_method
  File "apache_beam\runners\common.py", line 1508, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam\runners\common.py", line 1459, in apache_beam.runners.common.DoFnRunner._invoke_bundle_method
  File "apache_beam\runners\common.py", line 554, in apache_beam.runners.common.DoFnInvoker.invoke_start_bundle
  File "apache_beam\runners\common.py", line 560, in apache_beam.runners.common.DoFnInvoker.invoke_start_bundle
  File "F:\Py\beampy38\lib\site-packages\apache_beam\runners\direct\sdf_direct_runner.py", line 122, in start_bundle
    self._invoker = DoFnInvoker.create_invoker(
  File "apache_beam\runners\common.py", line 444, in apache_beam.runners.common.DoFnInvoker.create_invoker
TypeError: create_invoker() takes at least 2 positional arguments (1 given) [while running 'Read/SDFBoundedSourceReader/ParDo(SDFBoundedSourceDoFn)/pair']
```

**Comment by liferoad** [comment]
I see. Thanks for explaining this. I also added this as another test. Note the PR only fixes the `output_handler` issue. DirectRunner cannot support this use case now.
