### ISSUE TITLE
[Failing Test]: beam_PostCommit_Java_InfluxDbIO_IT_PR 

### ISSUE THREAD

**Issue by riteshghorse** [apache/beam#26866]
### What happened?

Test failure in InfluxDbIO for this test:
```
org.apache.beam.sdk.io.influxdb.InfluxDbIOIT > testWriteAndReadWithSingleMetricWithCustomRetentionPolicy FAILED
    java.lang.AssertionError: Count All/Flatten.PCollections.out: 
    Expected: <2000L>
         but: was <1999L>
        at org.apache.beam.sdk.testing.PAssert$PAssertionSite.capture(PAssert.java:175)
        at org.apache.beam.sdk.testing.PAssert.thatSingleton(PAssert.java:498)
        at org.apache.beam.sdk.testing.PAssert.thatSingleton(PAssert.java:490)
        at org.apache.beam.sdk.io.influxdb.InfluxDbIOIT.testWriteAndReadWithSingleMetricWithCustomRetentionPolicy(InfluxDbIOIT.java:310)

        Caused by:
        java.lang.AssertionError: 
        Expected: <2000L>
             but: was <1999L>
            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
            at org.apache.beam.sdk.testing.PAssert$AssertIsEqualTo.apply(PAssert.java:1643)
            at org.apache.beam.sdk.testing.PAssert$AssertIsEqualTo.apply(PAssert.java:1634)
            at org.apache.beam.sdk.testing.PAssert$CheckRelationAgainstExpected.apply(PAssert.java:1299)
            at org.apache.beam.sdk.testing.PAssert$CheckRelationAgainstExpected.apply(PAssert.java:1279)
            at org.apache.beam.sdk.testing.PAssert.doChecks(PAssert.java:1621)
            at org.apache.beam.sdk.testing.PAssert$SingletonCheckerDoFn.processElement(PAssert.java:1614)
            at org.apache.beam.sdk.testing.PAssert$SingletonCheckerDoFn$DoFnInvoker.invokeProcessElement(Unknown Source)
            at org.apache.beam.repackaged.direct_java.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:211)
            at org.apache.beam.repackaged.direct_java.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:188)
            at org.apache.beam.repackaged.direct_java.runners.core.SimplePushbackSideInputDoFnRunner.processElementInReadyWindows(SimplePushbackSideInputDoFnRunner.java:79)
            at org.apache.beam.runners.direct.ParDoEvaluator.processElement(ParDoEvaluator.java:244)
            at org.apache.beam.runners.direct.DoFnLifecycleManagerRemovingTransformEvaluator.processElement(DoFnLifecycleManagerRemovingTransformEvaluator.java:54)
            at org.apache.beam.runners.direct.DirectTransformExecutor.processElements(DirectTransformExecutor.java:165)
            at org.apache.beam.runners.direct.DirectTransformExecutor.run(DirectTransformExecutor.java:129)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
            at java.util.concurrent.FutureTask.run(FutureTask.java:266)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
            at java.lang.Thread.run(Thread.java:750)

```

Log link: https://ci-beam.apache.org/job/beam_PostCommit_Java_InfluxDbIO_IT_PR/4/consoleText

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by riteshghorse** [comment]
@Abacn (feel free to triage)

**Comment by Abacn** [comment]
Yeah it is long flaky: https://github.com/apache/beam/issues/23286#issuecomment-1341548232

**Comment by riteshghorse** [comment]
Got it. I'll re run but moving it to 2.49 is fine I guess
