### ISSUE TITLE
[Failing Test]: Cpython 3.7.17 broke Python 3.7 unit tests on Github actions

### ISSUE THREAD

**Issue by AnandInguva** [apache/beam#27193]
### What happened?

`actions/setup-python@v4` installed Cpython 3.7.17 and it results in a bug.  

Error log: https://github.com/apache/beam/actions/runs/5317877182/jobs/9628816900

```
Traceback (most recent call last):
  File "apache_beam/examples/complete/autocomplete_test.py", line 26, in <module>
    import apache_beam as beam
  File "/Users/runner/work/beam/beam/sdks/python/target/.tox/py37/lib/python3.7/site-packages/apache_beam/__init__.py", line 85, in <module>
    import apache_beam.internal.pickler
  File "/Users/runner/work/beam/beam/sdks/python/target/.tox/py[37](https://github.com/apache/beam/actions/runs/5317877182/jobs/9628816900#step:6:38)/lib/python3.7/site-packages/apache_beam/internal/pickler.py", line 31, in <module>
    from apache_beam.internal import cloudpickle_pickler
  File "/Users/runner/work/beam/beam/sdks/python/target/.tox/py37/lib/python3.7/site-packages/apache_beam/internal/cloudpickle_pickler.py", line 31, in <module>
    import bz2
  File "/Users/runner/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/bz2.py", line 19, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'
```

This is working on python 3.7.16

### Issue Failure

Failure: Test is flaky

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
from browsing it is an artifact most likely due to incomplete python install (e.g. https://stackoverflow.com/questions/50335503/no-module-named-bz2-in-python3) and given that beam has dropped python 3.7 support, should this be closed as not planned?

**Comment by AnandInguva** [comment]
Closing this as we stopped supporting python 3.7
