### ISSUE TITLE
[Failing Test]: Python flink runner load test failing

### ISSUE THREAD

**Issue by Abacn** [apache/beam#27601]
### What happened?

Found that Python Flink runner load tests all broken since Jul 20, e.g. https://ci-beam.apache.org/view/LoadTests/job/beam_LoadTests_Python_Combine_Flink_Batch/

```
01:40:48 ERROR:root:java.util.concurrent.TimeoutException: Timed out while waiting for command 'docker run -d --network=host --env=DOCKER_MAC_CONTAINER=null gcr.io/apache-beam-testing/beam_portability/beam_python3.8_sdk:latest --id=1-1 --provision_endpoint=localhost:43365'
01:40:52 INFO:apache_beam.runners.portability.portable_runner:Job state changed to FAILED
01:40:52 Traceback (most recent call last):
01:40:52   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
01:40:52     return _run_code(code, main_globals, None,
01:40:52   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
01:40:52     exec(code, run_globals)
01:40:52   File "/home/jenkins/jenkins-slave/workspace/beam_LoadTests_Python_Combine_Flink_Batch/src/sdks/python/apache_beam/testing/load_tests/combine_test.py", line 129, in <module>
01:40:52     CombineTest().run()
01:40:52   File "/home/jenkins/jenkins-slave/workspace/beam_LoadTests_Python_Combine_Flink_Batch/src/sdks/python/apache_beam/testing/load_tests/load_test.py", line 152, in run
01:40:52     state = self.result.wait_until_finish(duration=self.timeout_ms)
01:40:52   File "/home/jenkins/jenkins-slave/workspace/beam_LoadTests_Python_Combine_Flink_Batch/src/sdks/python/apache_beam/runners/portability/portable_runner.py", line 614, in wait_until_finish
01:40:52     raise self._runtime_exception
01:40:52 RuntimeError: Pipeline load-tests-python-flink-batch-combine-1-0720035125_c0b4d9c6-53f4-489b-90a5-f3885a9192b8 failed in state FAILED: java.util.concurrent.TimeoutException: Timed out while waiting for command 'docker run -d --network=host --env=DOCKER_MAC_CONTAINER=null gcr.io/apache-beam-testing/beam_portability/beam_python3.8_sdk:latest --id=1-1 --provision_endpoint=localhost:43365'
```

the first failing test run on Jul 20, 2023, 5:28 AM UTC using snapshot containers on Jul 19, 2023, 8:45 PM UTC.

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
Tests back green: https://ci-beam.apache.org/view/LoadTests/job/beam_LoadTests_Python_Combine_Flink_Batch/
