### ISSUE TITLE
[Failing Test]: java:container:pullLicense fail at install pyyaml affecting all XVR Tests

### ISSUE THREAD

**Issue by Abacn** [apache/beam#27925]
### What happened?

Seems affected by https://github.com/yaml/pyyaml/issues/601

Fail when trying to install pyyaml from source:

```
07:45:28   Downloading PyYAML-5.4.1.tar.gz (175 kB)
07:45:28      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 kB 5.7 MB/s eta 0:00:00
07:45:28   Installing build dependencies: started
07:45:32   error: subprocess-exited-with-error
07:45:32   
07:45:32   × Getting requirements to build wheel did not run successfully.
07:45:32       Traceback (most recent call last):
07:45:32         File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_XVR_Direct/src/sdks/java/container/build/virtualenv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
07:45:32           main()
07:45:32         File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_XVR_Direct/src/sdks/java/container/build/virtualenv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
07:45:32           json_out['return_val'] = hook(**hook_input['kwargs'])
...
07:45:32           self._add_defaults_ext()
07:45:32         File "/usr/lib/python3.11/distutils/command/sdist.py", line 312, in _add_defaults_ext
07:45:32           self.filelist.extend(build_ext.get_source_files())
07:45:32                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
07:45:32         File "<string>", line 201, in get_source_files
07:45:32         File "/usr/lib/python3.11/distutils/cmd.py", line 103, in __getattr__
07:45:32           raise AttributeError(attr)
07:45:32       AttributeError: cython_sources
07:45:32       [end of output]
```

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
Could not reproduce locally, with / without cython 0.x or 3.x in persistent python environment. Seems this only happens on Jenkins

**Comment by Abacn** [comment]
I see, it's failing on Python3.11 but pass for Python3.8 locally. Reproduce step: `./gradlew :sdks:java:container:pullLicenses -PpythonVersion=3.11`.
