### ISSUE TITLE
[Failing Test]: beam_PreCommit_Java_GCP_IO_Direct FhirIOSearchIT consistently failing on GitHub Action

### ISSUE THREAD

**Issue by Abacn** [apache/beam#28505]
### What happened?

Affected tests

FhirIOSearchIT.testFhirIOSearch[R4]

```
org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:377)
	at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:345)
	at org.apache.beam.sdk.io.gcp.healthcare.FhirIOSearchIT.testFhirIOSearch(FhirIOSearchIT.java:155)
...
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at com.google.gson.stream.JsonWriter.value(JsonWriter.java:579)
	at com.google.gson.internal.bind.TypeAdapters$28.write(TypeAdapters.java:828)
	at com.google.gson.internal.bind.TypeAdapters$28.write(TypeAdapters.java:846)
	at com.google.gson.internal.bind.TypeAdapters$28.write(TypeAdapters.java:846)
	at com.google.gson.internal.bind.TypeAdapters$28.write(TypeAdapters.java:838)
	at com.google.gson.internal.bind.TypeAdapters$28.write(TypeAdapters.java:846)
	at com.google.gson.internal.bind.TypeAdapters$28.write(TypeAdapters.java:846)
	at com.google.gson.internal.bind.TypeAdapters$28.write(TypeAdapters.java:838)
	at com.google.gson.internal.bind.TypeAdapters$28.write(TypeAdapters.java:725)
	at com.google.gson.internal.Streams.write(Streams.java:73)
	at com.google.gson.JsonElement.toString(JsonElement.java:323)
	at org.apache.beam.sdk.io.gcp.healthcare.JsonArrayCoder.encode(JsonArrayCoder.java:41)
	at org.apache.beam.sdk.io.gcp.healthcare.JsonArrayCoder.encode(JsonArrayCoder.java:28)
```

FhirIOSearchIT.testFhirIOSearchWithGenericParameters[R4]

```
org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.lang.OutOfMemoryError: Java heap space
	at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:377)
	at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:345)
	at org.apache.beam.sdk.io.gcp.healthcare.FhirIOSearchIT.testFhirIOSearchWithGenericParameters(FhirIOSearchIT.java:186)
...
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.lang.StringCoding.decode(StringCoding.java:215)
	at java.lang.String.<init>(String.java:463)
	at java.lang.String.<init>(String.java:515)
	at org.apache.beam.sdk.coders.StringUtf8Coder.readString(StringUtf8Coder.java:61)
```

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 2 (backlog / disabled test but we think the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by chamikaramj** [comment]
Another instance: https://github.com/apache/beam/actions/runs/6280184165/job/17118632816?pr=28210

Is this only failing for Github actions ? Probably should be a P1.

cc: @damondouglas

**Comment by Abacn** [comment]
same comment as #28635 - We are working on moving this test suite to large-memory worker set which would likely mitigate the issue, so no need to do with heap space for now; for test itself, may either decrease the data size since this is just an integration test; or optimize the IO

**Comment by svetakvsundhar** [comment]
.close-issue
