### ISSUE TITLE
[Bug]: Ongoing operation in Bigtable write step

### ISSUE THREAD

**Issue by chcornwell** [apache/beam#28562]
### What happened?

I have a pipeline running on Dataflow which pulls messages from PubSub and then writes to Bigtable via `BigtableIO`. We see many instances of logs such as the following:

```
Thread[DataflowWorkUnits-2,5,main]: at sun.misc.Unsafe.park(Native Method) at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215) at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078) at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467) at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:750)
```

```
Operation ongoing in step Bigtable write/applyInternal@{Pipeline.scala:55}:1/BigtableIO.WriteWithResults/ParDo(BigtableWriter) for at least 300h50m00s without outputting or completing in state finish at java.lang.Object.wait(Native Method) at java.lang.Object.wait(Object.java:502) at com.google.api.gax.batching.BatcherImpl.awaitAllOutstandingBatches(BatcherImpl.java:358) at com.google.api.gax.batching.BatcherImpl.flush(BatcherImpl.java:271) at org.apache.beam.sdk.io.gcp.bigtable.BigtableServiceImpl$BigtableWriterImpl.flush(BigtableServiceImpl.java:510) at org.apache.beam.sdk.io.gcp.bigtable.BigtableIO$BigtableWriterFn.finishBundle(BigtableIO.java:1187) at org.apache.beam.sdk.io.gcp.bigtable.BigtableIO$BigtableWriterFn$DoFnInvoker.invokeFinishBundle(Unknown Source)
```

Eventually the service gets completely stuck and quits writing anything to BT, though it never stops pulling and acknowledging messages from the subscription. I've observed this behavior in versions 2.48.0 and 2.50.0, though not in 2.33.0 (which is what we were using prior to upgrading recently). We're using Scala with Scio (at the respective versions for each Beam version we've tried).

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [X] Component: Google Cloud Dataflow Runner

**Comment by liferoad** [comment]
@mutianf FYI.

**Comment by mutianf** [comment]
Hi @chcornwell , how often does this happen?

**Comment by chcornwell** [comment]
Hey @mutianf, I see this every time we run the job, it usually runs fine for anywhere from a few hours to a day or so and then gets stuck.
