### ISSUE TITLE
[Failing Test]: ViewTest.testTriggeredLatestSingleton extremely flaky on Flink runner after #28614

### ISSUE THREAD

**Issue by Abacn** [apache/beam#29547]
### What happened?

Error message:

```
org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.lang.IllegalArgumentException: PCollection with more than one element accessed as a singleton view.
	at org.apache.beam.runners.flink.TestFlinkRunner.run(TestFlinkRunner.java:75)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:321)
Caused by: java.lang.IllegalArgumentException: PCollection with more than one element accessed as a singleton view.
	at org.apache.beam.sdk.values.PCollectionViews$SingletonViewFn2.apply(PCollectionViews.java:412)
	at org.apache.beam.sdk.values.PCollectionViews$SingletonViewFn2.apply(PCollectionViews.java:339)
	at org.apache.beam.runners.core.SideInputHandler.get(SideInputHandler.java:163)
	at org.apache.beam.runners.core.SimpleDoFnRunner.sideInput(SimpleDoFnRunner.java:246)
	at org.apache.beam.runners.core.SimpleDoFnRunner.access$1200(SimpleDoFnRunner.java:85)
	at org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.sideInput(SimpleDoFnRunner.java:400)
	at org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.sideInput(SimpleDoFnRunner.java:487)
	at org.apache.beam.sdk.transforms.ViewTest$7$DoFnInvoker.invokeProcessElement(Unknown Source)
```

### Issue Failure

Failure: Test is flaky

### Issue Priority

Priority: 2 (backlog / disabled test but we think the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
#28614 added another validate runner test (`validatesRunnerBatchWithDataStream`) so some tests get executed one more time and adds more chance to flakiness. However this particular test seems most flaky

**Comment by Abacn** [comment]
CC: @jto I am going to disable this test for now and leave this issue open until this feature is get fixed in  Flink runner BatchWithDataStream

**Comment by Abacn** [comment]
Thank you for prompt reply!

**Comment by jto** [comment]
Here's the PR https://github.com/apache/beam/pull/29557 :)
