### ISSUE TITLE
[Bug]: Typescript SDK dataflow classic template issues

### ISSUE THREAD

**Issue by dermasmid** [apache/beam#29884]
### What happened?

When trying to create a dataflow classic template (using `-runner=dataflow --template_location='${gcsPath}'`) the program never exits, which makes it hard to setup as part of CI/CD.
Also getting this error, while this happens after the template was uploaded, so it doen't effect deployment:

```
ERROR:apache_beam.runners.portability.local_job_service:Error running pipeline.
Traceback (most recent call last):
  File "/Users/cheskeltwersky/.apache_beam/cache/venvs/py-3.11-beam-2.53.0rc2-da39a3ee5e6b4b0d3255bfef95601890afd80709/lib/python3.11/site-packages/apache_beam/runners/portability/local_job_service.py", line 297, in _run_job
    self.result = self._invoke_runner()
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cheskeltwersky/.apache_beam/cache/venvs/py-3.11-beam-2.53.0rc2-da39a3ee5e6b4b0d3255bfef95601890afd80709/lib/python3.11/site-packages/apache_beam/runners/dataflow/dataflow_job_service.py", line 39, in _invoke_runner
    dataflow_runner.DataflowRunner.poll_for_job_completion(
  File "/Users/cheskeltwersky/.apache_beam/cache/venvs/py-3.11-beam-2.53.0rc2-da39a3ee5e6b4b0d3255bfef95601890afd80709/lib/python3.11/site-packages/apache_beam/runners/dataflow/dataflow_runner.py", line 142, in poll_for_job_completion
    job_id = result.job_id()
             ^^^^^^^^^^^^^^^
  File "/Users/cheskeltwersky/.apache_beam/cache/venvs/py-3.11-beam-2.53.0rc2-da39a3ee5e6b4b0d3255bfef95601890afd80709/lib/python3.11/site-packages/apache_beam/runners/dataflow/dataflow_runner.py", line 682, in job_id
    return self._job.id
           ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'
Exception in thread Thread-4 (_run_job):
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/cheskeltwersky/.apache_beam/cache/venvs/py-3.11-beam-2.53.0rc2-da39a3ee5e6b4b0d3255bfef95601890afd80709/lib/python3.11/site-packages/apache_beam/runners/portability/local_job_service.py", line 297, in _run_job
    self.result = self._invoke_runner()
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cheskeltwersky/.apache_beam/cache/venvs/py-3.11-beam-2.53.0rc2-da39a3ee5e6b4b0d3255bfef95601890afd80709/lib/python3.11/site-packages/apache_beam/runners/dataflow/dataflow_job_service.py", line 39, in _invoke_runner
    dataflow_runner.DataflowRunner.poll_for_job_completion(
  File "/Users/cheskeltwersky/.apache_beam/cache/venvs/py-3.11-beam-2.53.0rc2-da39a3ee5e6b4b0d3255bfef95601890afd80709/lib/python3.11/site-packages/apache_beam/runners/dataflow/dataflow_runner.py", line 142, in poll_for_job_completion
    job_id = result.job_id()
             ^^^^^^^^^^^^^^^
  File "/Users/cheskeltwersky/.apache_beam/cache/venvs/py-3.11-beam-2.53.0rc2-da39a3ee5e6b4b0d3255bfef95601890afd80709/lib/python3.11/site-packages/apache_beam/runners/dataflow/dataflow_runner.py", line 682, in job_id
    return self._job.id
           ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'
```

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [X] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [X] Component: Google Cloud Dataflow Runner

**Comment by dermasmid** [comment]
https://github.com/apache/beam/pull/29887 fixed the error, but it still does not exit
