### ISSUE TITLE
[Bug]: Python PostCommit test suite is failing for BigQueryIO read tests

### ISSUE THREAD

**Issue by riteshghorse** [apache/beam#30095]
### What happened?

PostCommits are continuously failing with failures in `apache_beam/io/gcp/bigquery_read_it_test.py`

Recent run - https://github.com/apache/beam/actions/runs/7635974244/job/20802248794

```
FAILED apache_beam/io/gcp/bigquery_read_it_test.py::ReadTests::test_native_source - apache_beam.runners.dataflow.dataflow_runner.DataflowRuntimeException: Dataflow pipeline failed. State: FAILED, Error:
Traceback (most recent call last):
  File "apache_beam/runners/common.py", line 1435, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 851, in apache_beam.runners.common.PerWindowInvoker.invoke_process
  File "apache_beam/runners/common.py", line 997, in apache_beam.runners.common.PerWindowInvoker._invoke_process_per_window
  File "/runner/_work/beam/beam/sdks/python/apache_beam/transforms/core.py", line 1961, in <lambda>
    wrapper = lambda x, *args, **kwargs: [fn(x, *args, **kwargs)]
  File "/runner/_work/beam/beam/sdks/python/apache_beam/testing/util.py", line 192, in _equal
    raise BeamAssertException(msg)
apache_beam.testing.util.BeamAssertException: Failed assert: [{'number': 1, 'str': 'abc'}, {'number': 2, 'str': 'def'}, {'number': 3, 'str': '??????'}, {'number': 4, 'str': '????????????'}] == [{'number': 1, 'str': 'abc'}, {'number': 1, 'str': 'abc'}, {'number': 2, 'str': 'def'}, {'number': 2, 'str': 'def'}, {'number': 4, 'str': '????????????'}, {'number': 4, 'str': '????????????'}, {'number': 3, 'str': '??????'}, {'number': 3, 'str': '??????'}], unexpected elements [{'number': 1, 'str': 'abc'}, {'number': 2, 'str': 'def'}, {'number': 4, 'str': '????????????'}, {'number': 3, 'str': '??????'}]
```

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by riteshghorse** [comment]
CC: @Abacn

**Comment by riteshghorse** [comment]
<img width="1072" alt="image" src="https://github.com/apache/beam/assets/25881114/047bc1aa-fa0c-4a58-94a1-e4dfdd957df6">
 is also failing with error:

 ```
 FAILED apache_beam/io/gcp/bigquery_file_loads_test.py::BigQueryFileLoadsIT::test_batch_copy_jobs_with_no_input_schema - AssertionError: 
Expected: (<[<BigqueryFullResultMatcher(Expected data is [(0,), (1,), (2,), (3,), (4,)])>, <BigqueryFullResultMatcher(Expected data is [(5,), (6,), (7,), (8,), (9,)])>]>)
     but: <[<BigqueryFullResultMatcher(Expected data is [(0,), (1,), (2,), (3,), (4,)])>, <BigqueryFullResultMatcher(Expected data is [(5,), (6,), (7,), (8,), (9,)])>]> was <DataflowPipelineResult 2024-01-23_22_23_28-9024953742164757457 DONE>
 ```

 which was recently added in #30015

CC: @ahmedabu98

**Comment by Abacn** [comment]
`bigquery_read_it_test.ReadTests::test_native_source` assert error with duplicate rows

**Comment by ahmedabu98** [comment]
Taking a look at `BigQueryFileLoadsIT.test_batch_copy_jobs_with_no_input_schema` now.

Although looking at the error coming out from `BigQueryFileLoadsIT. test_multiple_destinations_transform`, it looks like a separate issue:
```
E               "error": {
E                 "code": 400,
E                 "message": "Load configuration must specify at least one source URI",
E                 "errors": [
E                   {
E                     "message": "Load configuration must specify at least one source URI",
E                     "domain": "global",
E                     "reason": "invalid"
E                   }
E                 ],
E                 "status": "INVALID_ARGUMENT"
E               }
```

**Comment by Abacn** [comment]
Both tests start failing on https://github.com/apache/beam/actions/runs/7590387826, at commit https://github.com/apache/beam/commits/d5a7fc92cdfcba199f817cd0bd0793b16c5e105e/sdks/python

**Comment by ahmedabu98** [comment]
I'm able to fix `test_batch_copy_jobs_with_no_input_schema`

Still figuring out what `test_multiple_destinations_transform` is about..

**Comment by ahmedabu98** [comment]
Ahh looks like the new test changed attributes in `bigquery_file_loads.py` that apparently don't get reset after the test finishes running:
```
# reduce load job size to induce copy jobs
    bqfl._DEFAULT_MAX_FILE_SIZE = 10
    bqfl._MAXIMUM_LOAD_SIZE = 20
```
Chronologically, the following test that gets run is `test_multiple_destinations_transform` which gets affected by this and fails.
