### ISSUE TITLE
[Feature Request]: Iceberg Support for Python

### ISSUE THREAD

**Issue by asheeshgarg** [apache/beam#31830]
### What would you like to happen?

As of pyiceberg release of 0.6.0 pyiceberg gives the read write capability to read and write data to iceberg table format in Python. It will be good if we have a Source/Sink support for Iceberg in Python SDK. 

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by liferoad** [comment]
This should be available through Managed IO for Python later. @ahmedabu98

**Comment by liferoad** [comment]
https://github.com/apache/beam/pull/31495 FYI

**Comment by ahmedabu98** [comment]
@asheeshgarg just merged ##31495. See this example for how to use (note that input PCollection elements are Beam Rows)

```python
import apache_beam as beam

with beam.Pipeline() as p:
    (p 
     | beam.Create([beam.Row(...), beam.Row(...)]) 
     | beam.managed.Write(
        "iceberg",
        config={
            "table": "namespace.table",
            "catalog_name": "test-catalog",
            "catalog_properties": {
                "catalog-impl": "org.apache.iceberg.hadoop.HadoopCatalog",
                "warehouse": "path/to/warehouse". # local file system and GCS are supported
            }}))
```

**Comment by romkabauer** [comment]
@ahmedabu98 Does it require additional adjustments to support streaming mode? Or I'm just missing something?
While trying smth like
`iceberg_config = {
        "table": "test.write_read",
        "catalog_name": "default",
        "catalog_properties": {
            "type": "hadoop",
            "warehouse": "file:///test_from_kafka_to_iceberg_write",
        },
        "triggering_frequency_seconds": 30
    }

    with beam.Pipeline(options=pipeline_options) as p:
        (
            p | "ReadExpensesFromKafka" >> ReadExpensesFromKafka(
                bootstrap_servers=known_args.kafka_bootstrap,
                topics=[known_args.kafka_input],
                group_id="expenses-reader-group",
                expansion_service=get_expansion_service()
            )
            | beam.WindowInto(
                FixedWindows(1 * 30),
                trigger=Repeatedly(AfterProcessingTime(1 * 30)),
                accumulation_mode=AccumulationMode.DISCARDING
            )
            | 'Write to Iceberg' >> beam.managed.Write(
                beam.managed.ICEBERG,
                config=iceberg_config
            )
        )
`
I'm getting the following error - KeyError: 'after_synchronized_processing_time'

<details><summary>Traceback</summary>
<p>

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/beam_app/run.py", line 4, in <module>
    run()
  File "/app/beam_app/ingest_expenses_beam_app/pipeline_launcher.py", line 127, in run
    p | "ReadExpensesFromKafka" >> ReadExpensesFromKafka(
  File "/usr/local/lib/python3.10/site-packages/apache_beam/pvalue.py", line 138, in __or__
    return self.pipeline.apply(ptransform, self)
  File "/usr/local/lib/python3.10/site-packages/apache_beam/pipeline.py", line 681, in apply
    return self.apply(
  File "/usr/local/lib/python3.10/site-packages/apache_beam/pipeline.py", line 692, in apply
    return self.apply(transform, pvalueish)
  File "/usr/local/lib/python3.10/site-packages/apache_beam/pipeline.py", line 754, in apply
    pvalueish_result = self.runner.apply(transform, pvalueish, self._options)
  File "/usr/local/lib/python3.10/site-packages/apache_beam/runners/runner.py", line 191, in apply
    return self.apply_PTransform(transform, input, options)
  File "/usr/local/lib/python3.10/site-packages/apache_beam/runners/runner.py", line 195, in apply_PTransform
    return transform.expand(input)
  File "/usr/local/lib/python3.10/site-packages/apache_beam/transforms/managed.py", line 162, in expand
    return input | SchemaAwareExternalTransform(
  File "/usr/local/lib/python3.10/site-packages/apache_beam/pvalue.py", line 138, in __or__
    return self.pipeline.apply(ptransform, self)
  File "/usr/local/lib/python3.10/site-packages/apache_beam/pipeline.py", line 754, in apply
    pvalueish_result = self.runner.apply(transform, pvalueish, self._options)
  File "/usr/local/lib/python3.10/site-packages/apache_beam/runners/runner.py", line 191, in apply
    return self.apply_PTransform(transform, input, options)
  File "/usr/local/lib/python3.10/site-packages/apache_beam/runners/runner.py", line 195, in apply_PTransform
    return transform.expand(input)
  File "/usr/local/lib/python3.10/site-packages/apache_beam/transforms/external.py", line 429, in expand
    return pcolls | self._payload_builder.identifier() >> ExternalTransform(
  File "/usr/local/lib/python3.10/site-packages/apache_beam/pvalue.py", line 138, in __or__
    return self.pipeline.apply(ptransform, self)
  File "/usr/local/lib/python3.10/site-packages/apache_beam/pipeline.py", line 681, in apply
    return self.apply(
  File "/usr/local/lib/python3.10/site-packages/apache_beam/pipeline.py", line 692, in apply
    return self.apply(transform, pvalueish)
  File "/usr/local/lib/python3.10/site-packages/apache_beam/pipeline.py", line 754, in apply
    pvalueish_result = self.runner.apply(transform, pvalueish, self._options)
  File "/usr/local/lib/python3.10/site-packages/apache_beam/runners/runner.py", line 191, in apply
    return self.apply_PTransform(transform, input, options)
  File "/usr/local/lib/python3.10/site-packages/apache_beam/runners/runner.py", line 195, in apply_PTransform
    return transform.expand(input)
  File "/usr/local/lib/python3.10/site-packages/apache_beam/transforms/external.py", line 773, in expand
    self._outputs = {
  File "/usr/local/lib/python3.10/site-packages/apache_beam/transforms/external.py", line 774, in <dictcomp>
    tag: fix_output(result_context.pcollections.get_by_id(pcoll_id), tag)
  File "/usr/local/lib/python3.10/site-packages/apache_beam/runners/pipeline_context.py", line 106, in get_by_id
    self._id_to_obj[id] = self._obj_type.from_runner_api(
  File "/usr/local/lib/python3.10/site-packages/apache_beam/pvalue.py", line 209, in from_runner_api
    windowing=context.windowing_strategies.get_by_id(
  File "/usr/local/lib/python3.10/site-packages/apache_beam/runners/pipeline_context.py", line 106, in get_by_id
    self._id_to_obj[id] = self._obj_type.from_runner_api(
  File "/usr/local/lib/python3.10/site-packages/apache_beam/transforms/core.py", line 3709, in from_runner_api
    triggerfn=TriggerFn.from_runner_api(proto.trigger, context),
  File "/usr/local/lib/python3.10/site-packages/apache_beam/transforms/trigger.py", line 314, in from_runner_api
    }[proto.WhichOneof('trigger')].from_runner_api(proto, context)
  File "/usr/local/lib/python3.10/site-packages/apache_beam/transforms/trigger.py", line 734, in from_runner_api
    TriggerFn.from_runner_api(proto.repeat.subtrigger, context))
  File "/usr/local/lib/python3.10/site-packages/apache_beam/transforms/trigger.py", line 301, in from_runner_api
    return {
KeyError: 'after_synchronized_processing_time'

</p>
</details> 

As I understand after_synchronized_processing_time as trigger property was deprecated some time ago?

**Comment by romkabauer** [comment]
Yes, for example, I can write to file

```python
with beam.Pipeline(options=pipeline_options) as p:
        (
            p | "ReadExpensesFromKafka" >> ReadExpensesFromKafka(
                bootstrap_servers=known_args.kafka_bootstrap,
                topics=[known_args.kafka_input],
                group_id="expenses-reader-group",
                expansion_service=expansion_service
            )
            # | "Write to Iceberg" >> BeamManagedWrite(
            #     "iceberg",
            #     config=iceberg_config,
            #     expansion_service=expansion_service
            # )
            | "CastToString" >> beam.Map(lambda x: str(x))
            | beam.WindowInto(
                FixedWindows(1 * 30),
                trigger=Repeatedly(AfterProcessingTime(1 * 30)),
                accumulation_mode=AccumulationMode.DISCARDING
            )
            | 'Write to file' >> WriteToFiles(
                path='test_from_kafka_to_file_write',
                shards=1,
                max_writers_per_bundle=0
            )
        )
``` 

<details><summary>SDK harness image</summary>
<p>

FROM apache/beam_python3.10_sdk:2.61.0

ARG BEAM_VERSION
ENV BEAM_VERSION=${BEAM_VERSION:-2.61.0}
ENV REPO_BASE_BEAM_URL=https://repo1.maven.org/maven2/org/apache/beam

RUN apt-get update && apt-get install -y default-jdk

RUN mkdir -p /opt/apache/beam/jars \
  && wget ${REPO_BASE_BEAM_URL}/beam-sdks-java-io-expansion-service/${BEAM_VERSION}/beam-sdks-java-io-expansion-service-${BEAM_VERSION}.jar \
          --progress=bar:force:noscroll -O /opt/apache/beam/jars/beam-sdks-java-io-expansion-service.jar

COPY beam_app /app/beam_app

RUN pip install -e /app/beam_app/.

ENV PYTHONPATH="$PYTHONPATH:/app"

</p>
</details> 

<img width="506" alt="image" src="https://github.com/user-attachments/assets/8df23064-5974-43c8-9883-a0a5f54a1577" />
