### ISSUE TITLE
[Bug]: Pipeline may stuck after error thrown in transform due to racing condition in CancellableQueue

### ISSUE THREAD

**Issue by Abacn** [apache/beam#32502]
### What happened?

We've seen report ragarding pipeline stuck after error thrown in `@Setup` method in transform. It is suspected the cause attributed to CancellableQueue in Java SDK harness has the following racing condition. Sympom:

```
WARNING 2024-09-13T17:15:45.961Z Operation ongoing in bundle process_bundle-3678134576214540161-11096 for at least 06h56m00s without outputting or completing: at 
java.base@17.0.9/jdk.internal.misc.Unsafe.park(Native Method) at java.base@17.0.9/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341) at 
java.base@17.0.9/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506) at 
java.base@17.0.9/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3465) at java.base@17.0.9/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3436) at 
java.base@17.0.9/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623) at 
app//org.apache.beam.sdk.fn.CancellableQueue.take(CancellableQueue.java:95) at 
app//org.apache.beam.sdk.fn.data.BeamFnDataInboundObserver.awaitCompletion(BeamFnDataInboundObserver.java:122) at 
app//org.apache.beam.fn.harness.control.ProcessBundleHandler.processBundle(ProcessBundleHandler.java:550) at 
app//org.apache.beam.fn.harness.FnHarness$$Lambda$203/0x00007f77f52f5ef8.apply(Unknown Source) at 
app//org.apache.beam.fn.harness.control.BeamFnControlClient.delegateOnInstructionRequestType(BeamFnControlClient.java:150) at 
app//org.apache.beam.fn.harness.control.BeamFnControlClient$InboundObserver.lambda$onNext$0(BeamFnControlClient.java:115) at 
app//org.apache.beam.fn.harness.control.BeamFnControlClient$InboundObserver$$Lambda$212/0x00007f77f5301138.run(Unknown Source) at ...
```

Some Exception happened, cancel() called:

https://github.com/apache/beam/blob/aeead3f7cd33c6510555b9e9969efa4961150f7b/sdks/java/core/src/main/java/org/apache/beam/sdk/fn/CancellableQueue.java#L123

Further invocation is supposed to raise exception:

https://github.com/apache/beam/blob/aeead3f7cd33c6510555b9e9969efa4961150f7b/sdks/java/core/src/main/java/org/apache/beam/sdk/fn/CancellableQueue.java#L97

However, if in between cancel() and the next invocation, reset() is called,

https://github.com/apache/beam/blob/aeead3f7cd33c6510555b9e9969efa4961150f7b/sdks/java/core/src/main/java/org/apache/beam/sdk/fn/CancellableQueue.java#L143

exception will set to null, and runner does not know the bad status, and just waiting for elements which will never come in.

This affects Java portable runners including Dataflow runner v2.

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [X] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
thanks for information, closed the issue for now
