### ISSUE TITLE
[Bug]: Iceberg Write failing to upgrade due to "IllegalArgumentException: unable to serialize SchemaCoder"

### ISSUE THREAD

**Issue by chamikaramj** [apache/beam#32795]
### What happened?

I'm getting following (via the ExpansionService) when upgrading the Iceberg Write transform.

```
2024/10/16 02:58:02 E1016 02:58:02.041566      11 managed_transforms_worker_main.cc:138] Failed to upgrade using the expansion service manager: INTERNAL: Expansion request failed: java.lang.IllegalArgumentException: unable to serialize SchemaCoder<Schema: Fields:
2024/10/16 02:58:02 Field{name=tableIdentifierString, description=, type=STRING NOT NULL, options={{}}}
2024/10/16 02:58:02 Field{name=serializableDataFile, description=, type=ROW<path STRING NOT NULL, fileFormat STRING NOT NULL, recordCount INT64 NOT NULL, fileSizeInBytes INT64 NOT NULL, partitionPath STRING NOT NULL, partitionSpecId INT32 NOT NULL, keyMetadata BYTES, splitOffsets ARRAY<INT64 NOT NULL>, columnSizes MAP<INT32 NOT NULL, INT64 NOT NULL>, valueCounts MAP<INT32 NOT NULL, INT64 NOT NULL>, nullValueCounts MAP<INT32 NOT NULL, INT64 NOT NULL>, nanValueCounts MAP<INT32 NOT NULL, INT64 NOT NULL>, lowerBounds MAP<INT32 NOT NULL, BYTES NOT NULL>, upperBounds MAP<INT32 NOT NULL, BYTES NOT NULL>> NOT NULL, options={{}}}
2024/10/16 02:58:02 Encoding positions:
2024/10/16 02:58:02 {tableIdentifierString=0, serializableDataFile=1}
2024/10/16 02:58:02 Options:{{}}UUID: 1373ba11-1080-4271-b79a-985f2ff03727  UUID: 1373ba11-1080-4271-b79a-985f2ff03727 delegateCoder: org.apache.beam.sdk.coders.Coder$ByteBuddy$X4azj9mR@4a19cae6
2024/10/16 02:58:02     at org.apache.beam.sdk.util.SerializableUtils.serializeToByteArray(SerializableUtils.java:59)
2024/10/16 02:58:02     at org.apache.beam.sdk.util.construction.CoderTranslation.toCustomCoder(CoderTranslation.java:158)
2024/10/16 02:58:02     at org.apache.beam.sdk.util.construction.CoderTranslation.toProto(CoderTranslation.java:118)
2024/10/16 02:58:02     at org.apache.beam.sdk.util.construction.SdkComponents.registerCoder(SdkComponents.java:284)
2024/10/16 02:58:02     at org.apache.beam.sdk.util.construction.PCollectionTranslation.toProto(PCollectionTranslation.java:35)
2024/10/16 02:58:02     at org.apache.beam.sdk.util.construction.SdkComponents.registerPCollection(SdkComponents.java:239)
2024/10/16 02:58:02     at org.apache.beam.sdk.util.construction.PTransformTranslation.translateAppliedPTransform(PTransformTranslation.java:610)
2024/10/16 02:58:02     at org.apache.beam.sdk.util.construction.ParDoTranslation$ParDoTranslator.translate(ParDoTranslation.java:184)
2024/10/16 02:58:02     at org.apache.beam.sdk.util.construction.PTransformTranslation.toProto(PTransformTranslation.java:277)
2024/10/16 02:58:02     at org.apache.beam.sdk.util.construction.SdkComponents.registerPTransform(SdkComponents.java:183)
2024/10/16 02:58:02     at org.apache.beam.sdk.util.construction.PipelineTranslation$1.visitPrimitiveTransform(PipelineTranslation.java:96)
2024/10/16 02:58:02     at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:593)
2024/10/16 02:58:02     at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:585)
```

Seems like the coder for `FileWriteResult` is failing during translation. I'm not sure why the SchemaCoder didn't properly resolve for `SerializableDataFile` (so it ended up defaulting to `SerializableCoder`).

### Issue Priority

Priority: 1 (data loss / total loss of function)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by ahmedabu98** [comment]
Can you check if this works? #32796

**Comment by chamikaramj** [comment]
Getting the same error with that PR.

**Comment by ahmedabu98** [comment]
CC @reuvenlax

**Comment by ahmedabu98** [comment]
full stacktrace:

<details>

```
at org.apache.beam.sdk.util.SerializableUtils.serializeToByteArray(SerializableUtils.java:59)
        at org.apache.beam.sdk.util.construction.CoderTranslation.toCustomCoder(CoderTranslation.java:158)
        at org.apache.beam.sdk.util.construction.CoderTranslation.toProto(CoderTranslation.java:118)
        at org.apache.beam.sdk.util.construction.SdkComponents.registerCoder(SdkComponents.java:284)
        at org.apache.beam.sdk.util.construction.PCollectionTranslation.toProto(PCollectionTranslation.java:35)
        at org.apache.beam.sdk.util.construction.SdkComponents.registerPCollection(SdkComponents.java:239)
        at org.apache.beam.sdk.util.construction.PTransformTranslation.translateAppliedPTransform(PTransformTranslation.java:610)
        at org.apache.beam.sdk.util.construction.ParDoTranslation$ParDoTranslator.translate(ParDoTranslation.java:184)
        at org.apache.beam.sdk.util.construction.PTransformTranslation.toProto(PTransformTranslation.java:277)
        at org.apache.beam.sdk.util.construction.SdkComponents.registerPTransform(SdkComponents.java:183)
        at org.apache.beam.sdk.util.construction.PipelineTranslation$1.visitPrimitiveTransform(PipelineTranslation.java:96)
        at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:593)
        at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:585)
        at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:585)
        at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:585)
        at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:585)
        at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:585)
        at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:585)
        at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:585)
        at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:585)
        at org.apache.beam.sdk.runners.TransformHierarchy$Node.access$500(TransformHierarchy.java:240)
        at org.apache.beam.sdk.runners.TransformHierarchy.visit(TransformHierarchy.java:214)
        at org.apache.beam.sdk.Pipeline.traverseTopologically(Pipeline.java:477)
        at org.apache.beam.sdk.util.construction.PipelineTranslation.toProto(PipelineTranslation.java:68)
        at org.apache.beam.sdk.util.construction.PipelineTranslation.toProto(PipelineTranslation.java:59)
        at org.apache.beam.runners.dataflow.DataflowRunner.run(DataflowRunner.java:1213)
        at org.apache.beam.runners.dataflow.DataflowRunner.run(DataflowRunner.java:203)
        at org.apache.beam.sdk.Pipeline.run(Pipeline.java:325)
        at org.apache.beam.sdk.Pipeline.run(Pipeline.java:310)
        at org.apache.beam.examples.multilanguage.Temp.runJob(Temp.java:442)
        at org.apache.beam.examples.multilanguage.Temp.main(Temp.java:289)
Caused by: java.io.NotSerializableException: org.apache.beam.sdk.schemas.utils.ByteBuddyUtils$TransformingMap
        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1200)
        at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1585)
        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1542)
        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
        at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1585)
        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1542)
        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
        at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1585)
        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1542)
        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
        at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1585)
        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1542)
        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
        at org.apache.beam.sdk.util.SerializableUtils.serializeToByteArray(SerializableUtils.java:55)
        ... 30 more
```

</details>

**Comment by Abacn** [comment]
#32757 isn't in 2.60.0, should the milestone item be 2.61.0?

**Comment by reuvenlax** [comment]
I'm taking a look.

**Comment by reuvenlax** [comment]
I'm trying to repro - when I run these tests I see the following failure:

unable to serialize org.apache.beam.sdk.io.iceberg.ScanSource@490d9c41

However ScanSource is a BoundedSource, not an element. Does this have anything to do with schemas?

**Comment by reuvenlax** [comment]
@chamikaramj can you see if this works? https://github.com/apache/beam/pull/32810

**Comment by chamikaramj** [comment]
Yeah, https://github.com/apache/beam/pull/32810 works. Thank you!
