### ISSUE TITLE
[Task]: Re-Enable testPy39embeddingsMLTransform in the Python Dependency Postcommit

### ISSUE THREAD

**Issue by jrmccluskey** [apache/beam#32965]
### What needs to happen?

The python dependency postcommit suite went perma-red because of a strange failure to find the `sentence-transformers` package in HF embeddings tests despite pip showing version 2.2.2 installed. The test should be re-enabled once the problem is resolved.

### Issue Priority

Priority: 2 (default / most normal work should be filed as P2)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by liferoad** [comment]
```
>>> from sentence_transformers import SentenceTransformer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/google/home/xqhu/Dev/beam/sdks/python/test-suites/tox/py39/build/srcs/sdks/python/target/.tox-py39-embeddings/py39-embeddings/lib/python3.9/site-packages/sentence_transformers/__init__.py", line 3, in <module>
    from .datasets import SentencesDataset, ParallelSentencesDataset
  File "/usr/local/google/home/xqhu/Dev/beam/sdks/python/test-suites/tox/py39/build/srcs/sdks/python/target/.tox-py39-embeddings/py39-embeddings/lib/python3.9/site-packages/sentence_transformers/datasets/__init__.py", line 3, in <module>
    from .ParallelSentencesDataset import ParallelSentencesDataset
  File "/usr/local/google/home/xqhu/Dev/beam/sdks/python/test-suites/tox/py39/build/srcs/sdks/python/target/.tox-py39-embeddings/py39-embeddings/lib/python3.9/site-packages/sentence_transformers/datasets/ParallelSentencesDataset.py", line 4, in <module>
    from .. import SentenceTransformer
  File "/usr/local/google/home/xqhu/Dev/beam/sdks/python/test-suites/tox/py39/build/srcs/sdks/python/target/.tox-py39-embeddings/py39-embeddings/lib/python3.9/site-packages/sentence_transformers/SentenceTransformer.py", line 12, in <module>
    from huggingface_hub import HfApi, HfFolder, Repository, hf_hub_url, cached_download
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/usr/local/google/home/xqhu/Dev/beam/sdks/python/test-suites/tox/py39/build/srcs/sdks/python/target/.tox-py39-embeddings/py39-embeddings/lib/python3.9/site-packages/huggingface_hub/__init__.py)
```

**Comment by liferoad** [comment]
```
(py39-embeddings) xqhu@xqhu ~/Dev/beam$ pip list | grep sentence                                                    
sentence-transformers                 2.2.2
sentencepiece                         0.2.0
```

**Comment by liferoad** [comment]
caused by https://github.com/easydiffusion/easydiffusion/issues/1851#issuecomment-2437615074

the cached_download() function has been fully removed.

https://github.com/huggingface/huggingface_hub/releases/tag/v0.26.0
