### ISSUE TITLE
[Feature Request]: Provide error log for troubleshooting newJarGetter function

### ISSUE THREAD

**Issue by stephanusb** [apache/beam#33411]
### What would you like to happen?

I tried to run Dataflow Job in k8s job. I received the following error

```
  goroutine 1 [running]:
github.com/apache/beam/sdks/v2/go/pkg/beam/core/runtime/xlangx/expansionx.newJarGetter()
	/go/pkg/mod/github.com/apache/beam/sdks/v2@v2.61.0/go/pkg/beam/core/runtime/xlangx/expansionx/download.go:56 +0x23
github.com/apache/beam/sdks/v2/go/pkg/beam/core/runtime/xlangx/expansionx.init()
	/go/pkg/mod/github.com/apache/beam/sdks/v2@v2.61.0/go/pkg/beam/core/runtime/xlangx/expansionx/download.go:45 +0xf
```

The error returned by the `user.Current()` method is ignored, it hards for me to debug the issue https://github.com/apache/beam/blob/e68a79c03f4a059da7d62d5d1cc16e7c5c3ee504/sdks/go/pkg/beam/core/runtime/xlangx/expansionx/download.go#L55

I wish we could check the error message for troubleshooting. 

### Issue Priority

Priority: 2 (default / most feature requests should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [X] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by bnewcomer** [comment]
I just left a comment on https://github.com/apache/beam/issues/23647 with what I found to be a workaround. But I agree that there should be more helpful logging!
